### PR TITLE
UpdateServices PowerShell reference update

### PR DESCRIPTION
**Pull request by TimShererWithAquent**
[1870784](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1870784)

@PatAltimore These were mostly generated changes (inputs, outputs), but there was a weird gap:

https://docs.microsoft.com/en-us/powershell/module/updateservices/get-wsusdynamiccategory?view=windowsserver2019-ps

Look at **First** and **Skip**.  No descriptions in the current live docs. No "add descriptions" text in the generated text. Also, none of the other cmdlets in this module have those params, so I can't just copy them in.

Should I document these two?

### CODE REVIEW

**Comment by mark-phaedrus** [comment]
First and Skip appear to work the same way they do in Select-Object. In other words, if there are ten dynamic categories on the server, `Get-WSUSDynamicCategory` returns all ten. `Get-WSUSDynamicCategory -First 4` returns only the first four. `Get-WSUSDynamicCategory -Skip 3` returns the last seven (it skips the first 3 and returns all the rest). `Get-WSUSDynamicCategory -First 4 -Skip 3` returns the fourth through seventh categories.

**Comment by TimShererWithAquent** [comment]
Mark approved my text for First and Skip.

Other changes were all from PlatyPS. Ready for review, once the build runs.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by TimShererWithAquent** [comment]
@tiburd - This is ready for review.

**Review by get-itips — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by dariomws — APPROVED** [review]

**Comment by TimShererWithAquent** [comment]
@tiburd - Ready for merge.

**Pull request merged**
