### PR TITLE
Corrected CaptureType parameter desc

### PR DESCRIPTION
**Pull request by get-itips**
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/64

### CODE REVIEW

**Comment by tseward** [comment]
The Position in the -CaptureType is "4007". Should it be "Named"? Many of the parameters are using a numeric value for Position. Can you fix?

**Comment by get-itips** [comment]
Thanks @tseward for your review, I changed also that by your request.

**Comment by tseward** [comment]
I'm ok with it now. Thanks for the corrections!

**Comment by dariomws306** [comment]
Looks like the sentence "The acceptable values for this parameter are:" appear twice in the parameter description.

**Comment by get-itips** [comment]
@dariomws306 is true, I created another PR here.  @AndreaBarr please merge referenced pr

**Pull request merged**
