### PR TITLE
Update suspend-printjob.md

### PR DESCRIPTION
**Pull request by msbemba**
made changes to the ID description.

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306 @tseward

Peer review needed for this PR. Thanks.

**Comment by e0i** [comment]
@msbemba Please refer to the issue that this PR addresses. Thanks.

**Comment by dariomws306** [comment]
Hi @msbemba, please apply the same update for 2012 and 2012 R2 versions.

Thanks!

**Comment by tseward** [comment]
Change looks good.

**Comment by msbemba** [comment]
made changes to the 2012 r2 and 2012  versions of the doc via https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1331 and https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1332

**Comment by e0i** [comment]
@dariomws306 Changes for different versions of the documentation has been introduced. Please approve.

**Comment by dariomws306** [comment]
Looks good!

**Pull request merged**
