### PR TITLE
Update Get-ADTrust.md

### PR DESCRIPTION
**Pull request by sukihanabi**
#1137 
Hello Team, I did not change anything on the PR/article as the "Get-ADTrust" parameter returns all the domain trusted in AD
Kindly verify if this is correct, feel free to let me know of any actions needed to take.

_Steps taken:_ 

1.) Run **Get-ADTrust -Filter*** , shows all the domain trusted by the domain configure in AD/ADDS
see screenshot: https://snipboard.io/O2Aqls.jpg

2.) **Get-ADTrust -Filter {Target -eq "domain.info"}** and **Get-ADTrust "domain.tk"**
These returns all trusted domain objects in the domain that you are querying

see screenshot: https://snipboard.io/3k4VcI.jpg
https://snipboard.io/CYQhXc.jpg

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by get-itips** [comment]
Hello @sukihanabi  !
I think a PR to get a review was not needed here, in case you want a review by the team, you can directly ask in the issue, (as you were forced to insert a new line in a commit to be able to create it.)

I think the user is talking about having multiple domains in the same forest, each one with different trust relationships, I can not see in your screenshots, if you test this exact scenario or you have only one domain in the forest, can you clarify this?

tip: you can attach screenshots right here pasting the image into the Write box and it will be uploaded to GitHub, and it will support showing the screenshot directly without having to clic it. :)

**Comment by tseward** [comment]
Agreed, this PR should be closed as there are no changes.

**Comment by sukihanabi** [comment]
Hello @get-itips , that's right I have one domain in a forest with multiple trusted domains. I will create another domain with different trust domains , then test the command.
I created the PR because there are things we might figure out latter, after some suggestion and test , so I'll just add it here after. In that case, moving forward; I'll ask it in the issue as suggested.
Thanks for the tips; creating a PR doesn't give you an option to attach a screenshot, but here it does.

**Comment by sukihanabi** [comment]
@get-itips , tried to run the command in one AD forest with multiple domain and trusted domains, here are the result. 

The command: Get-ADTrust -Filter* , it shows all the domain trusted by the domain configure in AD/ADDS

Is there any changes needed in the article/repo? as it seems the command shows what the description says? or any test I need to run/do?

domain1
domain2

**Comment by get-itips** [comment]
So you ran the cmdlet in one of the domains and that returned ALL domains trusted in the forest? please confirm

**Comment by sukihanabi** [comment]
@get-itips , yes that's correct.

**Comment by get-itips** [comment]
Ok so no updates are needed imho

**Comment by sukihanabi** [comment]
@get-itips agreed, thank you for the help :)

**Comment by e0i** [comment]
Closing as no changes are necessary

**Pull request closed without merging**
