### PR TITLE
Added some missing information

### PR DESCRIPTION
**Pull request by get-itips**
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/491

### CODE REVIEW

**Comment by dariomws306** [comment]
I am ok with this PR.

**Comment by tseward** [comment]
Can we get all of the details flushed out, first?

**Comment by get-itips** [comment]
Hello @tseward I added some more descriptions, but, without help of the product team, I can not progress more than this. 
@yogkumgit Can you contact product team to get help on provisioningpackages module? every cmdlet from this module lacks descriptions.

Thanks to all.

**Comment by tseward** [comment]
@get-itips OK if we can't get PG traction, I'm OK with it as-is.

**Pull request merged**
