### PR TITLE
Replace all firstref instances with OS names

### PR DESCRIPTION
**Pull request by rdbahm**
This documentation contained several references to codenames - replaced these with the OS's official release names.

### CODE REVIEW

**Comment by rdbahm** [comment]
I had accidentially chosen the pull request to target "live" instead of "master." I've changed it, but I'd also be happy to rebuild this very small PR on master if preferred.

**Comment by e0i** [comment]
@get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by get-itips** [comment]
It looks ok @rdbahm 
@DaniHalfin with all these changes... what is the target branch that should be used against this repo? Thanks

**Comment by tseward** [comment]
Can you reword?

---
If RSS is disabled, network traffic is processed on a single processor core. This may impact network performance as the process utilization increases.

---

Something like that. You shouldn't need to mention the OS as RSS is a current feature in 2019, as well.

**Comment by rmca14** [comment]
No Acrolinx or staging link.

**Pull request merged**
