### PR TITLE
Update resize-vhd.md

### PR DESCRIPTION
**Pull request by msbemba**
Correct Sizebytes Uint64 value

### CODE REVIEW

**Comment by e0i** [comment]
@nenonix @JohanFreelancer9 Minor copy editing is needed for this PR. Thanks.

**Comment by tseward** [comment]
As the parameter is named `-SizeBytes`, instead of referring to the value as UInt64, can you mention the value is in _bytes_ and as you did, provide an example of 1TB = nnn bytes?

**Comment by get-itips** [comment]
ok with @tseward suggestions

**Comment by dariomws306** [comment]
Did you test it? I tested and looks like 1TB, 300GB, etc works.

Also, looks like it works for them:
https://www.considerednormal.com/2014/09/resizing-vhd-files-the-easy-way/
https://www.altaro.com/hyper-v/resize-virtual-hard-disks-hyper-v-2016/

**Comment by e0i** [comment]
> Did you test it? I tested and looks like 1TB, 300GB, etc works.
> 
> Also, looks like it works for them:
> https://www.considerednormal.com/2014/09/resizing-vhd-files-the-easy-way/
> https://www.altaro.com/hyper-v/resize-virtual-hard-disks-hyper-v-2016/

cc @msbemba

**Comment by msbemba** [comment]
@

> > Did you test it? I tested and looks like 1TB, 300GB, etc works.
> > Also, looks like it works for them:
> > https://www.considerednormal.com/2014/09/resizing-vhd-files-the-easy-way/
> > https://www.altaro.com/hyper-v/resize-virtual-hard-disks-hyper-v-2016/
> 
> cc @msbemba

@e0i  As per peers it doesn't require change. Was able to test it like Dario mentioned.

**Comment by e0i** [comment]
@AndreaBarr The PR is ready to be merged. Thanks.

**Pull request merged**
