### PR TITLE
Update add-mppreference.md

### PR DESCRIPTION
**Pull request by sowjanya365**
Issue #876 : "-ThreatIDDefaultAction_Actions" parameter value has been corrected.

### CODE REVIEW

**Comment by get-itips** [comment]
Looks ok

**Comment by e0i** [comment]
@sowjanya365 Please keep all changes that address a single issue within a single PR.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by sowjanya365** [comment]
> @sowjanya365 Please keep all changes that address a single issue within a single PR.

Hi @e0i 

Add-MpPreference.md AND set-mppreference.md both are different documents. So I've created different PRs. Kindly correct me if my understanding is not correct. Thank you.

**Comment by e0i** [comment]
@AndreaBarr The PR which is a continuation of the PR #1165 can be merged. Thanks.

**Comment by get-itips** [comment]
Hello @sowjanya365 what @e0i is telling you is that you can add files to the same PR, there is no a 1:1 relation between files and PRs.
If you work with the github UI you can clic on the branch of your PR and navigate that version of that repo and make changes to other file, that will be added as a new commit to the pr.

**Pull request merged**
