### PR TITLE
Update new-vhd.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to the doc (Example 5)

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306  @tseward

Peer review needed for this PR. Thanks.

**Comment by tseward** [comment]
One of two suggestions:

Due to the complexity of the PoSh where the Math function is often not used, please put a # comment about what this is done.

Or specify the size in bytes and again, put a # comment for how large that size is in GB. I think this would be the better option.

**Comment by dariomws306** [comment]
Same as https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1245, I think we should leave it as it is.

**Comment by e0i** [comment]
@tseward @get-itips Do you agree with Dario's suggestion that no changes are necessary?

**Comment by tseward** [comment]
> @tseward Do you agree with Dario's suggestion that no changes are necessary?

Agree

**Comment by e0i** [comment]
@officedocsbot close

**Pull request closed without merging**
