### PR TITLE
Update Set-MpPreference.md

### PR DESCRIPTION
**Pull request by pahuijbr**
DisableIntrusionPreventionSystem is a deprecated setting

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by dariomws** [comment]
@pahuijbr, it seems that the parameter is still there so I suggest that we keep the parameter with a description like "this parameter was deprecated".

Did you remove the DisableIOAVProtection parameter by accident?

I also think that the same update should be applied to other versions of Windows or at least 2022.

**Review by dariomws — COMMENTED** [review]
@pahuijbr, it seems that the parameter is still there so I suggest that we keep the parameter with a description like "this parameter was deprecated".

Did you remove the DisableIOAVProtection parameter by accident?

I also think that the same update should be applied to other versions of Windows or at least 2022.

**Comment by get-itips** [comment]
Agreed with @dariomws

**Comment by pahuijbr** [comment]
Sure, however this means we will need to update again soon. @Amir ***@***.***> for tracking.

DisableIOAVProtection is still relevant. Can someone please link the PR here?

**Comment by dariomws** [comment]
Sure:
https://github.com/MicrosoftDocs/windows-powershell-docs/pull/2757

**Comment by pahuijbr** [comment]
I did accidentally remove DisableIOAVProtection, please undo (I don't know how)?

As for the other comment regarding deprecation before removing, seems fine to me. @Amir ***@***.***> this is about PowerShell: DisableIntrusionPreventionSystem. When will the removal of this cmdlet take effect - 12/9 when we release the November platform? That would be the date where the setting is no longer visible on all Defender platforms right?

**Comment by pahuijbr** [comment]
Hello Paul,

No, actually this request came during Nov and Nov release was already Code Complete, so it will not be part of Nov release.

As @Xudong ***@***.***> suggested I first removed it from Get cmdlet and after a couple of month the Set/Remove will be removed as well.
If you prefer to get rid of them all at once, I can do it, please let me know.

Anyways, the very first deployment to customer will be Jan 2022 release.

Thanks,
Amir

From: Paul Huijbregts ***@***.***>
Sent: November 18, 2021 10:02 AM
To: MicrosoftDocs/windows-powershell-docs ***@***.***>; MicrosoftDocs/windows-powershell-docs ***@***.***>; Amir Dashti ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [MicrosoftDocs/windows-powershell-docs] Update Set-MpPreference.md (PR #2757)

I did accidentally remove DisableIOAVProtection, please undo (I don't know how)?

As for the other comment regarding deprecation before removing, seems fine to me. @Amir ***@***.***> this is about PowerShell: DisableIntrusionPreventionSystem. When will the removal of this cmdlet take effect - 12/9 when we release the November platform? That would be the date where the setting is no longer visible on all Defender platforms right?

**Comment by dariomws** [comment]
@pahuijbr, I have created a new PR to replace this one:
https://github.com/MicrosoftDocs/windows-powershell-docs/pull/2757

**Comment by e0i** [comment]
Thank you for the replacement, @dariomws. Closing this one.

**Pull request closed without merging**
