### PR TITLE
Update Update-IscsiTargetPortal.md

### PR DESCRIPTION
**Pull request by Rob-S**
Fixed spot where two lines were merged into one

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by dariomws — APPROVED** [review]
I'm ok, but it would look better if you enclose the commands and output as described here:
https://docs.microsoft.com/PowerShell/scripting/community/contributing/powershell-style-guide?view=powershell-7.1#executable-examples

**Review by get-itips — APPROVED** [review]

**Comment by get-itips** [comment]
Also agreed w/ @dariomws suggestion

**Review by tseward — APPROVED** [review]
Approved pending @dariomws suggestion

**Comment by Rob-S** [comment]
Based on requested change "it would look better if you enclose the commands and output"... The command and output were _already_ enclosed in a "```" block, starting with lines way above the one line that was changed for this patch. But the existing lines were enclosed in a single "```". So, not being clear about what was being asked to be changed, since only the last line within that already existing block was changed... simply added the "Output" tag between the commands and output - but again, that's _way_ above the line that was changed for this patch "patch-2".

**Comment by dariomws** [comment]
Thanks @Rob-S.

This is how your code should look:
image

**Comment by Rob-S** [comment]
When I try to do that, it says:
Selected user account does not exist in tenant 'Microsoft' and cannot access the application '53bb1162-c37b-4176-8ddf-ce47964c3fcd' in that tenant. The account needs to be added as an external user in the tenant first. Please use a different account.

I am not a Microsoft employee. In hindsight, when changes were requested, I should have pointed that out. The original change was simply just splitting one line into two separate lines, which had been improperly joined into a single line.

As this is the mechanism for reporting errors, what happens is the update to correct the specific error in one of the versions gets submitted through this process. Other than that specific change, to point out what the error in the page is, if any other changes, such as the cosmetic changes requested, are desired, I would claim that would fall on a Microsoft employee. Just as it falls on a Microsoft employee, who receives the notification regarding the error on the version-specific page, to propagate the correction of that error to all other versions of the page where that same error occurs.

**Comment by sdwheeler** [comment]
@Rob-S You are not allowed to have paragraphs between codeblocks in an example. This is a limitation of PlatyPS, the tool that is used to build the docs. I made changes to the file that should fix this.

See the contributors guide for more information. https://docs.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide?#formatting-cmdlet-reference-articles

**Pull request merged**
