### PR TITLE
Create PowerShell documentation for new Windows LAPS feature

### PR DESCRIPTION
**Pull request by jay98014**
# PR Summary

Hello there, super friendly PowerShell docs reviewers and editors!

This PR contains all-new content for the new [Windows LAPS feature](https://learn.microsoft.com/windows-server/identity/laps/laps-overview) which shipped recently in the April 11 2023 Windows monthly update. The new feature was shipped to Win11 SV2, Win11 SV1, Win10, Server 2022, and Server 2019.  The powershell cmdlets in this feature's new PowerShell module ("LAPS") have 100% identical behavior across all platforms.

I am also making parallel changes in the Windows code base to wire up support for downloadable PowerShell help; those updates will ship in a later update to the same platforms listed above.  

## PR Checklist

- [X] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [X] **Summary:** This PR's summary describes the scope and intent of the change.
- [X] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [X] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://learn.microsoft.com/powershell/scripting/community/contributing/overview
[style]: https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide

### CODE REVIEW

**Comment by jay98014** [comment]
@sdwheeler fyi - this is the PR that you've been helping me with.  Thanks for your awesome support! 

Reviewers:   all bugs or mistakes are mine and mine alone.

**Review by sdwheeler — CHANGES_REQUESTED** [review]
Please review the changes I made and copy the content to the 2019 folder. Change the `online version` metadata to point to 2019 in the copy.

**Comment by jay98014** [comment]
> Please review the changes I made and copy the content to the 2019 folder. Change the `online version` metadata to point to 2019 in the copy.

@sdwheeler I reviewed all of your edits and made some small followup changes.  Content is now cloned in the 2019 folder as well.

**Review by sdwheeler — APPROVED** [review]
LGTM

**Pull request merged**
