### PR TITLE
Update Set-SmbServerConfiguration.md

### PR DESCRIPTION
**Pull request by doctordns**
Changed Singing to Signing.

### CODE REVIEW

**Comment by e0i** [comment]
@doctordns Please change the target branch of the PR from `live` to `master` to continue with the review. Thank you.

**Comment by doctordns** [comment]
I have redone this PR - #1835. 

I am therefore closing this PR.

**Comment by e0i** [comment]
> I am not sure how that happened - I just clicked from the DOCs page to edit to edit the page. This took me to the Master branch. If I am meant to fork from the LIVE branch, then shouldn't Github take there rather than to Master?
> 
> Anway - I have redone this PR - #1835. I am therefore closing this PR.

@doctordns Thank you for pointing this out. 

@DaniHalfin @traya1 Recent PRs have been targeting the `live` branch probably because of this reason. Is it possible to change the default branch of the repository to `master` _(via [/settings/branches](https://github.com/MicrosoftDocs/windows-powershell-docs/settings/branches))_ without breaking the build automation? Thank you in advance.

**Comment by e0i** [comment]
@sdwheeler Most of the community contributions have been being submitted to the wrong branch because of repository configuration. Would you be able to help us out by [changing the default target of the repository](https://github.com/MicrosoftDocs/windows-powershell-docs/settings/branches) to `master` in your spare time? Thank you.

Relevant communication:
> > I am not sure how that happened - I just clicked from the DOCs page to edit to edit the page. This took me to the Master branch. If I am meant to fork from the LIVE branch, then shouldn't Github take there rather than to Master?
> > Anway - I have redone this PR - #1835. I am therefore closing this PR.
> 
> **doctordns** Thank you for pointing this out.
> 
> **DaniHalfin** **traya1** Recent PRs have been targeting the `live` branch probably because of this reason. Is it possible to change the default branch of the repository to `master` _(via [/settings/branches](https://github.com/MicrosoftDocs/windows-powershell-docs/settings/branches))_ without breaking the build automation? Thank you in advance.

**Pull request closed without merging**
