### PR TITLE
Update New-ADUser.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated LDAP display name for Office

Fixes #https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2890

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

CC : @scanum

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by get-itips** [comment]
Please review other windows versions of the article

**Comment by msbemba** [comment]
> Please review other windows versions of the article

@dariomws  I have updated the other versions of the document. Thank you.

**Review by tseward — APPROVED** [review]

**Review by get-itips — APPROVED** [review]

**Comment by scanum** [comment]
@tiburd 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Pull request merged**
