### PR TITLE
Add EncapsulationType parameter description.

### PR DESCRIPTION
**Pull request by velkovb**

### CODE REVIEW

**Comment by e0i** [comment]
@nenonix  Copy editing is needed for this PR. Thanks.

**Comment by e0i** [comment]
@dariomws306 @tseward

Peer review needed for this PR. Thanks.

**Comment by dariomws306** [comment]
I think something like this could be better:

Specifies the encapsulation type. The acceptable values for this parameter are:

- NVGRE: Network Virtualization Generic Routing Encapsulation
- VXLAN: Virtual eXtensible Local Area Network

**Comment by dariomws306** [comment]
Also apply the same update to enable-netadapterencapsulatedpackettaskoffload would be a good idea.

**Comment by tseward** [comment]
Looks good on a technical level.

**Comment by rmca14** [comment]
No Acrolinx or staging link.

**Pull request merged**
