### PR TITLE
Update Add-DtcClusterTMMapping.md

### PR DESCRIPTION
**Pull request by sowjanya365**
Replacement of the PR #1383

### CODE REVIEW

**Comment by e0i** [comment]
Replaces approved, merged and reverted PR #1383 that had been targeting the wrong branch. No further review necessary.

**Comment by traya1** [comment]
Hi @e0i and @sowjanya365,

I just wanted to confirm whether the links modified in this PR are in the correct format. As in should they be markdown links or separated text?

Thanks!

**Comment by sowjanya365** [comment]
Hi @traya1 

I was not able to submit the replacement PR with the same changes, because the changes were already pushed to live from PR #1383. And I found some links with Http. So changed Http to Https. Now I've reverted those changes. Kindly verify. Or suggest other workaround. Thank you! :)

**Comment by e0i** [comment]
Closing as the contents of #1383 is available in both `master` *and* `live`.

**Pull request closed without merging**
