### PR TITLE
Resolves #1022

### LINKED ISSUE #1022: Typo: "48-bit" should read "48-digit"
"cmdlet creates a random 48-bit recovery password"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18ba23fe-4cf9-e36c-cb26-0f04484fb392
* Version Independent ID: 4a116594-a3d6-804e-883f-72cb79e9dc21
* Content: [Add-BitLockerKeyProtector (bitlocker)](https://docs.microsoft.com/en-us/powershell/module/bitlocker/add-bitlockerkeyprotector?view=win10-ps)
* Content Source: [docset/windows/bitlocker/add-bitlockerkeyprotector.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/bitlocker/add-bitlockerkeyprotector.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

### PR DESCRIPTION
**Pull request by velkovb**
Fix typo 48-bit to 48-digit
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1022

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306 @get-itips

Peer review needed for this PR. Thanks.

**Comment by dariomws306** [comment]
I am good.

**Comment by get-itips** [comment]
ok

**Comment by e0i** [comment]
https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1083

**Comment by e0i** [comment]
@AndreaBarr This PR can be merged. Thanks.

**Pull request merged**
