### PR TITLE
Resolves #1029

### LINKED ISSUE #1029: QuarantineDuration / Quarantine­Threshold missing
Hi, the Get-Cluster output above seems to be from an older version as on recent S2016 builds there are more objects returned. Like QuarantineDuration / Quarantine­Threshold. 
Would love to see links to those values, there defaults and meanings from this page here. 
Thanks, Michael

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7df1397d-e142-f92c-0b63-45e2f7a42d7e
* Version Independent ID: 37129d51-1cbc-6dc8-87cd-29a209c1ba83
* Content: [Get-Cluster (failoverclusters)](https://docs.microsoft.com/en-us/powershell/module/failoverclusters/get-cluster?view=win10-ps#feedback)
* Content Source: [docset/windows/failoverclusters/get-cluster.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/failoverclusters/get-cluster.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

### PR DESCRIPTION
**Pull request by velkovb**
Added a new examples explaining QuarantineThreshold and QuarantineDuration
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1029

### CODE REVIEW

**Comment by e0i** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by e0i** [comment]
@dariomws306  @tseward

Peer review needed for this PR. Thanks.

**Comment by dariomws306** [comment]
Looks good!

**Comment by get-itips** [comment]
Looks ok

**Comment by tseward** [comment]
Why are we explaining just a couple of the properties of the object but not the remainder? Either explain all properties or omit them for other, more appropriate documentation.

**Comment by velkovb** [comment]
> 
> 
> Why are we explaining just a couple of the properties of the object but not the remainder? Either explain all properties or omit them for other, more appropriate documentation.

I could leave just the example and provide the explanation to the author of the issue.

**Comment by tseward** [comment]
I think the example is great. The output should be documented elsewhere. I'd imagine there is a good document on clustering that could be modified.

**Comment by e0i** [comment]
@AndreaBarr The PR can now be merged. Thanks.

**Pull request merged**
