### PR TITLE
Update Remove-Printer.md

### PR DESCRIPTION
**Pull request by msbemba**
Corrected acceptwildcard characters for Name, CimSession and  ComputerName

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1604

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by tseward** [comment]
Have you tested `-ComputerName` with a wildcard character? I would make the assumption that like most cmdlets, it must be a specific name.

    Remove-Printer -ComputerName * -Name "Microsoft XPS Document Writer"
    Remove-Printer : The spooler service is not reachable.  Ensure the spooler service is running.
    At line:1 char:1

**Comment by msbemba** [comment]
> Have you tested `-ComputerName` with a wildcard character? I would make the assumption that like most cmdlets, it must be a specific name.
> 
> ```
> Remove-Printer -ComputerName * -Name "Microsoft XPS Document Writer"
> Remove-Printer : The spooler service is not reachable.  Ensure the spooler service is running.
> At line:1 char:1
> ```

Thank you @tseward  You are right. I tested it with a wildcard on the name

 Remove-Printer -ComputerName laptop-SIJI125H -Name *micr

I'll update the PR accordingly.

**Pull request merged**
