### PR TITLE
Update Set-NetAdapterSriov.md

### PR DESCRIPTION
**Pull request by msbemba**
No vports parameter available for Set-NetAdapterSriov 

Updated the example accordingly.

Fixes #https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2903

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
CC : @scanum

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by dariomws — APPROVED** [review]

**Review by get-itips — CHANGES_REQUESTED** [review]
vports are also mentioned in the description of the article

**Comment by msbemba** [comment]
> vports are also mentioned in the description of the article

I have made those changes as suggested.

**Comment by scanum** [comment]
@tiburd 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Pull request merged**
