### PR TITLE
Resolves #905

### LINKED ISSUE #905: Firewall group is wrong
The above command to open the firewall ports is wrong.

It should be "Distributed Transaction Coordinator" group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bb83e47-15b2-86aa-f296-06a44ff798a5
* Version Independent ID: 68a4a153-4502-6620-4edc-d76829e3bc07
* Content: [Test-Dtc (msdtc)](https://docs.microsoft.com/en-us/powershell/module/msdtc/test-dtc?view=win10-ps#feedback)
* Content Source: [docset/windows/msdtc/test-dtc.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/msdtc/test-dtc.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

### PR DESCRIPTION
**Pull request by velkovb**
Changed firewall group rule from WMI to Distributed Transaction Coordinator
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/905

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by get-itips** [comment]
Looks ok

**Comment by dariomws306** [comment]
I think we could improve these lines:

1. There is a new article for netsh (it's a Win 2003 article) but I think it's even better if we replace this command with:
Enable-NetFirewallRule -DisplayGroup "Distributed Transaction Coordinator"

2. Then we can change the link to:
https://docs.microsoft.com/powershell/module/netsecurity/enable-netfirewallrule
And remove the link between brackets, we should leave only the title with the hyperlink.

3. I think we should also replace the W2012/8 and W2012R2/8.1 versions articles.

What do you think guys?

**Comment by velkovb** [comment]
@dariomws306 I like the idea. I was thinking about replacing it with PowerShell but I am not sure which version does this cmdlet require. The other articles do not have anything about the firewall so I did not edit them but probably it is a good idea to have it there as well. Will check if this works in powershell 3.0.

**Comment by get-itips** [comment]
Or we can add what @dariomws306 suggests as an alternative so we keep netsh too, as is still supported.

**Comment by velkovb** [comment]
@get-itips @dariomws306 I added suggested changes.

**Comment by get-itips** [comment]
like it... what do you think @dariomws306  ?

**Comment by dariomws306** [comment]
Looks ok now.

Maybe we can add:

For more information, see (Enable-NetFirewallRule)[https://docs.microsoft.com/powershell/module/netsecurity/enable-netfirewallrule].

**Comment by e0i** [comment]
@velkovb Please tag me after you process the final suggestion from Andres and apply (or not apply) related changes. Thanks.

**Comment by velkovb** [comment]
@dariomws306 I think we can leave it like that as we are actually at the PowerShell documentation section so it will be easy to navigate to the help for that cmdlet and we will not put too much info in the description.
@e0i I think this should be final, thanks :)

**Comment by dariomws306** [comment]
Ok, no problem with that.

**Comment by tseward** [comment]
I'm good with this.

**Comment by e0i** [comment]
@AndreaBarr The PR can be merged. Thanks.

**Pull request merged**
