### PR TITLE
Resolves #1037

### LINKED ISSUE #1037: Example Text error
says:
until either the Enable-DedupVolume -DataAccess command runs, or the restarts.

I'm guessing it should say
"runs, or the server restarts."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e95ced9-eede-d5ad-07ba-c3cd648ff445
* Version Independent ID: 3816e35d-9742-639f-3e34-54350691269d
* Content: [Disable-DedupVolume (deduplication)](https://docs.microsoft.com/en-us/powershell/module/deduplication/disable-dedupvolume?view=win10-ps)
* Content Source: [docset/windows/deduplication/disable-dedupvolume.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/deduplication/disable-dedupvolume.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

### PR DESCRIPTION
**Pull request by velkovb**
Fixed example 3 description. Update all versions of the article so they are identical.
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1037

### CODE REVIEW

**Comment by e0i** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by tseward** [comment]
Looks good.

**Comment by dariomws306** [comment]
Looks good.

**Comment by e0i** [comment]
The PR is ready for merge.

**Pull request merged**
