### PR TITLE
Changed note about AllUsers

### PR DESCRIPTION
**Pull request by get-itips**
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/344

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306 @tseward

Peer review needed for this PR. Thanks.

**Comment by tseward** [comment]
I don't have a 1709 machine or below to try it with, but if @get-itips has tested this to be accurate, I'm good with the change.

**Comment by dariomws306** [comment]
Super agree with Trevor.

**Comment by e0i** [comment]
@AndreaBarr This PR that has passed peer review can be merged. Thanks.

**Pull request merged**
