### PR TITLE
Get-ClusterLog: It is not clear where the cluster reposrts folder is.

### PR DESCRIPTION
**Pull request by HansOMartinsen**
Added a couple of spesific defentions to where the Cluster Reports Folder can be found, as it is not obious without extensive searching in other documentation.

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this community contributed PR. Thanks.

**Comment by get-itips** [comment]
Looks good.

**Comment by dariomws306** [comment]
Looks good!

**Comment by e0i** [comment]
@tseward Any further thoughts on this PR? Thanks.

**Comment by tseward** [comment]
Looks good to me.

**Comment by e0i** [comment]
@AndreaBarr This PR that has passed review is ready to be merged.

**Pull request merged**
