### PR TITLE
Patch 70

### PR DESCRIPTION
**Pull request by msbemba**

### CODE REVIEW

**Comment by e0i** [comment]
@msbemba Please resolve merge conflicts so that we can proceed with the review. Thanks.

**Comment by msbemba** [comment]
@e0i I don't see an option to resolve conflicts, it is grayed out.

**Comment by e0i** [comment]
@msbemba Followed up via Teams.

**Comment by msbemba** [comment]
Closing this PR as we have created another PR https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1456 without conflicts.

**Pull request closed without merging**
