### PR TITLE
Update Get-ADUser.md

### PR DESCRIPTION
**Pull request by justadakaje**
Adjusted the example in the Parameters > -Filter section to actually include curly braces; appears to have been copy+pasted from previous example.

### CODE REVIEW

**Comment by e0i** [comment]
@justadakaje Thank you for taking the time to improve the article. Reviewers should follow-up with their comments soon. Stay healthy.

**Comment by e0i** [comment]
@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by e0i** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by e0i** [comment]
Assigning someone to follow-up with a correction. Thank you for the feedback.

**Comment by e0i** [comment]
Ready to merge along with the follow-up PR #1914 that corrects the error in this PR.

**Comment by tiburd** [comment]
close > reopen

**Pull request merged**
