### PR TITLE
Added missing parameters

### PR DESCRIPTION
**Pull request by JoelJerkin**
Added missing parameters
#ATCP

### CODE REVIEW

**Comment by BarbaraSelden** [comment]
#signoff

**Review by sdwheeler — CHANGES_REQUESTED** [review]
The version for Server 2022 needs to be updated as well.

**Review by dariomws — APPROVED** [review]
Please don't forget to apply the same update to 2022 version as Sean recommended.

**Review by get-itips — APPROVED** [review]
I am ok after @sdwheeler request

**Review by tseward — APPROVED** [review]
Also OK after suggested changes are made.

**Comment by sdwheeler** [comment]
@andyruth No, the submitter has not updated all affected versions.

**Review by JoelJerkin — COMMENTED** [review]
Updated documents for both WS2019 and WS2022 to match

**Comment by andyruth** [comment]
Hi all - can we get this pushed out?

**Review by sdwheeler — CHANGES_REQUESTED** [review]
Remove duplicate content

**Review by sdwheeler — APPROVED** [review]

**Pull request merged**
