### PR TITLE
Add link to the list of Input methods on Set-WinUserLanguageList

### PR DESCRIPTION
**Pull request by DJm00n**
Add link to the list of `Input methods` on `Set-WinUserLanguageList` page.

# PR Summary

## PR Checklist

- [x] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [x] **Summary:** This PR's summary describes the scope and intent of the change.
- [x] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [x] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://learn.microsoft.com/powershell/scripting/community/contributing/overview
[style]: https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by DJm00n** [comment]
@JohanFreelancer9 what should be done to this get merged?

**Comment by JohanFreelancer9** [comment]
> @JohanFreelancer9 what should be done to this get merged?

@scanum, can you please assist? Thanks.

**Review by get-itips — COMMENTED** [review]
Agree when @tseward suggestion is applied

**Comment by DJm00n** [comment]
@tseward @get-itips please take a look now.

**Review by get-itips — APPROVED** [review]

**Comment by scanum** [comment]
@tiburd 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by tiburd** [comment]
@DJm00n 
Hi Dimitriy,

Please complete the checklist. We're unable to merge this pull request until after all checklist items are selected as complete.

After you do that, please @ mention me in a comment in this PR, then I'll merge it if it passes review at that time.

Thank you!

**Comment by DJm00n** [comment]
@tiburd done.

**Pull request merged**
