### PR TITLE
Remove extraneous space

### PR DESCRIPTION
**Pull request by goldstar611**
# PR Summary
Remove extraneous space from example command.

## PR Checklist

- [x] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [x] **Summary:** This PR's summary describes the scope and intent of the change.
- [x] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [x] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://learn.microsoft.com/powershell/scripting/community/contributing/overview
[style]: https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by get-itips — APPROVED** [review]
Can you please check if the other Operating System articles for the same cmdlet require the same edit? thanks

**Comment by goldstar611** [comment]
> Can you please check if the other Operating System articles for the same cmdlet require the same edit? thanks

changes pushed

**Comment by goldstar611** [comment]
@microsoft-github-policy-service agree

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by goldstar611** [comment]
cla signed, anything left to do on my end?

**Review by msbemba — APPROVED** [review]

**Comment by goldstar611** [comment]
any good news?

**Pull request closed without merging**
