### PR TITLE
Change http to https

### PR DESCRIPTION
**Pull request by v-alji**
The background was Microsoft security scan, checks website for URLs to Microsoft properties or resources that explicitly specify HTTP. WebScout was reporting "Explicit HTTP internal URLS" in fresh content, the change was to fix them all.

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]
Copy review.

**Comment by OsmondJiang** [comment]
@JohanFreelancer9 could you help merge this PR? we don't have the permission to merge it.

**Comment by JohanFreelancer9** [comment]
@OsmondJiang - I also do not have permission to merge.
@e0i Could you please assist? Thanks.

**Comment by traya1** [comment]
Hi @v-alji,

Are you working with a MARVEL team/writer for these proposed changes?

**Comment by v-alji** [comment]
> Hi @v-alji,
> 
> Are you working with a MARVEL team/writer for these proposed changes?

No, I am a member from DevRel, according to Microsoft security policy, checks website for URLs to Microsoft properties or resources that explicitly specify HTTP. The code change was to fix the issue.

**Pull request closed without merging**
