### PR TITLE
Update Add-DnsServerQueryResolutionPolicy.md

### PR DESCRIPTION
**Pull request by msbemba**
Corrected the format for creiteria

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1880

**Comment by e0i** [comment]
cc @dariomws @get-itips @tseward

**Comment by get-itips** [comment]
The criteria is also mentioned in FQDN, InternetProtocol, QType, ServerInterfaceIP, TimeOfDay andTransportProtocol parameter descriptions

**Comment by get-itips** [comment]
Also, the document currently says

> The operator is either EQ or NE. You can specify no more than one of each operator in the string.

Did you check the accepted combinations? Thank you

**Comment by dariomws** [comment]
Agree with @get-itips, the same should be fixed in the description of the following parameters:
ClientSubnet
Fqdn
InternetProtocol
QType
ServerInterfaceIP
TimeOfDay
TransportProtocol

**Comment by tseward** [comment]
Agree with @dariomws and @get-itips

**Comment by msbemba** [comment]
> Also, the document currently says
> 
> > The operator is either EQ or NE. You can specify no more than one of each operator in the string.
> 
> Did you check the accepted combinations? Thank you

Yes @get-itips The accepted combinations are to use the operator (EQ and/or NE with multiple values, But cannot use the same operator more than once in a criterion.  I'm editing the document to reflect the change on all parameter sets like you and @dariomws mentioned. 

Thanks again.

Sri

**Comment by get-itips** [comment]
Thanks @msbemba

**Comment by msbemba** [comment]
Made the same changes to 
ClientSubnet
Fqdn
InternetProtocol
QType
ServerInterfaceIP
TimeOfDay
TransportProtocol

**Comment by garycentric** [comment]
In review.

**Pull request merged**
