### PR TITLE
Fixed powershell command that was missing a quote

### PR DESCRIPTION
**Pull request by john159753**

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by get-itips — APPROVED** [review]

**Review by tseward — APPROVED** [review]

**Review by dariomws — APPROVED** [review]

**Comment by dariomws** [comment]
@john159753 could you kindly apply the same fix for other versions of Windows?

**Comment by john159753** [comment]
> @john159753 could you kindly apply the same fix for other versions of Windows?

Should be good now!

**Comment by dariomws** [comment]
Thank you @john159753!

**Comment by e0i** [comment]
@tiburd Ready to merge.

**Pull request merged**
