### PR TITLE
Update Remove-NetIPAddress.md (via #1772)

### PR DESCRIPTION
**Pull request by e0i**
@JulianTurner wrote:
> changed the description of the comment because it was missleading and incomplete

This PR is a follow-up replacement of PR #1772, with applied copy editing suggestions, and with correct merge target.

 The PR had passed review via @tseward, @get-itips and @JohanFreelancer9

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws @get-itips @tseward

Please confirm reproduction. Thanks.

**Comment by get-itips** [comment]
The description of the example should be outside and under the code block.

**Comment by tseward** [comment]
I'm confused about this change -- it looks like it just incorrectly moves the cmdlet description from outside of the PoSh block into it.

**Comment by JohanFreelancer9** [comment]
I agree with other reviewers. I don't think this PR should be approved.

**Comment by e0i** [comment]
Closing the reproduction via comments.

**Pull request closed without merging**
