### PR TITLE
More comprehensive examples

### PR DESCRIPTION
**Pull request by skycommand**
Originally, this page showed three examples, but the only difference between them was in just one switch. This update replaces two of those examples to demonstrate:
- How to designate multiple volumes for scan
- How to scan a volume without a drive letter

These changes have already been applied to [winserver2012r2-ps/storage/Repair-Volume.md](https://github.com/MicrosoftDocs/windows-powershell-docs/edit/master/docset/winserver2012r2-ps/storage/Repair-Volume.md), following my pull request #279.

### CODE REVIEW

**Comment by kenwith** [comment]
Looks like some conflicts. Let me know if I can help.

**Comment by skycommand** [comment]
@kenwith So I see. The conflict seems to be in the metadata/header area, so I assume the master takes precedence. But the conflict resolution UI seems not to respond to me. I assume it is because I do not have permissions for it.

**Comment by kenwith** [comment]
let me see if I have permissions.

**Comment by kenwith** [comment]
@skycommand - you were 100% correct. It was the metadata. I resolved it and confirmed the example. Much appreciated for sharing your expertise to make the docs better. This is a nice example and much clearer than before.

**Comment by skycommand** [comment]
@kenwith You are welcome. 😊 Glad to be of help. Would you please make sure #540 is handled in the same manner? Thanks in advance.

**Pull request merged**
