### PR TITLE
Correct export path in example

### PR DESCRIPTION
**Pull request by outorted**
The example is to create an HTML report, but the path of the report had the extension .xml. For an HTML report, this should be HTML

# PR Summary

## PR Checklist

- [x] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [x] **Summary:** This PR's summary describes the scope and intent of the change.
- [x] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [x] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://learn.microsoft.com/powershell/scripting/community/contributing/overview
[style]: https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by get-itips — APPROVED** [review]

**Comment by scanum** [comment]
@tiburd
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by tiburd** [comment]
@outorted 
Hello - thank you for your contribution.
Before we can merge this pull request, the PR Checklist must be complete:
image

After you complete the checklist, please @ mention me so that I can merge the pull request.

Thank you!

**Comment by outorted** [comment]
@tiburd sorry, I've not done this before... I just ticked the boxes in the previous comment. I hope that's OK. If you need anything else from me, then please let me know.

**Comment by tiburd** [comment]
> @tiburd sorry, I've not done this before... I just ticked the boxes in the previous comment. I hope that's OK. If you need anything else from me, then please let me know.

@outorted 
No worries at all! 
I'll merge the pull request after it passes all the required checks....
Thanks!

**Pull request merged**
