### PR TITLE
Update Remove-AppxPackage.md

### PR DESCRIPTION
**Pull request by msbemba**
Syntax is already added to the document

### CODE REVIEW

**Comment by e0i** [comment]
cc @dariomws @get-itips @tseward

**Comment by tseward** [comment]
I'm confused about what this change is. Is it just reordering the parameter sets?

**Comment by get-itips** [comment]
I don't quite understand either, is there an issue related to this PR ?

**Comment by msbemba** [comment]
The live document doesn't have the other syntaxes in there. The master branch shows all syntaxes on the doc.

**Comment by msbemba** [comment]
Thank you @dariomws I have added the parameter name(S) to the document.

**Comment by dariomws** [comment]
I think we should replace Parameter Set 1, 2, 3 and 4 with a better title.

**Comment by e0i** [comment]
@msbemba Sriraman, Can you refer to the original issue that this PR resolved to provide reviewers with more context? Thank you.

**Comment by msbemba** [comment]
@dariomws I have added names to the parameter sets as per your suggestion. let me know if it looks ok now.

**Comment by msbemba** [comment]
Issue# https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1751

**Comment by get-itips** [comment]
@msbemba 
I used platyps to create the cmdlet's documentation and this is the parameter set section, notice that we can not come up with any name for the parameter sets.
 

<pre>
## SYNTAX

### RemoveByPackageSet (Default)
```
Remove-AppxPackage [-Package] <String> [-PreserveApplicationData] [-WhatIf] [-Confirm] [<CommonParameters>]
```

### AllUsersSet
```
Remove-AppxPackage [-Package] <String> [-AllUsers] [-WhatIf] [-Confirm] [<CommonParameters>]
```

### UserSet
```
Remove-AppxPackage [-Package] <String> -User <String> [-WhatIf] [-Confirm] [<CommonParameters>]
```
</pre>

**Comment by msbemba** [comment]
> @msbemba
> I used platyps to create the cmdlet's documentation and this is the parameter set section, notice that we can not come up with any name for the parameter sets.
> 
> ## SYNTAX
> 
> ### RemoveByPackageSet (Default)
> ```
> Remove-AppxPackage [-Package]  [-PreserveApplicationData] [-WhatIf] [-Confirm] []
> ```
> 
> ### AllUsersSet
> ```
> Remove-AppxPackage [-Package]  [-AllUsers] [-WhatIf] [-Confirm] []
> ```
> 
> ### UserSet
> ```
> Remove-AppxPackage [-Package]  -User  [-WhatIf] [-Confirm] []
> ```

Thank you @get-itips  I have made changes to the PR per your suggestion. Let me know if this looks ok now.

**Comment by get-itips** [comment]
Looks better now @msbemba Thanks

**Comment by e0i** [comment]
Thank you all for the productive discussion.

**Pull request merged**
