### PR TITLE
Update ServerManager.md

### PR DESCRIPTION
**Pull request by sowjanya365**
Missing description has been updated now in the below articles. 
docset/winserver2012r2-ps/servermanager/ServerManager.md
docset/winserver2012-ps/servermanager/ServerManager.md

### CODE REVIEW

**Comment by e0i** [comment]
@nenonix Copy editing is needed for this PR. Thanks.

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by tseward** [comment]
This looks good.

**Comment by sowjanya365** [comment]
> I am not sure about the dash... But then looks good.

Hi @dariomws306 

I've added the dash to the sentence after referring to the other articles with the same kind of description. So I just started following the same format. Hope this clarifies. Let me know if you think we need to omit the dash. Thank you! :)

"This reference provides cmdlet descriptions and syntax for all Server Manager-specific cmdlets"

**Comment by sowjanya365** [comment]
> Yes, it's true @sowjanya365, sorry about that. I see the dash in other similar articles after I left this comment. So I think it's ok. Thanks!

Thank you, @dariomws306 :)

**Pull request merged**
