### PR TITLE
chanaged the example

### PR DESCRIPTION
**Pull request by MaratMussabekov**
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2186

### CODE REVIEW

**Comment by MaratMussabekov** [comment]
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @e0i, for your information

Thank you

**Comment by e0i** [comment]
@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

**Review by dariomws — APPROVED** [review]
I think we should add the same information for the W2012 R2 article.

**Review by get-itips — APPROVED** [review]

**Comment by MaratMussabekov** [comment]
hello @dariomws ,
done, please have a look at #2212.
Thank you

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by tseward — APPROVED** [review]

**Pull request merged**
