### PR TITLE
Fixed error in example 8

### LINKED ISSUE #1742: Error in Example 8
Example 8 is wrong - datatype of value of the parameter "-Value" in this example (String) does not match datatype of this DHCP Option definition (BinaryData).
Thus example throws error:
`
Set-DhcpServerv4OptionValue : Parameters for option value to be set for option ID 5 do not match with option definition on DHCP server
`

Current incorrect code:
```PowerShell
Set-DhcpServerv4OptionValue -ComputerName "dhcpserver.contoso.com" -ScopeId 10.10.10.0 -VendorClass "MSUCClient" -OptionId 5 -Value "6874747073"
````

Correct code:
```PowerShell
Set-DhcpServerv4OptionValue -ComputerName "dhcpserver.contoso.com" -ScopeId 10.10.10.0 -VendorClass "MSUCClient" -OptionId 5 -Value ([System.Text.Encoding]::ASCII.GetBytes("/CertProv/CertProvisioningService.svc"))
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a5853e3-f2b4-cce7-fd6f-c1d677d578f5
* Version Independent ID: cac2dbc1-f5d6-d3fd-ffe8-790989e10bd7
* Content: [Set-DhcpServerv4OptionValue (dhcpserver)](https://docs.microsoft.com/en-us/powershell/module/dhcpserver/set-dhcpserverv4optionvalue?view=win10-ps)
* Content Source: [docset/windows/dhcpserver/Set-DhcpServerv4OptionValue.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/dhcpserver/Set-DhcpServerv4OptionValue.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

### PR DESCRIPTION
**Pull request by shivtorov**
resolves #1742

### CODE REVIEW

**Comment by shivtorov** [comment]
Just wanted to clarify the context of the Example 8 - it is about Skype for Business Server phones.
The DHCP option in question is defined as follows:
``` PowerShell
Add-DhcpServerv4Class -Name 'MSUCClient' -Type Vendor -Data 'MS-UC-Client'
Add-DhcpServerv4OptionDefinition -VendorClass 'MSUCClient' -OptionId 5 -Name 'CertProvRelPath' -Type BinaryData -Description 'Cert Prov Path'
Set-DhcpServerv4OptionValue -VendorClass 'MSUCClient' -OptionId 5 -Value ([System.Text.Encoding]::ASCII.GetBytes("/CertProv/CertProvisioningService.svc"))
```

**Comment by e0i** [comment]
Hello, @shivtorov Can you change the target branch of the PR to `master` from `live`? Thank you.

**Comment by shivtorov** [comment]
@e0i done

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by tseward** [comment]
You should be able to use `Get-Content -Encoding Byte -Path /path/to/file.svc' instead of the class directly, no?

**Comment by get-itips** [comment]
As the example is converting a plain text portion of the certsrv url _in the go_ to bytes, I think Get-Content won't be of use here.
I am ok with the change.

**Pull request merged**
