### PR TITLE
fixed example formatting

### PR DESCRIPTION
**Pull request by nedpyle**
powershell lines wrapped into output lines

### CODE REVIEW

**Review by JasonGerend — APPROVED** [review]

**Comment by JasonGerend** [comment]
#sign-off

**Comment by JasonGerend** [comment]
@tiburd This ideally would've been submitted through the private repo but let Ned and I know if we need to do anything more with it to get it merged. Thanks for your efforts with this repo! :) - Jason

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by tseward** [comment]
@nedpyle @JasonGerend PoSh output should be wrapped in \```output. See https://docs.microsoft.com/en-us/PowerShell/scripting/community/contributing/powershell-style-guide?view=powershell-7.1#executable-examples.

Examples should also not use aliases, for example in `Format-Table`, specify `-AutoSize` instead of `-Auto`. https://docs.microsoft.com/en-us/PowerShell/scripting/community/contributing/powershell-style-guide?view=powershell-7.1#formatting-command-syntax-elements

**Review by get-itips — COMMENTED** [review]
I am ok once @tseward suggestions are applied

**Comment by dariomws** [comment]
I approve after @tseward's suggestion.

**Review by JasonGerend — APPROVED** [review]

**Review by tseward — APPROVED** [review]

**Pull request merged**
