### PR TITLE
update get-aduser.md

### PR DESCRIPTION
**Pull request by MaratMussabekov**
issue #1047 ,
issue related to github formatting syntax:
"Note: PowerShell wildcards other than *, such as ?, are not supported by the *Filter* syntax."
the first * symbol has to be ignored, so I added \ to ignore markdown
source: [Basic writing and formatting syntax](https://help.github.com/en/articles/basic-writing-and-formatting-syntax#quoting-text)

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306 @get-itips

Peer review needed for this PR. Thanks.

**Comment by dariomws306** [comment]
I am good.

**Comment by get-itips** [comment]
Ok!

**Comment by e0i** [comment]
@AndreaBarr This PR can be merged. Thank you.

**Pull request merged**
