### PR TITLE
Update the -EnableHTTPRedirect section

### PR DESCRIPTION
**Pull request by piaudonn**
Using the parameter does not dynamically open the port 80. This change it to reflect this and provide an example in PowerShell.

### CODE REVIEW

**Comment by e0i** [comment]
@piaudonn Hello, Would you kindly change the target branch of the PR from `live` to `master` in order to proceed with the review? Thank you for your contributions.

**Comment by tseward** [comment]
As with #1525, I would move the example out of the switch description and return the switch description to the previous text.

**Comment by e0i** [comment]
@piaudonn Would you be able to follow-up with revision suggestions provided by @tseward ? Thanks.

**Comment by e0i** [comment]
Hello, @piaudonn As with PR #1525, We would like to proceed with merge upon your follow-up with reviewers' suggestions. Thank you again for your patience with the process and your contributions.

**Comment by e0i** [comment]
@piaudonn  Closing as there has been no follow-up with the reviewers' revision suggestions. Please re-open the PR to proceed with the review. Thank you for your patience with the process and your contributions.

**Pull request closed without merging**
