### PR TITLE
Fix error (spaces) in Powershell cmdlet

### PR DESCRIPTION
**Pull request by DarrylvanderPeijl**
Fix error (spaces) in Powershell cmdlet

### CODE REVIEW

**Comment by e0i** [comment]
Closing and re-opening to run checks.

**Comment by e0i** [comment]
@DarrylvanderPeijl Would you be able to re-target the PR branch to `master` in order to move forward with the review? Thank you for your contribution.

**Comment by DarrylvanderPeijl** [comment]
> @DarrylvanderPeijl Would you be able to re-target the PR branch to `master` in order to move forward with the review? Thank you for your contribution.

Done

**Comment by e0i** [comment]
@dariomws306 @tseward

Peer review needed for this PR. Thanks.

**Pull request merged**
