### PR TITLE
Update Set-SmbShare.md

### PR DESCRIPTION
**Pull request by msbemba**
Fixed syntax

### CODE REVIEW

**Comment by e0i** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by tseward** [comment]
Looks good.

**Comment by rjagiewich** [comment]
Hi @msbmba and @e0i - can you please close this PR and submit another that's merging to the Master branch instead of to Live? 

Thanks! -Rebecca

**Pull request closed without merging**
