### PR TITLE
Update Remove-ADPrincipalGroupMembership.md

### PR DESCRIPTION
**Pull request by sowjanya365**
Issue #1119 - Required value for the "-Confirm" parameter has been updated now.

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306 @get-itips

Peer review needed for this PR. Thanks.

**Comment by get-itips** [comment]
I do not think that the "Required" field needs change here.
The Ps cmdlet is not failing saying "you missed a parameter", it is only behaving that way because the "Confirm" parameter is true by default, so I think that is the field that needs to be True.

**Comment by dariomws306** [comment]
I am agree with @get-itips. -Confirm parameter is not required.

But... Should default value be false or true?

**Comment by get-itips** [comment]
Confirm:$true makes a cmdlet ask you for confirmation.
So it seems the default here is $true

**Comment by sowjanya365** [comment]
Hi @get-itips 

Thank you for your inputs. I've updated the "default value" field from false to true now. Kindly review the changes. Thanks.

**Comment by get-itips** [comment]
ok by me!

**Comment by dariomws306** [comment]
Ok!

**Comment by e0i** [comment]
@AndreaBarr This PR can be merged. Thanks.

**Pull request merged**
