### PR TITLE
Resolves #1131

### LINKED ISSUE #1131: AccountInactive Param
I think the information for the parameter means Windows 2003 or higher, the way it is currently worded makes it sound like it only works in a domain function level of 2003. 

"Note that this attribute is only used when the domain is in Windows Server 2003 Domain Functional Level, so this parameter will only work in that mode."
I would think this is what is meant
"Note that this attribute is only used when the domain is in Windows Server 2003 or higher Domain Functional Level, so this parameter will only work in those modes."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87483a05-ea3b-19c2-3d31-4701e03e68e2
* Version Independent ID: 917d2078-1e43-895a-e3cb-d6e64844196e
* Content: [Search-ADAccount (addsadministration)](https://docs.microsoft.com/en-us/powershell/module/addsadministration/search-adaccount?view=win10-ps#feedback)
* Content Source: [docset/windows/addsadministration/search-adaccount.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsadministration/search-adaccount.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

### PR DESCRIPTION
**Pull request by velkovb**
Adjuster domain functional level requirements for -AccountInactive to be 2003 or higher.
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1131

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by tseward** [comment]
Looks good.

**Comment by dariomws306** [comment]
Good!

**Comment by get-itips** [comment]
Ok!

**Comment by e0i** [comment]
@AndreaBarr This PR can now be merged.

**Comment by e0i** [comment]
@AndreaBarr The PR is ready to be merged. Thanks.

**Pull request merged**
