### PR TITLE
Resolves #2028

### LINKED ISSUE #2028: Examples use positional parameters
The examples use positional parameters and it is not clear enough. 
It is always a best practice to use named parameters!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f294bea5-f428-eba4-faea-ce17a386a012
* Version Independent ID: 47866b29-caf6-79d9-6817-d16488dbfc27
* Content: [Move-VM (hyper-v)](https://docs.microsoft.com/en-us/powershell/module/hyper-v/move-vm?view=win10-ps)
* Content Source: [docset/windows/hyper-v/Move-VM.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/hyper-v/Move-VM.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

### PR DESCRIPTION
**Pull request by velkovb**
Fix examples to use named parameters.
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2028

### CODE REVIEW

**Comment by e0i** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by e0i** [comment]
@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by tseward** [comment]
@velkovb Examples should have their description below the cmdlet, not in-line with "Example N".

**Comment by dariomws** [comment]
I think this repo has a "title" for each cmdlet in several cmdlet articles. For example:
https://docs.microsoft.com/powershell/module/adcsadministration/Add-CAAuthorityInformationAccess
https://docs.microsoft.com/powershell/module/adfs/add-adfsclient

**Comment by velkovb** [comment]
I added example description in-line as most of the articles have it here just to follow the same pattern and I think is it useful to have a few words there.

**Comment by get-itips** [comment]
> I think this repo has a "title" for each example in several cmdlet articles. For example:
> https://docs.microsoft.com/powershell/module/adcsadministration/Add-CAAuthorityInformationAccess
> https://docs.microsoft.com/powershell/module/adfs/add-adfsclient

good catch

**Pull request merged**
