### PR TITLE
Changed xml to newly vcmx format

### PR DESCRIPTION
**Pull request by get-itips**
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/315

and also taken from

https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/deploy/export-and-import-virtual-machines

### CODE REVIEW

**Comment by tseward** [comment]
Example #3 needs to have the comments/descriptive text moved out of the example (the idea being that the cmdlet text is something you could copy/paste).

Also, what about previous versions of Hyper-V where XML *is* correct?

**Comment by get-itips** [comment]
@tseward thanks for your review.
Actually, tbh, I would completely remove example 3, but it was present before my PR, I tried to fix it now.

About XML, as that was valid for previous versions, and this article is for 2016, which uses vcmx, that would be covered with different versions of the same article (Selecting the required version of your O.S. at the left panel)
Thank you again.

**Comment by tseward** [comment]
@get-itips I'd remove example 3, then :)

I'm not sure how the versioning is done in this repo (with SharePoint, we manually mark it as such) but if that will continue to work, sounds good.

**Comment by dariomws306** [comment]
I agree with both. Let's remove example 3.

**Comment by get-itips** [comment]
done

**Pull request merged**
