### PR TITLE
Resolved #1098

### LINKED ISSUE #1098: Example fails with error - Cannot process argument transformation on parameter 'Action'
To resolve:

$PS = PowerShell.exe

should be

$PS = New-ScheduledTaskAction -Execute "C:\windows\system32\WindowsPowerShell\v1.0\powershell.exe"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8e0ae68-fc55-853d-8b6c-77d326d78e13
* Version Independent ID: 4e093fe1-bdec-0e8f-2d35-ef44181f617d
* Content: [Register-ScheduledTask (scheduledtasks)](https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/register-scheduledtask?view=winserver2012r2-ps#feedback)
* Content Source: [docset/winserver2012r2-ps/scheduledtasks/Register-ScheduledTask.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012r2-ps/scheduledtasks/Register-ScheduledTask.md)
* Product: **powershell**
* Technology: **powershell**
* GitHub Login: @brianlic
* Microsoft Alias: **brianlic**

### PR DESCRIPTION
**Pull request by velkovb**
Fixed example to created scheduledtask action properly.
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1098

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by get-itips** [comment]
Looks ok

**Comment by tseward** [comment]
Looks good.

**Comment by dariomws306** [comment]
Ok!

**Comment by e0i** [comment]
@AndreaBarr This PR that has passed review is ready to be merged.

**Pull request merged**
