### PR TITLE
Resolves #974

### LINKED ISSUE #974: Errors on Remove-WebVirtualDirectory doc
`Site` and `Application` are listed as optional but are actually required from my experience using this command.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00544400-b443-d558-a315-e03392d528ff
* Version Independent ID: 35c13c66-4b89-a2e3-cc0a-08e744877492
* Content: [Remove-WebVirtualDirectory (webadminstration)](https://docs.microsoft.com/en-us/powershell/module/webadminstration/remove-webvirtualdirectory?view=winserver2012-ps#feedback)
* Content Source: [docset/winserver2012-ps/webadminstration/Remove-WebVirtualDirectory.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/webadminstration/Remove-WebVirtualDirectory.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

### PR DESCRIPTION
**Pull request by velkovb**
Fixed required parameters and command syntax.
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/974

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by get-itips** [comment]
Hello @velkovb 
It seems that -Name parameter is also required, so we need to remove the [ ] for it.
Thank you!

**Comment by dariomws306** [comment]
Agree with @get-itips!

**Comment by velkovb** [comment]
> 
> 
> Hello @velkovb
> It seems that -Name parameter is also required, so we need to remove the [ ] for it.
> Thank you!

@get-itips @dariomws306 
Thanks for the feedback but I have to disagree with you.

[-Name] <string> - means that the parameter value is required but the name can be ommitted because it is a positional parameter. 
Optional paramerters have the following syntax:
[-Parameter <type>]
Optional positional parameter:
[[-Parameter] <type>]

**Comment by dariomws306** [comment]
Hi @velkovb, it's true, you are right. I had not noticed that, my answer is based on my belief that everything was in brackets.

**Comment by get-itips** [comment]
Right!

**Comment by tseward** [comment]
I'm fine with this.

**Comment by e0i** [comment]
@AndreaBarr This PR can be merged. Thanks.

**Pull request merged**
