### PR TITLE
Update Set-ADUser.md

### PR DESCRIPTION
**Pull request by msbemba**
Added a note to clarify  between remove and clear attribute

### CODE REVIEW

**Comment by msbemba** [comment]
Issue #https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1777

**Comment by e0i** [comment]
cc @dariomws @get-itips @tseward

**Comment by tseward** [comment]
I think this is already stated in the cmdlet parameters for -Clear/-Remove.

**Comment by get-itips** [comment]
Agree w @tseward

**Comment by msbemba** [comment]
Thank you.

**Pull request closed without merging**
