### PR TITLE
Add example 9

### PR DESCRIPTION
**Pull request by bs-logisoft**
I was in search for a similar case and find it useful to add it to the docs.

### CODE REVIEW

**Comment by e0i** [comment]
@bs-logisoft Thank you for your contribution. Please target the branch of this PR to `master` to proceed with the review.

**Comment by e0i** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by bs-logisoft** [comment]
> @bs-logisoft Thank you for your contribution. Please target the branch of this PR to `master` to proceed with the review.

Thanks for the hint, I changed the target.

**Comment by e0i** [comment]
@bs-logisoft You contribution has been approved and the PR will get merged. It might take a few days for live content to get updated. Thank you for your contributions. Much appreciated.

**Pull request merged**
