### PR TITLE
Update import-certificate.md

### PR DESCRIPTION
**Pull request by msbemba**
Added an example for Importing from root to local machine

### CODE REVIEW

**Comment by e0i** [comment]
@nenonix @JohanFreelancer9 Minor copy editing is needed for this PR. Thanks.

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by tseward** [comment]
Can you use the `-FilePath` parameter rather than piping the file in? This makes it easier to read and understand for someone who isn't familiar with PoSh piping.

**Comment by get-itips** [comment]
Example 1 also uses piping, maybe is a good idea that this example uses FilePath yes

**Comment by tseward** [comment]
Good catch, I'd agree.

**Comment by dariomws306** [comment]
Agree!

**Comment by msbemba** [comment]
Thank you, I have used -filepath instead of piping the file in on both the examples.

**Comment by e0i** [comment]
@msbemba FYI Public contributions to the repository are on hold due to internal maintenance. The PR will be merged once maintenance is due.

**Comment by e0i** [comment]
@AndreaBarr The PR is ready to be merged upon completion of Dani's maintenance. Thanks.

**Pull request merged**
