### PR TITLE
Resolves #989

### LINKED ISSUE #989: InitiatorLatency Unit
Hi,

What unit is InitiatorLatency reported in, msec or usec? We're having trouble getting what this page: https://docs.microsoft.com/en-us/previous-versions/windows/desktop/clusstorageqosprov/msft-storageqosflow says to correspond to what we see.

Thanks,
Martin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbdbfded-de5b-552a-ec30-4a87833772a9
* Version Independent ID: 18dcc03c-386c-01c3-38af-0c4a5dbbf0ce
* Content: [Get-StorageQoSFlow (storageqos)](https://docs.microsoft.com/en-us/powershell/module/storageqos/get-storageqosflow?view=win10-ps#feedback)
* Content Source: [docset/windows/storageqos/get-storageqosflow.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/storageqos/get-storageqosflow.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

### PR DESCRIPTION
**Pull request by velkovb**
Included measurement units in example
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/989

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306 @get-itips

Peer review needed for this PR. Thanks.

**Comment by dariomws306** [comment]
Looks good.

**Comment by get-itips** [comment]
Ok too

**Comment by e0i** [comment]
@AndreaBarr This PR that has passed peer review can be merged. Thanks.

**Pull request merged**
