### PR TITLE
adding image for merge-vhd example

### PR DESCRIPTION
**Pull request by skalpin**
This description is confusing. An image would help clear up what the author is trying to say.

### CODE REVIEW

**Comment by e0i** [comment]
cc @JohanFreelancer9 @dariomws @get-itips @tseward

**Comment by get-itips** [comment]
I am having second thoughts on this one.
While I recognize the value of adding an image that improves explanation, AFAIK there are no images on cmdlet-specific documentation. There are images on other types of articles, like guides or procedures. Shouldn't we check if this is accepted @dariomws @tseward  ?

and also, can we check if the image art complies with the art team_ @e0i ?

Thanks

**Comment by tseward** [comment]
@get-itips good point -- and this wouldn't sync down to the PoSh help docs via `Get-Help`.

**Comment by e0i** [comment]
@skalpin Given that the documentation is also accessible via terminal clients, and that there is no other similar diagram picture in the repository  it has been concluded by the reviewers that it is best to leave the picture out of the PR. 

Feel free to reopen the PR without the picture for re-evaluation.

Thank you for taking the time to contribute to the Docs, and stay healthy.

**Comment by skalpin** [comment]
@e0i No worries, I figured an image wouldn't make it through without going through some kind of marketing check.

I'll maybe make another PR to make the wording more clear.

**Comment by e0i** [comment]
Closing via PR authors' comment.

**Pull request closed without merging**
