### PR TITLE
removed incorrect note

### PR DESCRIPTION
**Pull request by MaratMussabekov**
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1915

### CODE REVIEW

**Comment by MaratMussabekov** [comment]
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @e0i, for your information

Thank you

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by e0i** [comment]
Closing and re-opening to refresh validation checks.

**Comment by e0i** [comment]
@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by dariomws** [comment]
@MaratMussabekov What DNS name you used to test more than 25 entries? Thanks!

**Review by get-itips — COMMENTED** [review]
@MaratMussabekov did you test maybe with an internal DNS ?

**Comment by dariomws** [comment]
> @MaratMussabekov did you test maybe with an internal DNS ?

Oh, I think so. Good point!

**Comment by dariomws** [comment]
Test it with 219 records, and they return all of them. I'll approve. Could you also remove the note for 2012 and R2? Thanks!

**Review by dariomws — APPROVED** [review]

**Review by tseward — APPROVED** [review]

**Review by get-itips — APPROVED** [review]

**Comment by MaratMussabekov** [comment]
> Test it with 219 records, and they return all of them. I'll approve. Could you also remove the note for 2012 and R2? Thanks!

Hello, done for 2012 R2, version for 2012 doesn't have this note.
Thank you

**Pull request merged**
