### PR TITLE
Resolves 992

### PR DESCRIPTION
**Pull request by velkovb**
Replaces seconds with minutes.
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/992

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306 @get-itips 

Peer review needed for this PR. Thanks.

**Comment by get-itips** [comment]
Looks ok

**Comment by dariomws306** [comment]
Hi @velkovb, could you test it?

**Comment by get-itips** [comment]
more info by request of @dariomws306 

image

**Comment by dariomws306** [comment]
Nice!

So I am ok with this issue!

**Comment by velkovb** [comment]
@get-itips Thanks, that is exactly what I did. I guess it is a good idea to make screenshots when I test things.

**Comment by e0i** [comment]
@AndreaBarr The issue can now be merged. Thanks.

**Pull request merged**
