### PR TITLE
Update remove-appxpackage.md

### PR DESCRIPTION
**Pull request by msbemba**
Changed the doc with the correct information.

### CODE REVIEW

**Comment by e0i** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by tseward** [comment]
Looks like the article is missing switches. Can you please add them, or add them and put "{{Fill in description}}" if you're unsure as to their purpose?

```
Remove-AppxPackage [-Package] <String> [-AllUsers] [-Confirm] [-WhatIf] [<CommonParameters>]

    Remove-AppxPackage [-Package] <String> [-PreserveApplicationData] [-Confirm] [-WhatIf] [<CommonParameters>]

    Remove-AppxPackage [-Package] <String> -User <String> [-Confirm] [-WhatIf] [<CommonParameters>]
```

Also note that there is an `-AllUsers` switch so you may want to update your description/synopsis of the cmdlet to say something like "removes an app package from one or more users".

**Comment by get-itips** [comment]
ok with @tseward 
side note: This is a module that is changing on every win10 release, already submitted some PRs we can expect different behaviors

**Comment by dariomws306** [comment]
I am agree with @tseward.

**Comment by e0i** [comment]
> Looks like the article is missing switches. Can you please add them, or add them and put "{{Fill in description}}" if you're unsure as to their purpose?
> 
> ```
> Remove-AppxPackage [-Package] <String> [-AllUsers] [-Confirm] [-WhatIf] [<CommonParameters>]
> 
>     Remove-AppxPackage [-Package] <String> [-PreserveApplicationData] [-Confirm] [-WhatIf] [<CommonParameters>]
> 
>     Remove-AppxPackage [-Package] <String> -User <String> [-Confirm] [-WhatIf] [<CommonParameters>]
> ```
> 
> Also note that there is an `-AllUsers` switch so you may want to update your description/synopsis of the cmdlet to say something like "removes an app package from one or more users".

cc @msbemba

**Comment by msbemba** [comment]
> > Looks like the article is missing switches. Can you please add them, or add them and put "{{Fill in description}}" if you're unsure as to their purpose?
> > ```
> > Remove-AppxPackage [-Package] <String> [-AllUsers] [-Confirm] [-WhatIf] [<CommonParameters>]
> > 
> >     Remove-AppxPackage [-Package] <String> [-PreserveApplicationData] [-Confirm] [-WhatIf] [<CommonParameters>]
> > 
> >     Remove-AppxPackage [-Package] <String> -User <String> [-Confirm] [-WhatIf] [<CommonParameters>]
> > ```
> > 
> > 
> > Also note that there is an `-AllUsers` switch so you may want to update your description/synopsis of the cmdlet to say something like "removes an app package from one or more users".
> 
> cc @msbemba

The changes have been made as per @tseward suggestion.

**Comment by e0i** [comment]
@AndreaBarr The PR is ready to be merged post-migration. Thanks.

**Pull request merged**
