### PR TITLE
Update new-iscsitargetportal.md

### PR DESCRIPTION
**Pull request by sowjanya365**
Issue #569 - Parameter values are case sensitive. Document has been updated now.

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306 @tseward

Peer review needed for this PR. Thanks.

**Comment by dariomws306** [comment]
@sowjanya365, coud you test it? It sounds strange for me that it's case sensitive.

**Comment by tseward** [comment]
I agree, it is very unusual for things to be case-sensitive in Windows.

**Comment by sowjanya365** [comment]
Hello All,

Initially I too found it strange. But later I found out that it is true. There are supporting conversations also available on this topic. Kindly refer to these links. 

https://social.technet.microsoft.com/Forums/windowsserver/en-US/6bdc2ea6-2c91-44b6-aecd-618d8effc868/connectiscsitarget-authenticationtype-parameter-is-case-sensitive?forum=winserverpowershell

https://gungormez.wordpress.com/2018/09/25/connect-iscsi-targets-with-mututalchap-authentication-using-powershell/

https://srblogms.wordpress.com/tag/chap/

And there are lot more articles supporting this.

Kindly let me know your views on this. Really appreciate your time. Thank you so much.

**Comment by dariomws306** [comment]
It's true, there are a lot of articles confirming this. So I am agree with this PR.

**Comment by e0i** [comment]
Pending final OK via Trevor.

**Comment by tseward** [comment]
I'm OK with the PR.

**Comment by e0i** [comment]
@AndreaBarr The PR can be merged. Thanks.

**Pull request merged**
