### PR TITLE
Update Add-DnsServerVirtualizationInstance.md

### PR DESCRIPTION
**Pull request by doctordns**
The opening paragraph was poorly worded - this is an improvement.

I'd still like to have a reference here to more detail on how to make use of Virtualization instances.

### CODE REVIEW

**Comment by e0i** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by e0i** [comment]
@doctordns Can you please re-target the branch of this PR to `master`? The `live` branch is not the appropriate target for merge. Thank you for all of your contributions so far. Much appreciated.

**Comment by doctordns** [comment]
> @doctordns Can you please re-target the branch of this PR to `master`? The `live` branch is not the appropriate target for merge. Thank you for all of your contributions so far. Much appreciated.

I am not too sure how to do that easilyi.

I will close this PR and create a new one targeting master.

**Pull request closed without merging**
