### PR TITLE
Resolves #527

### LINKED ISSUE #527: No return value or exceptions list
The documentation should show the return value of all commands, even if it returns nothing. Similarly, if there are exceptions that the command can throw, that should be included in the documentation as well. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 396d4612-0240-2ddb-442c-43910d659d41
* Version Independent ID: 4700a39a-5694-1d2d-e166-354704cd19f3
* Content: [Install-ADDSDomainController (addsdeployment)](https://docs.microsoft.com/en-us/powershell/module/addsdeployment/install-addsdomaincontroller?view=win10-ps)
* Content Source: [docset/windows/addsdeployment/install-addsdomaincontroller.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/addsdeployment/install-addsdomaincontroller.md)
* Product: **w10**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

### PR DESCRIPTION
**Pull request by velkovb**
Added the output type of the Install-ADDSDomainController
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/527

### CODE REVIEW

**Comment by e0i** [comment]
@JohanFreelancer9 Minor style checks needed for this PR. Thanks.

**Comment by e0i** [comment]
@dariomws306 @tseward

Peer review needed for this PR. Thanks.

**Comment by dariomws306** [comment]
I'm ok with this.

**Comment by tseward** [comment]
I'm good with this.

**Comment by e0i** [comment]
@AndreaBarr The PR can be merged. Thank you.

**Pull request merged**
