### PR TITLE
Update remove-adgroupmember.md

### PR DESCRIPTION
**Pull request by ianjohnson2000**
Default value for Confirm parameter was incorrect. It should be set to True for its default value.

Members parameter talked about adding members rather than removing, updated to say 'remove form' rather than 'add to'.

### CODE REVIEW

**Comment by e0i** [comment]
@JohanFreelancer9 Minor copy editing and style checks are needed for this PR. Thanks.

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this community contributed PR. Thanks.

**Comment by tseward** [comment]
Looks good.

**Comment by get-itips** [comment]
Looks ok.

**Comment by dariomws306** [comment]
Good.

**Comment by e0i** [comment]
@AndreaBarr This PR can now be merged.

**Pull request merged**
