### PR TITLE
Fix: build warnings

### PR DESCRIPTION
**Pull request by velkovb**
@e0i @get-itips @dariomws 

Fix build warnings introduced with recent changes.

### CODE REVIEW

**Comment by e0i** [comment]
@traya1 @tiburd 

This PR addresses all the build warnings caused by the recent changes in the build engine.

Although there might be limitations to number of files introduced per PR, submitting the warning fixes in smaller parts would cause additional warnings for each small PR, probably making it more difficult to merge. Hence, All changes in one PR. 

Thanks.

cc @sdwheeler

**Comment by sdwheeler** [comment]
@velkovb These changes will work but I recommend moving the metadata values out of the markdown files and add them to the docfx.json file. When you do that, metadata values can be applied at a folder level. That way, when the values need to be changed, the change occurs in docfx.json rather than updating 5000+ files

**Comment by traya1** [comment]
Will the updates be moved to the docfx file?

**Comment by e0i** [comment]
We are uncertain whether the docfx configuration is going to resolve every metadata field, including the formatting with ms.date fields.

@traya @sdwheeler

**Comment by sdwheeler** [comment]
You should put move metadata that is not unique to the article into the docfx.json. For example, the following values are typically the same for all files in a folder for cmdlet reference.

- ms.technology: 
- author: 
- ms.author: 
- ms.devlang: 
- ms.topic: 

When you do this, you need to remove the values from the markdown files. Any value in the markdown file take precedence over the docfx.json.

Metdata like title, ms.date, and description are specific to the file and belong with the markdown.

**Comment by sdwheeler** [comment]
You can merge the PR as is. But I recommend a future PR to move common metadata to the docfx.json.

**Comment by e0i** [comment]
cc PubOps: @tiburd @traya1  _Sign Off_  via Sean’s final [comment](https://github.com/MicrosoftDocs/windows-powershell-docs/pull/2195#issuecomment-722511457) above.

**Pull request merged**
