### PR TITLE
Update Get-AppxDefaultVolume.md

### PR DESCRIPTION
**Pull request by msbemba**
Made change to the syntax to reflect just Get-AppxDefaultVolume

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1876

**Comment by get-itips** [comment]
I think that all cmdlet's documentation include the [<CommonParameters>] the difference with this one is that it has no other parameters than the common ones. The sintax is not implying that you have to run `Get-AppxDefaultVolume []` it is actually telling you that you can run `Get-AppxDefaultVolume -Verbose`

This would be a different story if found on the Example section.

**Comment by tseward** [comment]
Agreed, should not be merged.

**Comment by e0i** [comment]
@msbemba Do you have any recommendations on how to proceed with this PR and the related issue?

**Comment by msbemba** [comment]
@tseward  @dariomws  @get-itips Thank you for the feedback. I Close the Pull request.

**Pull request closed without merging**
