### PR TITLE
updated syntax

### PR DESCRIPTION
**Pull request by MaratMussabekov**
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2006

### CODE REVIEW

**Comment by e0i** [comment]
Closing and re-opening to refresh validation checks.

**Comment by e0i** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by e0i** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by dariomws** [comment]
@e0i I read your comment on the issue. 2019 information should be added or not? Could you please share your source of information about this? Thanks!

**Comment by e0i** [comment]
There is no repository yet for the 2019 content and only content related to the corresponding version of the documentation repository should be added.

**Review by dariomws — COMMENTED** [review]
Based on your comment @e0i I think this PR should be closed without merging it.

**Pull request closed without merging**
