### PR TITLE
Resolve #2047

### LINKED ISSUE #2047: Set-NetIPsecMainModeCryptoSet cmdlet -MaxMinutes parameter default value misprint
It must be 480 minutes

image

Actual for:

windows-powershell-docs/docset/winserver2012r2-ps/netsecurity/Set-NetIPsecMainModeCryptoSet.md

windows-powershell-docs/docset/winserver2012-ps/netsecurity/Set-NetIPsecMainModeCryptoSet.md

windows-powershell-docs/docset/windows/netsecurity/Set-NetIPsecMainModeCryptoSet.md

### PR DESCRIPTION
**Pull request by velkovb**
Fix typo
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2047

### CODE REVIEW

**Comment by e0i** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by e0i** [comment]
@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by traya1** [comment]
Hi @e0i,

Just to confirm: this PR is good to be reviewed by PubOps? Asking as the "Admin Review" and "Sign off" labels are both applied in this PR.

**Comment by e0i** [comment]
@traya1 Apologies, The _Admin review_ label must have been applied mistakenly. Thanks.

**Comment by garycentric** [comment]
In review.

**Pull request merged**
