### PR TITLE
Resolves #1044

### LINKED ISSUE #1044: New-ADServiceAccount wrong parameter information in description
In the description there is mention of a `-Standalone` parameter which is (no longer) present for the cmdlet.

> To create a standalone MSA which is linked to a specific computer, the -Standalone parameter is used.

I'm pretty positive that it has been replaced by the `-RestrictToSingleComputer` parameter so the description should reflect the change.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebd731d8-61d8-f6b3-0e8a-3decfe25a184
* Version Independent ID: 3338b8fe-1364-ecd7-eb5c-5ab25d054df7
* Content: [New-ADServiceAccount (activedirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/new-adserviceaccount?view=winserver2012-ps)
* Content Source: [docset/winserver2012-ps/activedirectory/New-ADServiceAccount.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/activedirectory/New-ADServiceAccount.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @brianlic-msft
* Microsoft Alias: **brianlic**

### PR DESCRIPTION
**Pull request by velkovb**
Changed -Standalone to -RestrictToSingleComputer in description
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1044

### CODE REVIEW

**Comment by e0i** [comment]
@nenonix Minor copy editing and style checks is needed for this PR. Thanks.

**Comment by e0i** [comment]
@dariomws306 @tseward

Peer review needed for this PR. Thanks.

**Comment by dariomws306** [comment]
I am good with this PR.

**Comment by tseward** [comment]
Also fine with the PR.

**Comment by e0i** [comment]
@AndreaBarr This PR that has passed review can now be merged. Thanks.

**Pull request merged**
