### PR TITLE
Bulk update | 167121 - Azure AD PowerShell rebrand

### PR DESCRIPTION
**Pull request by JustPies**
This PR contains updates to MS Graph PowerShell. See User story: [167121](https://dev.azure.com/msft-skilling/Content/_workitems/edit/167121)

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by get-itips — APPROVED** [review]

**Review by msbemba — APPROVED** [review]

**Comment by omondiatieno** [comment]
#reassign:@omondiatieno

**Comment by omondiatieno** [comment]
#assign:omondiatieno

**Comment by MeeraDi** [comment]
#sign-off

**Comment by Stacyrch140** [comment]
No Acrolinx report. Trying a close/reopen.

**Pull request merged**
