### PR TITLE
Clarify that DN syntax can be used to set permissions on AD domain root

### PR DESCRIPTION
**Pull request by jay98014**
# PR Summary

Adds comments to all LAPS permission-setting cmdlets to clarify that DN syntax may be used to target the AD domain root.

## PR Checklist

- [X] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [X] **Summary:** This PR's summary describes the scope and intent of the change.
- [X] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [X] **Style:** This PR adheres to the [style guide][style].

### CODE REVIEW

**Comment by jay98014** [comment]
#sign-off

**Comment by jay98014** [comment]
#sign-off

**Review by JohanFreelancer9 — APPROVED** [review]
Copy review.

**Comment by jay98014** [comment]
#sign-off

**Comment by jay98014** [comment]
@sdwheeler - can you please help me get this PR completed?   Apparently #sign-off is not the right magic incantation.

**Review by sdwheeler — APPROVED** [review]

**Pull request merged**
