### PR TITLE
Update remove-adorganizationalunit.md

### PR DESCRIPTION
**Pull request by msbemba**
Correct the values accepted for identity

### CODE REVIEW

**Comment by e0i** [comment]
@get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by tseward** [comment]
Can you please review the text of the `-Identity` parameter? It still references an AD Group, etc.

**Comment by get-itips** [comment]
ok with @tseward

**Comment by msbemba** [comment]
@tseward I have corrected the text of the identity parameter.

**Comment by e0i** [comment]
@AndreaBarr The PR is ready to be merged.

**Pull request merged**
