### PR TITLE
Update Install-ADDSDomainController.md

### PR DESCRIPTION
**Pull request by PaulaTomasG**
Modifying example in "-LogPath" as it could cause DCPromo to fail as directory is non-empty, DCPromo needs to empty it out and permissions may prevent this operation. Sysvol and Database paths both use their full path defaults as examples in this document, so proposing the same for the Log directory.

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by get-itips — APPROVED** [review]
Can you make the same edit to the other OS versions of the same cmdlet article? Thanks

**Review by dariomws — APPROVED** [review]
Agree with @get-itips.

**Comment by PaulaTomasG** [comment]
@get-itips I just submitted pull requests for the other OS versions of the article

**Comment by scanum** [comment]
@tiburd 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Pull request closed without merging**
