### PR TITLE
Resolves #1023

### LINKED ISSUE #1023: Typo: "48-bit" should read "48-digit"
"cmdlet creates a random 48-bit recovery password"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35517b3c-d00e-c08d-c274-8b606ad87bfa
* Version Independent ID: 3428c627-8703-752e-fbdf-52526f281f57
* Content: [Enable-BitLocker (bitlocker)](https://docs.microsoft.com/en-us/powershell/module/bitlocker/enable-bitlocker?view=win10-ps)
* Content Source: [docset/windows/bitlocker/enable-bitlocker.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/bitlocker/enable-bitlocker.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

### PR DESCRIPTION
**Pull request by velkovb**
Fix typo 48-bit to 48-digit
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1023

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306 @get-itips

Minor peer revision needed for this PR. Thanks.

**Comment by dariomws306** [comment]
Good!

**Comment by get-itips** [comment]
Ok!

**Comment by e0i** [comment]
@AndreaBarr This PR can be merged.

**Pull request merged**
