### PR TITLE
Fixed a typo

### PR DESCRIPTION
**Pull request by skycommand**
Fixed a typo. There is no "-FullFormat" switch, but there is a "-Full" switch.

### CODE REVIEW

**Comment by coreyp-at-msft** [comment]
Thanks, @skycommand !

**Comment by skycommand** [comment]
Great! I no longer have an open pull request from 2018. 😊

**Comment by Gatorz4eva** [comment]
@skycommand  Example#2 still reads "-FullFormat".

**Comment by skycommand** [comment]
@Gatorz4eva It has been corrected here on GitHub but Microsoft is not pushing it to docs.microsoft.com or updating PowerShell documents. I'm worried a little. I've seen behavior on Microsoft's part before when a product is getting the ax. Is PowerShell getting discontinued?

**Pull request merged**
