### PR TITLE
removed letter s

### PR DESCRIPTION
**Pull request by RAJU2529**
as per report issue #2511,  i checked the given commands on windows 11, and I found out  s should be removed from the command

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by get-itips — APPROVED** [review]

**Review by dariomws — APPROVED** [review]

**Review by tseward — APPROVED** [review]

**Comment by sdwheeler** [comment]
@RAJU2529 This needs to be fixed in all version.

**Comment by sdwheeler** [comment]
Please submit changes for the other versions in this PR.

**Comment by RAJU2529** [comment]
@sdwheeler . why merging is blocked, still showing here.

**Comment by sdwheeler** [comment]
@RAJU2529 You need to make the same change to all versions of this file.

- winserver2012-ps\international\Get-WinLanguageBarOption.md
- winserver2012r2-ps\international\Get-WinLanguageBarOption.md
- winserver2016-ps\international\Get-WinLanguageBarOption.md
- winserver2019-ps\international\Get-WinLanguageBarOption.md
- winserver2022-ps\international\Get-WinLanguageBarOption.md

**Comment by RAJU2529** [comment]
@sdwheeler. Thanks I wil try to do, after completion , I post  conform message here.

**Comment by RAJU2529** [comment]
@sdwheeler , removed letter s
**https://github.com/RAJU2529/windows-powershell-docs/blob/patch-13/docset/winserver2012-ps/international/Get-WinLanguageBarOption.md**

**Comment by RAJU2529** [comment]
@sdwheeler . removed letter s
**https://github.com/RAJU2529/windows-powershell-docs/blob/patch-13/docset/winserver2012r2-ps/international/Get-WinLanguageBarOption.md**

**Comment by RAJU2529** [comment]
@sdwheeler   removed letter s
**https://github.com/RAJU2529/windows-powershell-docs/blob/patch-13/docset/winserver2016-ps/international/Get-WinLanguageBarOption.md**

**Comment by RAJU2529** [comment]
@sdwheeler . removed letter s 
**https://github.com/RAJU2529/windows-powershell-docs/blob/patch-13/docset/winserver2022-ps/international/Get-WinLanguageBarOption.md**

**Comment by RAJU2529** [comment]
@sdwheeler . All editing works are completed, **WindowsServer2019-ps** is already in PR #2526.

**Pull request merged**
