### PR TITLE
fixed broken link cultural settings link

### PR DESCRIPTION
**Pull request by RAJU2529**
as per the user report #1795. i replaced the invalid to correct link

**https://docs.microsoft.com/previous-versions/office/developer/sharepoint-2010/ms425914(v=office.14)**

### CODE REVIEW

**Comment by e0i** [comment]
@RAJU2529 Please change the target branch of the PR from `live` to `master` to continue with the review. Thank you.

**Comment by RAJU2529** [comment]
@e0i . Changed to master. Thanks

**Comment by e0i** [comment]
@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

@JohanFreelancer9 Minor style checks needed for this PR. Thanks.

**Comment by get-itips** [comment]
> I'm not comfortable with this new link, as it's for SharePoint Foundation and a very old link... I think it must be a link to .net article...

agree with @dariomws we should at least try to get a more accurate link.

I tried to find one but couldn't, @kenwith can you kindly provide someone from the internationalization team that we can contact to help us? I appreciate

**Comment by kenwith** [comment]
Let's see if @sdwheeler might know who to contact for the International module. @sdwheeler the question is where should the following link point to?

image

From this article: https://docs.microsoft.com/en-us/powershell/module/international/set-winuserlanguagelist?view=win10-ps

**Comment by sdwheeler** [comment]
Looks like it would be aandrejs@microsoft.com according to the component owner tool.

https://microsoft.visualstudio.com/os/_apps/hub/wdgeswm.ownership.ownership-hub#query=international.psd1&accounts=Microsoft&projects=OS


Thanks.



Sean D. Wheeler

Sr. Content Developer | PowerShell

Microsoft C+L | Developer Relations

Office: 425-538-9279 | Mobile: 425-979-8626


________________________________

**Comment by sdwheeler** [comment]
It seems that this would be an appropriate replacement link.

https://support.microsoft.com/help/4496404/windows-10-manage-the-input-and-display-language#input_language<https://support.microsoft.com/en-us/help/4496404/windows-10-manage-the-input-and-display-language#input_language>


Thanks.



Sean D. Wheeler

Sr. Content Developer | PowerShell

Microsoft C+L | Developer Relations

Office: 425-538-9279 | Mobile: 425-979-8626


________________________________

**Comment by e0i** [comment]
@sdwheeler Thank you for providing the correct link. We are updating each such document that contains the link accordingly. 

> It seems that this would be an appropriate replacement link. https://support.microsoft.com/help/4496404/windows-10-manage-the-input-and-display-language#input_language<https://support.microsoft.com/en-us/help/4496404/windows-10-manage-the-input-and-display-language#input_language> Thanks. Sean D. Wheeler Sr. Content Developer | PowerShell Microsoft C+L | Developer Relations Office: 425-538-9279 | Mobile: 425-979-8626
> […](#)
> ________________________________ From: Sean Wheeler <Sean.Wheeler@microsoft.com> Sent: Thursday, March 26, 2020 4:19 PM To: MicrosoftDocs/windows-powershell-docs <windows-powershell-docs@noreply.github.com>; MicrosoftDocs/windows-powershell-docs <reply@reply.github.com> Cc: Mention <mention@noreply.github.com> Subject: Re: [MicrosoftDocs/windows-powershell-docs] fixed broken link cultural settings link (#1797) Looks like it would be aandrejs@microsoft.com according to the component owner tool. https://microsoft.visualstudio.com/os/_apps/hub/wdgeswm.ownership.ownership-hub#query=international.psd1&accounts=Microsoft&projects=OS Thanks. Sean D. Wheeler Sr. Content Developer | PowerShell Microsoft C+L | Developer Relations Office: 425-538-9279 | Mobile: 425-979-8626
> ________________________________ From: Ken Withee <notifications@github.com> Sent: Thursday, March 26, 2020 3:31 PM To: MicrosoftDocs/windows-powershell-docs <windows-powershell-docs@noreply.github.com> Cc: Sean Wheeler <Sean.Wheeler@microsoft.com>; Mention <mention@noreply.github.com> Subject: Re: [MicrosoftDocs/windows-powershell-docs] fixed broken link cultural settings link (#1797) Let's see if @sdwheeler<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsdwheeler&data=02%7C01%7Csean.wheeler%40microsoft.com%7C8bb4d6bba19746e6d27a08d7d1d573ee%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637208587011425645&sdata=rBZ4jjqRvi6vBddWGMwplOULWdWSBnQtSKwUSKibtHM%3D&reserved=0> might know who to contact for the International module. @sdwheeler<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsdwheeler&data=02%7C01%7Csean.wheeler%40microsoft.com%7C8bb4d6bba19746e6d27a08d7d1d573ee%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637208587011425645&sdata=rBZ4jjqRvi6vBddWGMwplOULWdWSBnQtSKwUSKibtHM%3D&reserved=0> the question is where should the following link point to? [image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F27743960%2F77702878-b616e800-6f76-11ea-9880-2f7e9bc576c8.png&data=02%7C01%7Csean.wheeler%40microsoft.com%7C8bb4d6bba19746e6d27a08d7d1d573ee%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637208587011435638&sdata=ki5CVYMLvcBDCXucySDJ5ZSUgEA7CLEXKCygCfR%2F8dg%3D&reserved=0> From this article: https://docs.microsoft.com/en-us/powershell/module/international/set-winuserlanguagelist?view=win10-ps<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fpowershell%2Fmodule%2Finternational%2Fset-winuserlanguagelist%3Fview%3Dwin10-ps&data=02%7C01%7Csean.wheeler%40microsoft.com%7C8bb4d6bba19746e6d27a08d7d1d573ee%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637208587011435638&sdata=k6qCArmxsa%2Bmw5Sv323Zsaij01PCkYXH1RAoqlMzEqg%3D&reserved=0> — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fwindows-powershell-docs%2Fpull%2F1797%23issuecomment-604721193&data=02%7C01%7Csean.wheeler%40microsoft.com%7C8bb4d6bba19746e6d27a08d7d1d573ee%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637208587011445632&sdata=vIsu7LfJQ3EbZMLMN6%2FbjBv8FUn%2FHXOJeiv%2ByvVac3s%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEUEGSKCQ56IWQB5R6DMLYTRJPJUXANCNFSM4K7PARGQ&data=02%7C01%7Csean.wheeler%40microsoft.com%7C8bb4d6bba19746e6d27a08d7d1d573ee%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637208587011445632&sdata=pecWtd1VEqH4%2BYSEjMShBpDi4DX1Z0O24SliETTaq9g%3D&reserved=0>.



> It seems that this would be an appropriate replacement link. https://support.microsoft.com/help/4496404/windows-10-manage-the-input-and-display-language#input_language<https://support.microsoft.com/en-us/help/4496404/windows-10-manage-the-input-and-display-language#input_language> Thanks. Sean D. Wheeler Sr. Content Developer | PowerShell Microsoft C+L | Developer Relations Office: 425-538-9279 | Mobile: 425-979-8626
> […](#)
> ________________________________ From: Sean Wheeler <Sean.Wheeler@microsoft.com> Sent: Thursday, March 26, 2020 4:19 PM To: MicrosoftDocs/windows-powershell-docs <windows-powershell-docs@noreply.github.com>; MicrosoftDocs/windows-powershell-docs <reply@reply.github.com> Cc: Mention <mention@noreply.github.com> Subject: Re: [MicrosoftDocs/windows-powershell-docs] fixed broken link cultural settings link (#1797) Looks like it would be aandrejs@microsoft.com according to the component owner tool. https://microsoft.visualstudio.com/os/_apps/hub/wdgeswm.ownership.ownership-hub#query=international.psd1&accounts=Microsoft&projects=OS Thanks. Sean D. Wheeler Sr. Content Developer | PowerShell Microsoft C+L | Developer Relations Office: 425-538-9279 | Mobile: 425-979-8626
> ________________________________ From: Ken Withee <notifications@github.com> Sent: Thursday, March 26, 2020 3:31 PM To: MicrosoftDocs/windows-powershell-docs <windows-powershell-docs@noreply.github.com> Cc: Sean Wheeler <Sean.Wheeler@microsoft.com>; Mention <mention@noreply.github.com> Subject: Re: [MicrosoftDocs/windows-powershell-docs] fixed broken link cultural settings link (#1797) Let's see if @sdwheeler<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsdwheeler&data=02%7C01%7Csean.wheeler%40microsoft.com%7C8bb4d6bba19746e6d27a08d7d1d573ee%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637208587011425645&sdata=rBZ4jjqRvi6vBddWGMwplOULWdWSBnQtSKwUSKibtHM%3D&reserved=0> might know who to contact for the International module. @sdwheeler<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsdwheeler&data=02%7C01%7Csean.wheeler%40microsoft.com%7C8bb4d6bba19746e6d27a08d7d1d573ee%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637208587011425645&sdata=rBZ4jjqRvi6vBddWGMwplOULWdWSBnQtSKwUSKibtHM%3D&reserved=0> the question is where should the following link point to? [image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F27743960%2F77702878-b616e800-6f76-11ea-9880-2f7e9bc576c8.png&data=02%7C01%7Csean.wheeler%40microsoft.com%7C8bb4d6bba19746e6d27a08d7d1d573ee%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637208587011435638&sdata=ki5CVYMLvcBDCXucySDJ5ZSUgEA7CLEXKCygCfR%2F8dg%3D&reserved=0> From this article: https://docs.microsoft.com/en-us/powershell/module/international/set-winuserlanguagelist?view=win10-ps<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fpowershell%2Fmodule%2Finternational%2Fset-winuserlanguagelist%3Fview%3Dwin10-ps&data=02%7C01%7Csean.wheeler%40microsoft.com%7C8bb4d6bba19746e6d27a08d7d1d573ee%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637208587011435638&sdata=k6qCArmxsa%2Bmw5Sv323Zsaij01PCkYXH1RAoqlMzEqg%3D&reserved=0> — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fwindows-powershell-docs%2Fpull%2F1797%23issuecomment-604721193&data=02%7C01%7Csean.wheeler%40microsoft.com%7C8bb4d6bba19746e6d27a08d7d1d573ee%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637208587011445632&sdata=vIsu7LfJQ3EbZMLMN6%2FbjBv8FUn%2FHXOJeiv%2ByvVac3s%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEUEGSKCQ56IWQB5R6DMLYTRJPJUXANCNFSM4K7PARGQ&data=02%7C01%7Csean.wheeler%40microsoft.com%7C8bb4d6bba19746e6d27a08d7d1d573ee%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637208587011445632&sdata=pecWtd1VEqH4%2BYSEjMShBpDi4DX1Z0O24SliETTaq9g%3D&reserved=0>.

@sdwheeler Thank you for providing the correct link!

**Comment by e0i** [comment]
@RAJU2529 The broken link targets are being updated en masse with the correct link Sean has provided. Thank you for taking the initiative.

**Pull request closed without merging**
