### PR TITLE
Resolves #1655

### LINKED ISSUE #1655: CommonTCPPort Clarification
Might be worthwhile to clarify that the CommonTCPPort parameter only takes one of those options.

Even better would be an update to that parameter to accept multiple or all of them but perhaps this isn't the spot for that type of suggestion.

### PR DESCRIPTION
**Pull request by velkovb**
Replace Get-PartitionSupportedSizes with Get-PartitionSupportedSize.
https://github.com/MicrosoftDocs/feedback/issues/1655

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by tseward** [comment]
Looks good.

**Comment by get-itips** [comment]
It's ok.

**Comment by dariomws306** [comment]
Ok!

**Comment by e0i** [comment]
@AndreaBarr The PR that addresses an external issue from the feedback repository is ready to be merged.

**Pull request merged**
