### PR TITLE
Clarify that Get-AppLockerPolicy only works for GP

### PR DESCRIPTION
**Pull request by isbrahm**
Policies that have been deployed through MDM cannot be retrieved using Get-AppLockerPolicy

### CODE REVIEW

**Comment by e0i** [comment]
@tseward

Minor review needed for this PR. Please let me know whether additional input form other reviewers is necessary. Thanks.

**Comment by e0i** [comment]
@tseward Any updates with the review? Thanks.

**Comment by e0i** [comment]
@isbrahm Would you be able to retarget the PR branch to `master`? Merging to `live` is not allowed via PubOps team. Thanks.

**Comment by isbrahm** [comment]
@e0i @traya1 
Could someone merge this? Thank you!

**Comment by traya1** [comment]
Hi @isbrahm,

I'll go ahead and review this PR now.

**Pull request merged**
