### PR TITLE
Get-Certificate examples fixes

### PR DESCRIPTION
**Pull request by Styxxy**
* removed extra white space (lines) which makes the code sample unnecessarily long
* removed redundant parenthesis in variable assignment
* moved location of cli after Set-Location

### CODE REVIEW

**Comment by skycommand** [comment]
Hi. If you wouldn't mind having a suggestion, I think the prompts on the page are entirely redundant. Why not get rid of all instances of "`PS C:\>`" and "`PS cert:\LocalMachine\My>`"? That'll make the page more readable.

**Comment by Styxxy** [comment]
> Hi. If you wouldn't mind having a suggestion, I think the prompts on the page are entirely redundant. Why not get rid of all instances of "`PS C:\>`" and "`PS cert:\LocalMachine\My>`"? That'll make the page more readable.
> 
> Edit: Same goes for #1649, #1648, #1647, #1646, #1645, #1644, #1643, and #1641.

True, but I stayed consistent with all the other snippets on all the other pages.
That's something bigger to handle than this PR.

**Comment by skycommand** [comment]
> True, but I stayed consistent with all the other snippets on all the other pages.

True, but as a principle, I'd stay away from adding the prompt when only one or two commands are shown without their output, or even when their output lacks significance. Still, it was just a suggestion. That's all.

> That's something bigger to handle than this PR.

Yes, but you don't need to psych yourself out over other such stuff being in existence. As long as you're doing volunteer work here, you can change the world one click at a time. And like I said before, no pressure! It was just a suggestion.

**Comment by e0i** [comment]
@Styxxy Thank you for your multiple contributions overall. Would you please update the target branch of your PRs to `master`? We would like to proceed with review.

**Comment by Styxxy** [comment]
> @Styxxy Thank you for your multiple contributions overall. Would you please update the target branch of your PRs to `master`? We would like to proceed with the review.

Interesting... I did my forking and PR's from GitHub web ui, and it defaulted to the "live" branch.
I switched the base branch (of the PR) to `master`.

**Comment by e0i** [comment]
@dariomws306 @get-itips

Peer review needed for this PR. Thanks.

**Pull request merged**
