### PR TITLE
Update New-NetQosPolicy.md

### PR DESCRIPTION
**Pull request by RAJU2529**
as per user report #2535, so i corrected data units, i conformed after checking on PowerShell commands.

### CODE REVIEW

**Comment by RAJU2529** [comment]
here is the proof
proof

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by get-itips — APPROVED** [review]
-

**Review by dariomws — APPROVED** [review]

**Comment by dariomws** [comment]
@RAJU2529 we'll appreciate it if you apply the same update on other Windows versions (eg. 2012, 2016, 2022...). Thanks!

**Comment by RAJU2529** [comment]
> @RAJU2529 we'll appreciate it if you apply the same update on other Windows versions (eg. 2012, 2016, 2022...). Thanks!

Thanks for replying sir  Could you tell me ,in which article I should applying it .

**Comment by dariomws** [comment]
https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2022-ps/netqos/New-NetQosPolicy.md
https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2016-ps/netqos/New-NetQosPolicy.md
https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012r2-ps/netqos/New-NetQosPolicy.md
https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/netqos/New-NetQosPolicy.md

**Comment by RAJU2529** [comment]
@dariomws , I completed all works, here are PR numbers
https://github.com/MicrosoftDocs/windows-powershell-docs/pull/2556
https://github.com/MicrosoftDocs/windows-powershell-docs/pull/2557
https://github.com/MicrosoftDocs/windows-powershell-docs/pull/2558
https://github.com/MicrosoftDocs/windows-powershell-docs/pull/2559

Thanks for providing direct links for editting.

**Review by tseward — APPROVED** [review]

**Pull request merged**
