### PR TITLE
PcsvDevice PowerShell reference update

### PR DESCRIPTION
**Pull request by TimShererWithAquent**
[1881241](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1881241)

Changes from PlatyPS only.

### CODE REVIEW

**Comment by TimShererWithAquent** [comment]
@tiburd This one doesn't require product team input. Ready for review.

**Review by get-itips — APPROVED** [review]

**Review by dariomws — APPROVED** [review]

**Review by JohanFreelancer9 — APPROVED** [review]
Copy review.

**Comment by TimShererWithAquent** [comment]
Forgot to mark this as no longer a draft when I requested review -

**Review by ghost — APPROVED** [review]

**Comment by TimShererWithAquent** [comment]
@tiburd Looks like this is ready for merge, thanks -

**Pull request merged**
