### PR TITLE
Update get-started.md

### PR DESCRIPTION
**Pull request by sowjanya365**
Issue #522 - Invalid module names are removed from the table now.

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306 @tseward

Peer review needed for this PR. Thanks.

**Comment by dariomws306** [comment]
I think there are some of them that we can find the article. For example, Windows Defender:
https://docs.microsoft.com/powershell/module/defender/

Hardware Certification:
https://docs.microsoft.com/powershell/module/hardwarecertification/

MsDtc:
https://docs.microsoft.com/powershell/module/msdtc/

Please check the others.

**Comment by sowjanya365** [comment]
Hi @dariomws306 

Thank you for the review. 

These modules were commented out on the Windows Server 2012 R2. And there is no content available under these modules. And because of the the comments symbols content is not properly aligned. 

Kindly suggest me on the next steps. Really appreciate your time on this. 

Thank you.

**Comment by dariomws306** [comment]
@sowjanya365, MsDTC and SMISConfig have a module for 2012 R2 and 8.1. I think Windows Defender should has one also, but it doesn't, maybe it should be fixed.

I think we should double check each of them.

**Comment by sowjanya365** [comment]
Hi @dariomws306 

Thank you for your assistance. 

But I couldn't find the Windows Defender module listed under 2012 R2 and 8.1. And MsDTS and SMISConfig modules are fixed with the respective links. Thanks.

**Comment by e0i** [comment]
@dariomws306

Any recommendations?

**Comment by dariomws306** [comment]
I think it would be good that we check if we can add Windows Defender module listed under 2012 R2 and 8.1, but it should be a different issue.

If @sowjanya365 has double checked that there aren't more missing 2012 R2/8.1 cmdlets list to add I am ok.

Thanks!

**Comment by sowjanya365** [comment]
Hi @dariomws306 

As per my research, defender module is not available on Windows server 2012 R2/8.1. Please refer to the following articles. 

https://social.technet.microsoft.com/Forums/lync/en-US/4851f4f8-7f74-4cc4-ae52-de8c9912f3c9/how-do-you-enable-powershell-defender-module-on-server-2012-r2?forum=winserversecurity

https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-8.1-and-8/dn344918(v=ws.11)#BKMK_WindowsDefender

Thanks.

**Comment by dariomws306** [comment]
@sowjanya365, it's true it's not available on 2012. But it's available on 8.1.

Maybe we can avoid to add it to the list.

**Comment by sowjanya365** [comment]
Thank you for the clarification and appreciate your time, @dariomws306 

Hi @e0i 

Kindly coordinate to get this PR merged. Thank you.

**Comment by dariomws306** [comment]
You're welcome @sowjanya365! Thank you for your patience!

**Comment by e0i** [comment]
The PR is OK by Trevor.

**Comment by e0i** [comment]
@AndreaBarr The PR can be merged. Thanks.

**Pull request merged**
