### PR TITLE
Fixed a typo

### PR DESCRIPTION
**Pull request by skycommand**
Fixed a typo. I had to decide whether the original author meant "\Windows\Temp" or "%Temp%". (No, they are  not equivalents.) Thankfully, DISM.Log came to rescue.

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by dariomws306** [comment]
Based on the last chat in Teams...

Looks ok.

**Comment by get-itips** [comment]
Ok.

**Comment by tseward** [comment]
Ok, too.

**Comment by e0i** [comment]
@AndreaBarr This PR can be merged. Thanks.

**Pull request merged**
