### PR TITLE
Correct name of parameter

### PR DESCRIPTION
**Pull request by bennettforkner**
There is no "GroupType" parameter, rather the one it is referencing is called "GroupCategory"

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]
Copy review.

**Comment by bennettforkner** [comment]
Ready for merge...if anyone wants to do so :) .

**Comment by get-itips** [comment]
@tiburd

**Comment by tiburd** [comment]
close > reopen

**Comment by tiburd** [comment]
@bennettforkner 
Hi,
Can you please resubmit this PR? Please don't delete the branch until after the PR is merged.
In your new PR, you can @ mention me to merge it.
Thank you!

**Pull request closed without merging**
