### PR TITLE
corrects all instances of *-StorageSettings to *-StorageSetting

### PR DESCRIPTION
**Pull request by rparsonsbb**
PowerShell uses `*-StorageSetting` but in the verbiage and examples `*-StorageSettings` appears to be used almost everywhere.

Modifies both the examples and the verbiage to match the actual PowerShell cmdlet

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for the community contributed PR. Thanks.

**Comment by e0i** [comment]
@nenonix Minor copy editing is needed for this PR. Thanks.

**Comment by tseward** [comment]
Looks good.

**Comment by get-itips** [comment]
Looks good.

**Comment by dariomws306** [comment]
Good!

**Comment by e0i** [comment]
@AndreaBarr This PR is now ready to be merged.

**Pull request merged**
