### PR TITLE
Repair damage

### PR DESCRIPTION
**Pull request by skycommand**
Moved HTML comments that disrupted proper rendering. Here is how the damaged page looked on docs.microsoft.com:

Screenshot_2019-12-17 Windows 8 and Windows Server 2012

I took this opportunity to patch two other damaged links too, on the same page set.

### CODE REVIEW

**Comment by e0i** [comment]
@JohanFreelancer9 Minor style checks needed for this PR. Thanks.

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by tseward** [comment]
For the technet.microsoft.com links, can you please swap those over to wherever the redirect is pointing to sans the language code portion of the URL?

**Comment by skycommand** [comment]
@tseward Done.

**Comment by skycommand** [comment]
Retrying... Sometimes, I really have a hard time understanding why Git acts the way it does.

**Comment by e0i** [comment]
@skycommand Please re-target the branch to `master` for merge. Thanks.

**Pull request merged**
