### PR TITLE
Added an example

### PR DESCRIPTION
**Pull request by get-itips**
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/730

### CODE REVIEW

**Comment by dariomws306** [comment]
@yogkumgit, I am ok with this.

**Comment by tseward** [comment]
I'm OK with this, as well.

**Comment by e0i** [comment]
@yogkumgit Copy editing might be needed for the long paragraph in the PR.

**Comment by dariomws306** [comment]
Looks good!

**Pull request merged**
