### PR TITLE
New-VirtualDisk: Corrects IsEnclosureAware's default value

### PR DESCRIPTION
**Pull request by exchange12rocks**
For `IsEnclosureAware` there actually **is** a default value.

### CODE REVIEW

**Comment by e0i** [comment]
@JohanFreelancer9

**Review by get-itips — COMMENTED** [review]
Actually, we tend to maintain the bulleted list of acceptable values in the description too. What do you think @tseward @dariomws ?

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by dariomws — COMMENTED** [review]
Agree with you @get-itips; I think we should leave them.

**Comment by tseward** [comment]
Agree with @get-itips as this is typically how we present parameter values.

**Comment by exchange12rocks** [comment]
Alright fellas, I reverted back the acceptable values changes.

**Review by tseward — APPROVED** [review]

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by dariomws — APPROVED** [review]

**Review by get-itips — APPROVED** [review]

**Pull request merged**
