### PR TITLE
replaced broken link to new link

### PR DESCRIPTION
**Pull request by RAJU2529**
as per the user report #1728         . i replaced to new link

**https://docs.microsoft.com/previous-versions/office/developer/sharepoint-2010/ms425914(v=office.14)**

### CODE REVIEW

**Comment by e0i** [comment]
@RAJU2529 Please change the target branch of the PR from `live` to `master` to continue with the review. Thank you.

**Comment by RAJU2529** [comment]
@e0i . changed to master.thanks

**Comment by e0i** [comment]
@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by e0i** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by tseward** [comment]
This was similar to another article which was for a Windows cmdlet pointing to legacy SharePoint docs. Is there not a more appropriate doc for culture info in Windows? Something like https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c?

**Comment by get-itips** [comment]
> This was similar to another article which was for a Windows cmdlet pointing to legacy SharePoint docs. Is there not a more appropriate doc for culture info in Windows? Something like https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c?

Yeap, this is directly related to the resolution of this conversation https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1797

**Comment by e0i** [comment]
@RAJU2529 The broken link targets are being updated en masse with the correct link Sean has provided. Thank you for taking the initiative.

**Pull request closed without merging**
