### PR TITLE
fixed the example

### PR DESCRIPTION
**Pull request by MaratMussabekov**
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2168

### CODE REVIEW

**Comment by MaratMussabekov** [comment]
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @e0i, for your information

Thank you

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by e0i** [comment]
@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

**Review by dariomws — CHANGES_REQUESTED** [review]
I think all the examples should be fixed and also the W2012 article. Thanks!

**Review by get-itips — COMMENTED** [review]
agree when @dariomws suggestions are applied.

**Comment by MaratMussabekov** [comment]
> I think all the examples should be fixed and also the W2012 article. Thanks!

Hello, please have a look now

**Review by dariomws — APPROVED** [review]

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by get-itips — APPROVED** [review]

**Pull request merged**
