### PR TITLE
Update New-WBBackupTarget.md

### PR DESCRIPTION
**Pull request by msbemba**
Added max path length for network path

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1997

**Comment by e0i** [comment]
@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by tseward** [comment]
I haven't personally used the cmdlet, but 110 characters seems like an odd limitation. As for the text itself that you've added, it shouldn't go on the same line as the credential statement since they don't have anything in common.

**Comment by get-itips** [comment]
agree @tseward @dariomws

**Comment by msbemba** [comment]
Closing this without merging PR

**Pull request closed without merging**
