### PR TITLE
"Name" is not a valid parameter for this command.

### PR DESCRIPTION
**Pull request by thwpike**
When attempting to run the command as specified the following error is displayed.  Parameter should be "Resource" rather than "Name":

```
PS C:\Windows\system32> Get-ClusterOwnerNode -Name "Cluster Virtual Disk (Volume03)"
Get-ClusterOwnerNode : A parameter cannot be found that matches parameter name 'Name'.
At line:1 char:22
+ Get-ClusterOwnerNode -Name "Cluster Virtual Disk (Volume03)"
+                      ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-ClusterOwnerNode], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.FailoverClusters.PowerShell.GetClusterOwnerNodeCommand
```

### CODE REVIEW

**Comment by thwpike** [comment]
Misread command, `-Name` is valid for `Get-ClusterResource`.

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by dariomws306** [comment]
@thwpike thank you.

So, this PR must be cancelled.

**Comment by tseward** [comment]
Which version of Windows Server?

```
PS C:\WINDOWS\system32> Get-ClusterResource -Name "Cloud Witness"

Name          State  OwnerGroup    ResourceType
----          -----  ----------    ------------
Cloud Witness Online Cluster Group Cloud Witness
```

**Comment by get-itips** [comment]
I believe the PR author already said that this change is not needed.

**Pull request closed without merging**
