### PR TITLE
Update get-dnsclient.md

### PR DESCRIPTION
**Pull request by msbemba**
Corrected Typo $dnsClient1

### CODE REVIEW

**Comment by e0i** [comment]
@get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by tseward** [comment]
Looks good.

**Comment by get-itips** [comment]
Ok

**Comment by e0i** [comment]
@msbemba FYI Public contributions are on hold for a short period of time due to internal maintenance. The PR will be merged immediately following the completion of maintenance.

**Comment by e0i** [comment]
@AndreaBarr The PR is ready to be merged upon completion of deployment maintenance. Thanks.

**Pull request merged**
