### PR TITLE
Update Set-MpPreference.md with correcting the example of -SignatureScheduleTime

### PR DESCRIPTION
**Pull request by yangsa666**
# PR Summary

According to the Syntax
 [-ScanScheduleTime <HH:MM:SS>]
The original example `PS C:\> Set-MpPreference -SignatureScheduleTime 120` should be a mistake. The correct example should be `PS C:\> Set-MpPreference -SignatureScheduleTime 02:00:00`

## PR Checklist
- [x] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [x] **Summary:** This PR's summary describes the scope and intent of the change.
- [x] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [x] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://learn.microsoft.com/powershell/scripting/community/contributing/overview
[style]: https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yangsa666** [comment]
Hi @JohanFreelancer9 , can you help merging this PR to the main branch? Thanks.

**Comment by JohanFreelancer9** [comment]
> Hi @JohanFreelancer9 , can you help merging this PR to the main branch? Thanks.

@scanum, can you help, please? Thanks.

**Comment by yangsa666** [comment]
Hi @scanum , could you please help mering this PR? There have been multiple customers reporting this mistake. It would be great if we can correct it ASAP. Thanks.

**Comment by scanum** [comment]
Hi @yangsa666 hope all is well. An apology for the late reply, I did not get the notification for this for some reason. Adding the required reviewers.

**Review by get-itips — APPROVED** [review]

**Review by dariomws — APPROVED** [review]
Approve but for some strange reason I cannot set it to 120 minutes:
image

**Comment by scanum** [comment]
@tiburd hope all is well. Could you please help with merging this PR? Thanks!

**Comment by yangsa666** [comment]
> Approve but for some strange reason I cannot set it to 120 minutes: image

@dariomws thanks for approving this PR. I also tested this in my lab and it works fine. So, you may be lucky to encounter this tricky issue, lol.
image

**Pull request merged**
