### PR TITLE
Resolves #1359

### LINKED ISSUE #1359: certificate type
The certificate type is not Token-Encryption, it should say Token-Decrypting instead

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce4c3905-94f4-3cad-48c2-bcd6ffbe1022
* Version Independent ID: 24c5edaf-ee43-b27b-d128-857c2debefba
* Content: [Set-AdfsCertificate (adfs)](https://docs.microsoft.com/en-us/powershell/module/adfs/set-adfscertificate?view=win10-ps#feedback)
* Content Source: [docset/windows/adfs/set-adfscertificate.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/adfs/set-adfscertificate.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

### PR DESCRIPTION
**Pull request by velkovb**
Fix CertificateType parameter description and ajdust links in articles in all versions
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1359

### CODE REVIEW

**Comment by e0i** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by tseward** [comment]
For the code examples, make sure the command is prefixed `PS C:\>`. I see there are some legacy uses of `C:\PS>`. Once that is resolved, I approve.

**Comment by velkovb** [comment]
@tseward would have never noticed that :)

**Pull request merged**
