### PR TITLE
Update #2056

### PR DESCRIPTION
**Pull request by velkovb**
Separate cmldet output
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2056

### CODE REVIEW

**Review by dariomws — CHANGES_REQUESTED** [review]
I think you missed example 3 in the 2012 R2 version.

**Review by dariomws — APPROVED** [review]

**Comment by velkovb** [comment]
@e0i Could you add reviewers here?

**Comment by e0i** [comment]
@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by e0i** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by get-itips — APPROVED** [review]

**Review by tseward — APPROVED** [review]

**Review by dariomws — APPROVED** [review]

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by jborsecnik** [comment]
Closing and re-opening to try to get staging views.

**Pull request merged**
