### PR TITLE
Fix casing of `windows` module and cmdlet filenames

### PR DESCRIPTION
**Pull request by joeyaiello**
I wrote this short script using [PSYaml](https://www.powershellgallery.com/packages/PSYaml/1.0.2) to fix the casing of each cmdlet and module name in the `windows` folder based on the `title` field of the YAML front matter. I had to make a couple small edits to the YAML front matter of some newer cmdlets in order to get it to work properly (those fixes are included in a smaller commit also included in this PR). 

This PR does not include fixes to the TOC nor to folders other than `windows` within the docset. Those may take me a little longer, and I wanted to get this out so as to set an example for any new cmdlets or modules. I can help with both of those at some point in the future.

### CODE REVIEW

**Comment by e0i** [comment]
Hello Joey,

The merges are on hold due to internal maintenance, which concerns fixing various schema errors and syncing public repository contents to live.

Consulted @DaniHalfin on whether to merge this PR prior or later that maintenance since he operates the maintenance. Also passed your note regarding the moniker.

Thank you for taking the initiative to improve PowerShell documentation writing experience.

**Comment by joeyaiello** [comment]
Yeah, I'm internal (I'm the PM owner of PowerShell itself) and on a thread with @DaniHalfin. Feel free to follow-up offline.

**Comment by DaniHalfin** [comment]
Saw the internal thread. Will merge as soon as possible.

**Comment by e0i** [comment]
Pending @DaniHalfin's input.

**Comment by e0i** [comment]
cc @DaniHalfin

**Comment by joeyaiello** [comment]
Should be rebased now

**Comment by e0i** [comment]
> Should be rebased now

cc @DaniHalfin

**Comment by joeyaiello** [comment]
Rebased to fix another conflict

**Comment by tfosmark** [comment]
@joeyaiello Please resolve the warnings in the build report and add the SignOff label when the build completes without warnings. Thanks!

**Comment by e0i** [comment]
@joeyaiello Would you be able to resolve build warnings on toc.md file? We would like to proceed with merge. Thank you for your time and attention.

**Comment by tfosmark** [comment]
Set the SignOff label per @joeyaiello.

**Comment by rjagiewich** [comment]
Hi @joeyaiello and @joeyaiello e0i- We understand that these [PR criteria](https://review.docs.microsoft.com/en-us/office-authoring-guide/pr-criteria?branch=master) are new, and we appreciate your patience with the process. 

**Following are blocking issues that need to be resolved before we can review:**

- Resolve the merge conflicts 

***

**Reference**

[Criteria used for pull request reviews](https://review.docs.microsoft.com/en-us/office-authoring-guide/pr-criteria?branch=master)

**Blocking**
- The PR is free of merge conflicts. If a merge conflict exists, then see [Resolve merge conflicts in Git and GitHub](https://review.docs.microsoft.com/en-us/help/contribute/resolve-merge-conflicts?branch=master).

thanks! -Rebecca

**Pull request merged**
