### PR TITLE
Removed invalid examples

### PR DESCRIPTION
**Pull request by get-itips**
Examples for ServicePrincipalNames corresponded to Set- not this article.

https://github.com/MicrosoftDocs/windows-powershell-docs/issues/353

### CODE REVIEW

**Comment by dariomws306** [comment]
Should we add that we can add multiple SPNs separating them with comma?

**Comment by dariomws306** [comment]
image

**Comment by get-itips** [comment]
Thanks for that, will improve the pr based on that

**Comment by tseward** [comment]
Looks good to me.

**Pull request merged**
