### PR TITLE
Update Set-SmbServerConfiguration.md

### PR DESCRIPTION
**Pull request by sowjanya365**
Issue #1289 : More examples with the different parameters have been incorporated into the document.

### CODE REVIEW

**Comment by sowjanya365** [comment]
Issue #1289 : More examples with the different parameters have been incorporated into the document.

**Comment by e0i** [comment]
@get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by e0i** [comment]
@get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by get-itips** [comment]
@sowjanya365 

I see this in the examples

`-ServerHidden $False` 

and the description for the parameter is _Indicates whether the server announces itself._

For turning off server announcements: shouldn't that parameter be $true ?

**Comment by sowjanya365** [comment]
> @sowjanya365
> 
> I see this in the examples
> 
> `-ServerHidden $False`
> 
> and the description for the parameter is _Indicates whether the server announces itself._
> 
> For turning off server announcements: shouldn't that parameter be $true ?

Hi @get-itips 

If we set the value to "True" then in that case, then the example title should be "Turn on server announcements". For more information on this command, kindly refer to this URL.

https://books.google.co.in/books?id=rgyLDwAAQBAJ&pg=PA146&lpg=PA146&dq=%22Set-SmbServerConfiguration%22+AND+%22AnnounceServer%22&source=bl&ots=YW2qrzmY0o&sig=ACfU3U1eIG9DVUFK2y-i_5TIb5nggstqoQ&hl=en&sa=X&ved=2ahUKEwi0lZT7x5nmAhUyguYKHWMIBg04ChDoATAAegQIChAB#v=onepage&q=%22Set-SmbServerConfiguration%22%20AND%20%22AnnounceServer%22&f=false

Let me know if my understanding is incorrect. Thank you! :)

**Comment by get-itips** [comment]
> > @sowjanya365
> > I see this in the examples
> > `-ServerHidden $False`
> > and the description for the parameter is _Indicates whether the server announces itself._
> > For turning off server announcements: shouldn't that parameter be $true ?
> 
> Hi @get-itips
> 
> If we set the value to "True" then in that case, then the example title should be "Turn on server announcements". For more information on this command, kindly refer to this URL.
> 
> https://books.google.co.in/books?id=rgyLDwAAQBAJ&pg=PA146&lpg=PA146&dq=%22Set-SmbServerConfiguration%22+AND+%22AnnounceServer%22&source=bl&ots=YW2qrzmY0o&sig=ACfU3U1eIG9DVUFK2y-i_5TIb5nggstqoQ&hl=en&sa=X&ved=2ahUKEwi0lZT7x5nmAhUyguYKHWMIBg04ChDoATAAegQIChAB#v=onepage&q=%22Set-SmbServerConfiguration%22%20AND%20%22AnnounceServer%22&f=false
> 
> Let me know if my understanding is incorrect. Thank you! :)

Ok, let's keep it that way then

**Comment by e0i** [comment]
@sowjanya365 Please re-target the branch for merge. Thanks.

**Comment by doctordns** [comment]
> > @sowjanya365
> > I see this in the examples
> > `-ServerHidden $False`
> > and the description for the parameter is _Indicates whether the server announces itself._
> > For turning off server announcements: shouldn't that parameter be $true ?
> 
> Hi @get-itips
> 
> If we set the value to "True" then in that case, then the example title should be "Turn on server announcements". For more information on this command, kindly refer to this URL.
> 
> https://books.google.co.in/books?id=rgyLDwAAQBAJ&pg=PA146&lpg=PA146&dq=%22Set-SmbServerConfiguration%22+AND+%22AnnounceServer%22&source=bl&ots=YW2qrzmY0o&sig=ACfU3U1eIG9DVUFK2y-i_5TIb5nggstqoQ&hl=en&sa=X&ved=2ahUKEwi0lZT7x5nmAhUyguYKHWMIBg04ChDoATAAegQIChAB#v=onepage&q=%22Set-SmbServerConfiguration%22%20AND%20%22AnnounceServer%22&f=false
> 
> Let me know if my understanding is incorrect. Thank you! :)

Since it was me that wrote that book, I think you have it right. ALWAYS happy to be corrected.

**Pull request merged**
