### PR TITLE
Added -AllUsers command

### PR DESCRIPTION
**Pull request by Malind19**
Could not find proper documentation specific to this command, but looking at the general feeling defined the parameter as it is common across many commands.

### CODE REVIEW

**Comment by kenwith** [comment]
@Malind19 - thanks for taking the time on making the content better! Please sign the CLA (click button above) so the checks can complete.

**Comment by Malind19** [comment]
> @Malind19 - thanks for taking the time on making the content better! Please sign the CLA (click button above) so the checks can complete.

Done.

**Comment by kenwith** [comment]
@Malind19 - thanks for this fix. I confirmed All-Users is there for this cmdlet. I am just taking this repo over and will work to get these audited using PlatyPS open source tool ( https://github.com/PowerShell/platyPS ). It is what I use for Office Server cmdlets and works really well. :) Thanks for this fix, much appreciated!

**Comment by e0i** [comment]
Fixes #343

**Comment by Borkason** [comment]
No, this does not fix #343.

**Comment by Borkason** [comment]
The update is lazy and doesn't even work. See #344.

No working example was given by @Malind19, therefor I do not consider this fixing anything here.

**Comment by Borkason** [comment]
The update adds the parameter to the documentation. The important this is missing, however. As explained in #344 the parameter does not work. Therefore, a proper fix would be to give a *working example* in the docs update.

@kenwith if you take over this repository, please make sure the PR is of good quality. This one is lazy and is not helpful to anyone who tries to use the switch and inevitably ends up with an error. Please reopen #343.

**Comment by kenwith** [comment]
@Borkason - I re-opened 343. 

The cmdlets are self-serve now that they are open source and the product teams that own the areas should be keeping these up to date. I am just stepping in to try to help things along. :) We are working to get through the backlog of issues and if you find any more areas like this that need attention please don't hesitate to open an Issue or better yet if you know the answer then submit a PR if you are willing to share your expertise with the community.

**Comment by Borkason** [comment]
@kenwith Another one of you closed a related ticket #344 unjustified. I tell you that this is frustrating to no end. I put quite a bit of time into creating this issue and commenting on it. I have to fight for tickets to being reopened as I am not permitted to do it myself.

If you guys rather close ticket than resolving them, then I don't see the point in investing my time into this.

**Pull request merged**
