### PR TITLE
Update get-started.md

### PR DESCRIPTION
**Pull request by msbemba**
Made changes to the Eventtracing management link

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1916

**Comment by e0i** [comment]
FYI @dariomws @get-itips @tseward @JohanFreelancer9

**Comment by e0i** [comment]
Good to go with [Trevor's](https://github.com/tseward) approval

**Comment by garycentric** [comment]
In review.

**Pull request merged**
