### PR TITLE
Update Set-VMProcessor.md

### PR DESCRIPTION
**Pull request by msbemba**
Fixed Typo

 Fixes https://github.com/MicrosoftDocs/windows-powershell-docs/issues/3241

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Comment by msbemba** [comment]
Fixed all applicable versions of the documents

**Comment by msbemba** [comment]
@scanum

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by dariomws — APPROVED** [review]

**Review by get-itips — APPROVED** [review]

**Comment by scanum** [comment]
@tiburd 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Pull request merged**
