### PR TITLE
Correct -PolicyStore path example

### PR DESCRIPTION
**Pull request by rdbahm**
The example shows forward slashes in the PolicyStore parameter, which does not work in the cmdlet. A backslash is required - this is also shown in the documentation for the parameter itself.

### CODE REVIEW

**Comment by e0i** [comment]
Re-opening to refresh automated checks.

**Comment by e0i** [comment]
@rdbahm Please change the branch target to `master` as the time permits. Thank you for your patience with the process.

**Comment by rdbahm** [comment]
Hm, I switched the base branch, but it did some weird stuff with the other changes that happened since I made the commit. Is there a best way to make sure it doesn't try to do anything weird?

**Comment by e0i** [comment]
@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

**Pull request merged**
