### PR TITLE
Update protocol description

### PR DESCRIPTION
**Pull request by MaratMussabekov**
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1819

### CODE REVIEW

**Comment by MaratMussabekov** [comment]
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @e0i, for your information

Thank you

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by e0i** [comment]
@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

**Review by get-itips — APPROVED** [review]

**Review by dariomws — APPROVED** [review]

**Comment by dariomws** [comment]
I think the same information must be added to W2012 and R2 versions.

**Review by tseward — APPROVED** [review]

**Comment by MaratMussabekov** [comment]
Hello, added to W2012 and R2 versions.
Thank you

**Review by tseward — APPROVED** [review]

**Review by JohanFreelancer9 — APPROVED** [review]

**Pull request merged**
