### PR TITLE
Update Set-ClusterStorageSpacesDirectDisk.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the example stating that omitting the parameter indicates that the specified physical disks can be claimed.

Fixes #https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2910

### CODE REVIEW

**Comment by msbemba** [comment]
@JohanFreelancer9 please copy review

**Comment by get-itips** [comment]
Articles for other Windows versions also seem to need an update

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by tseward — APPROVED** [review]

**Review by get-itips — APPROVED** [review]

**Comment by scanum** [comment]
@tiburd hope all is well. Could you please help us merge? Thanks!

**Comment by scanum** [comment]
@tiburd hope all is well. Could you please help us merge? Thanks!

**Pull request merged**
