### PR TITLE
Update set-netconnectionprofile.md

### PR DESCRIPTION
**Pull request by sukihanabi**
#984 
_*Action Taken :_
- Changes $Profile to $NetworkProfile variable.

_Run the following_:

1.) Run $Profile as a variable for the following command: works successfully
$Profile = Get-NetConnectionProfile -InterfaceAlias Ethernet
Set-NetConnectionProfile -InputObject $Profile (Just did not continue as I don't want to change my networkprofile)

See screenshot:
https://snipboard.io/CArlOe.jpg

2.) Run $NetworkProfile and $NWProfile as a variable for the following command: works successfully
$NetworkProfile = Get-NetConnectionProfile -InterfaceAlias Ethernet
$NWProfile = Get-NetConnectionProfile -InterfaceAlias Ethernet

_According to the below references the $PROFILE variable is an automatic variable stores the paths to the PowerShell profiles that are available in the current session._

_References:_ 

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-6#the-profile-variable

https://docs.microsoft.com/en-us/powershell/scripting/components/ise/how-to-use-profiles-in-windows-powershell-ise?view=powershell-6

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306 @tseward

Peer review needed for this PR. Thanks.

**Comment by tseward** [comment]
In Example 1, please remove the commends from within the code block and place them below in the description, rewording as appropriate.

**Comment by sukihanabi** [comment]
@tseward , changes made as suggested, feel free to let me know of any changes needed.

**Comment by tseward** [comment]
Here is what I was thinking and is the normal format for examples to follow:

```powershell
PS C:\> $NetworkProfile = Get-NetConnectionProfile -InterfaceAlias Ethernet1
PS C:\> $NetworkProfile.NetworkCategory = Public
PS C:\> Set-NetConnectionProfile -InputObject $NetworkProfile
```

This first command gets the connection profile for the network adapter named Ethernet1. The command stores the results in the $NetworkProfile variable. The second command assigns the value of Public to the NetworkCategory property of the connection profile stored in the $NetworkProfile variable. The third command sets the network category of the connection profile stored in the $NetworkProfile variable.

**Comment by sukihanabi** [comment]
@tseward . Thank you , changes made as suggested.

**Comment by e0i** [comment]
> Looks good after Trevor suggestion but I think we should apply the same update to 2012 and 2012R2 versions.

cc @sukihanabi

**Comment by e0i** [comment]
@sukihanabi Please revert the last two commits that deletes certain files necessary for deployment. Thanks.

**Comment by sukihanabi** [comment]
closing the PR

**Pull request closed without merging**
