### PR TITLE
delete MSOnlineBackup files since it's published in a seperate repo

### PR DESCRIPTION
**Pull request by Saisang**

### CODE REVIEW

**Comment by dcurwin** [comment]
@traya1 @tiburd @garycentric  - can you merge?

@Saisang  - do you need to sign off first?

**Comment by Saisang** [comment]
#sign-off

**Comment by e0i** [comment]
@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by tseward** [comment]
@Saisang what repo are these cmdlets residing in?

**Comment by Saisang** [comment]
> @Saisang what repo are these cmdlets residing in?

https://github.com/MicrosoftDocs/msonlinebackup-docs-powershell-pr here it is. and it's ready live.

**Comment by get-itips** [comment]
> > @Saisang what repo are these cmdlets residing in?
> 
> https://github.com/MicrosoftDocs/msonlinebackup-docs-powershell-pr here it is. and it's ready live.

I am getting a 404 on that link, can you kindly check ?

**Comment by dariomws** [comment]
Same here, getting 404.

**Comment by Saisang** [comment]
> > > @Saisang what repo are these cmdlets residing in?
> > 
> > 
> > https://github.com/MicrosoftDocs/msonlinebackup-docs-powershell-pr here it is. and it's ready live.
> 
> I am getting a 404 on that link, can you kindly check ?

I've granted access to you and @dariomws . I can add anybody else if needed.

**Comment by tseward** [comment]
@Saisang can you also add me? Thanks!

**Comment by Saisang** [comment]
> @Saisang can you also add me? Thanks!

sure, added. if you want higher perms just let me know.

**Comment by dcurwin** [comment]
Now that it's been approved, @traya1 @tiburd @garycentric  - can you merge?

Thanks.

**Comment by garycentric** [comment]
@Saisang, @dcurwin, @e0i 



**Following are blocking issues that need to be resolved before we can merge:**

Please add redirection in this PR for these deleted articles. Also, if these deleted articles appear in TOC files, those must also be modified in this PR.

***

**Reference**

[Quality criteria for pull request review](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-pull-request-quality-criteria?branch=master)

 - Blocking: When an article is deleted, the PR includes [a redirect for the article in the .openpublishing.redirection.json file](https://review.docs.microsoft.com/office-authoring-guide/retiring-redirecting-content?branch=master#the-condensed-max-version) for the repo and an update to the TOC to remove the entry for the article.

***

This PR removes 36 files, but it does not provide redirection or modify a TOC. When I search the repo for references to some of these file names, I find content that apparently links to these articles. For example:

<pre>c:\repos\windows-powershell-docs>findstr /s "New-OBFileSpec.md" *.md
docset\winserver2012-ps\msonlinebackup\Add-OBFileSpec.md:[New-OBFileSpec](./New-OBFileSpec.md)
docset\winserver2012-ps\msonlinebackup\Get-OBFileSpec.md:[New-OBFileSpec](./New-OBFileSpec.md)
docset\winserver2012-ps\msonlinebackup\MSOnlineBackup.md:### [New-OBFileSpec](./New-OBFileSpec.md)
docset\winserver2012-ps\msonlinebackup\New-OBSchedule.md:[New-OBFileSpec](./New-OBFileSpec.md)
docset\winserver2012-ps\msonlinebackup\Set-OBPolicy.md:[New-OBFileSpec](./New-OBFileSpec.md)</pre>

Thanks,

Gary

#hold-off

**Comment by Saisang** [comment]
Hi @garycentric Those content are all modules and they will be still under the same path /powershell/module/msonlinebackup/ 
So is that necessary?

**Comment by garycentric** [comment]
@Saisang 

I'm going to pass this PR to admin review, since the criteria that I have to work with say we need redirection.

**Comment by garycentric** [comment]
> 
> 
> Hi @garycentric Those content are all modules and they will be still under the same path /powershell/module/msonlinebackup/
> So is that necessary?

So the external URLs will be the same?

**Comment by Saisang** [comment]
> @Saisang
> 
> > Hi @garycentric Those content are all modules and they will be still under the same path /powershell/module/msonlinebackup/
> > So is that necessary?
> 
> So the external URLs will be the same?

https://review.docs.microsoft.com/en-us/powershell/module/msonlinebackup/get-oballrecoverypoints?view=winserver2012-ps
https://review.docs.microsoft.com/en-us/powershell/module/msonlinebackup/get-oballrecoverypoints?view=msonlinebackup-ps&branch=review

the only difference is the moniker value. So should I update the redirection file? The link could be auto corrected when I access a wrong moniker. https://review.docs.microsoft.com/en-us/powershell/module/msonlinebackup/get-oballrecoverypoints?view=winserver2012-ps&branch=review

**Comment by dstrome** [comment]
@Saisang - can you send me the new docset name? You should be good without the redirects but I just want to take a look at the config,

**Comment by Saisang** [comment]
> @Saisang - can you send me the new docset name? You should be good without the redirects but I just want to take a look at the config,

ops site: https://ops.microsoft.com/#/sites/Docs/docsets/msonlinebackup-docs-powershell-pr
github repo: https://github.com/MicrosoftDocs/msonlinebackup-docs-powershell-pr

**Comment by dstrome** [comment]
Thanks. I've done a test merge that deletes a single file (Add-OBFileSpec.md) and want to confirm that the system serves up the article properly from the new docset before merging this one. 

PubOps/owners - Please don't merge this PR until I give the OK. Thanks.

**Comment by dstrome** [comment]
Confirmed deleted test file from windows-powershell-docs is being served by new repo. Merging this PR.

**Pull request merged**
