### PR TITLE
Fix incorrect title inside cmdlet's yaml header

### PR DESCRIPTION
**Pull request by jeffreyxrh**
#2078

### CODE REVIEW

**Comment by qinezh** [comment]
@traya1 and @e0i please help take a look at this PR. The title's value in cmdlet's yaml header will be used in the new Docs build pipeline, so here in the PR we fixed some of the incorrect titles as content issue.

**Comment by e0i** [comment]
@traya1 This PR seems to relate to proposed changes to PowerShell Updatable Help pipeline, announced *May* by PowerShell and Docs team. Please review and do not hesitate to call for help where needed. Thank you.

**Comment by traya1** [comment]
Apologies for the delay - reviewing now. With respond with feedback in 15-20mins.

**Comment by traya1** [comment]
I am okay with the action of updating the title metadata attribute values though I cannot speak on the values proposed in the PR. Not sure who is the correct person to review and approve/deny the proposed values. Best I can do is reach out to the manager listed in the topics for guidance.

Let me know how to proceed.

**Comment by qinezh** [comment]
@sdwheeler can you please help review this PR? Thanks a lot~

**Comment by qinezh** [comment]
@sdwheeler I have to say, the requested changes are out of our scope, as we don't know the correct ms.assetid and online version. Can we fix the same kind of issues in just one PR and let the content owners to fix the issue you mentioned?

**Comment by qinezh** [comment]
We're trying to unblock the new SDP build pipeline by fixing the incorrect titles, instead of fixing the content issues of every documents. It's out of our scope.

**Comment by sdwheeler** [comment]
@qinezh The changes to `title` are good. You can merge this. But the content owners should fix the other metadata. It will be required to onboard to the CabGen CI.

**Comment by qinezh** [comment]
@sdwheeler Thanks, PR merged.

BTW, it sounds a good point to add metadata validation step inside the CabGen logic. Can you share the list of metadata that need to be validated and sent an email to Robert and me?

**Pull request merged**
