### PR TITLE
Resolves #1102

### LINKED ISSUE #1102: add-adfsrelyingpartytrust required parameters aren't consistent
In the example, the _-identifier_ parameter is not used. It's also not listed in 2 of the 3 syntax blocks. Seems this parameter is only required when _-MetadataUrl_ or _-MetadataFile_ are not used.
Still it is listed as a required parameter, which the other two parameters are not. 

In the second and third syntax block, only _-Name_ is set as required, but the command doesn't run when just Name is defined. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d3854ea-a248-2b59-197f-0edd6fc9800a
* Version Independent ID: 123cee00-5841-0abc-d76b-00f002969f37
* Content: [Add-AdfsRelyingPartyTrust (adfs)](https://docs.microsoft.com/en-us/powershell/module/adfs/add-adfsrelyingpartytrust?view=win10-ps)
* Content Source: [docset/windows/adfs/add-adfsrelyingpartytrust.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/adfs/add-adfsrelyingpartytrust.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

### PR DESCRIPTION
**Pull request by velkovb**
Change MetadataUrl to required for the MetadataUrl parameter set and
change MetadataFile to required for the MetadataFile parameter set.
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1102

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by get-itips** [comment]
Looks ok

**Comment by tseward** [comment]
Looks good.

**Comment by dariomws306** [comment]
Good!

**Comment by e0i** [comment]
@AndreaBarr This PR is now ready to be merged.

**Pull request merged**
