### PR TITLE
Update Set-MsmqQueueManager.md

### PR DESCRIPTION
**Pull request by sowjanya365**
Missing description for one of the parameter has been added now.

### CODE REVIEW

**Comment by e0i** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by e0i** [comment]
@dariomws306  @tseward

Peer review needed for this PR. Thanks.

**Comment by e0i** [comment]
> Description is missing on 2016 version. Could you add it please?

cc @sowjanya365

**Comment by sowjanya365** [comment]
> Description is missing on 2016 version. Could you add it please?

This is done now. Thank you! :)

**Comment by e0i** [comment]
@dariomws306 Any additional feedback on recent revisions? Thanks.

**Pull request merged**
