### PR TITLE
Resolves #2259

### LINKED ISSUE #2259: Get-ADServiceAccount Example 3 should be removed
Example 3 should be removed from the documentation; the cmdlet does not necessarily perform the way described in the example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe3affb4-2f61-05e7-c600-760c25e8d066
* Version Independent ID: b02f24ae-c006-8130-42d4-89fc746a75fc
* Content: [Get-ADServiceAccount (ActiveDirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/get-adserviceaccount?view=winserver2012-ps)
* Content Source: [docset/winserver2012-ps/activedirectory/Get-ADServiceAccount.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/activedirectory/Get-ADServiceAccount.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @kenwith
* Microsoft Alias: **kenwith**

### PR DESCRIPTION
**Pull request by velkovb**
Fix example 3 description
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2259

### CODE REVIEW

**Review by dariomws — APPROVED** [review]

**Review by get-itips — APPROVED** [review]

**Review by tseward — APPROVED** [review]

**Comment by tiburd** [comment]
Hi, Borislav/@velkovb, 

**Following are blocking issues that need to be resolved before we can merge:**
- This PR has build validation warnings.

***

**Reference**

[Criteria used for pull request reviews](https://review.docs.microsoft.com/en-us/office-authoring-guide/pr-criteria?branch=master)

**Blocking**
- The validation status must be "Passed."

***
The three updated articles have no other blocking issues. After the PR no longer has validation warnings, we can merge the PR.

It looks like removing the "ms.technology" line in the metadata fixes the warnings.

Thanks!

**Comment by velkovb** [comment]
@tiburd Those warnings were not caused by changes in this PR. I guess something else was merged/changed meanwhile. The build reports 2883 files with warning.  We have previously fixed such things:
https://github.com/MicrosoftDocs/windows-powershell-docs/pull/2195

Should we do the same now?

**Comment by e0i** [comment]
Re-opening to run checks.

**Comment by rjagiewich** [comment]
Hi @velkovb and @eoi - Because these warnings are already present in the master, we've decided to move forward and review only the files in this PR. So you don't need to do anything more with this PR. However, the issue needs to be fixed globally and to do that, you can open a new PR to remove either the ms.prod or ms.technology value from the affected files. 

@Kateyanne - can you drive this? 

Thanks, Rebecca

**Comment by garycentric** [comment]
Due to [Rebecca's note about fixing this PR after merger](https://github.com/MicrosoftDocs/windows-powershell-docs/pull/2280#issuecomment-764928214), and Tina saying that she had found no other blocking issues, I'll merge this PR now.

**Comment by Kateyanne** [comment]
Thanks Gary.

Kateyanne

**Pull request merged**
