### PR TITLE
Update Set-HpcTask.md

### PR DESCRIPTION
**Pull request by traya1**

### CODE REVIEW

**Review by get-itips — APPROVED** [review]

**Comment by tseward** [comment]
@traya1 shouldn't Export-, Get-, and Stop- all have the same format?

**Comment by traya1** [comment]
@[tseward](https://github.com/tseward)

Yeah, they should although I'm only using this PR to look into the link-out-of-scope warnings in the repo.

**Review by JohanFreelancer9 — APPROVED** [review]
No copy to review.

**Review by tseward — APPROVED** [review]

**Comment by tiburd** [comment]
@traya1 
Please help. Thanks!

**Comment by traya1** [comment]
This PR was for troubleshooting an issue that seems to be persisting to this day. I'll open a ticket.

**Pull request closed without merging**
