### PR TITLE
Task 36621825: Bug in ConfigCI New-CIPolicyRule article

### PR DESCRIPTION
**Pull request by jjhenry21**
removed "The -Level must be set to FileName for this option."

### CODE REVIEW

**Comment by jjhenry21** [comment]
hello @e0i can you review and sign off on this pull request?

**Comment by e0i** [comment]
> hello @e0i can you review and sign off on this pull request?

On it. Thanks.

**Review by get-itips — APPROVED** [review]

**Review by dariomws — APPROVED** [review]

**Comment by jgeurten** [comment]
@e0i can you please merge this PR? The feature team approves the changes

**Review by tseward — APPROVED** [review]

**Comment by e0i** [comment]
@tiburd Ready to merge. Thanks.

**Pull request merged**
