### PR TITLE
Update disable-tlsecccurve.md

### PR DESCRIPTION
**Pull request by sowjanya365**
Issue #1123 - Descriptions are updated now.

### CODE REVIEW

**Comment by e0i** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by get-itips** [comment]
Hello @sowjanya365  Please try to be more descriptive as in https://docs.microsoft.com/en-us/powershell/module/tls/get-tlsecccurve?view=win10-ps descriptions.

For example I propose changing all occurrences of 

> ECC Curve

 to _Elliptic Curve Cryptography (ECC)_ in synopsis and description.

**Comment by dariomws306** [comment]
Agree with @get-itips. Thanks!

**Comment by sowjanya365** [comment]
Hi @get-itips 

Thank you for the inputs. I've updated the document with the descriptions now. Kindly review. Thank you.

**Comment by get-itips** [comment]
Looks better!

**Comment by dariomws306** [comment]
Ok!

**Comment by e0i** [comment]
@AndreaBarr The PR that has passed copy and technical review can be merged. Thanks.

**Pull request merged**
