### PR TITLE
Resolves #1090

### LINKED ISSUE #1090: help mentions non-existent productkey parameter
The help for "Set-WindowsEdition" says this:

The ProductKey parameter is required for changing online Server images.

That parameter does not exist in this cmdlet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cf4133c-7c5c-dfcb-3e83-0d41e590d64e
* Version Independent ID: d7205783-6a2b-7178-009f-6929ab0deff8
* Content: [Set-WindowsEdition (dism)](https://docs.microsoft.com/en-us/powershell/module/dism/set-windowsedition?view=winserver2012r2-ps)
* Content Source: [docset/winserver2012r2-ps/dism/Set-WindowsEdition.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012r2-ps/dism/Set-WindowsEdition.md)
* Product: **powershell**
* Technology: **powershell**
* GitHub Login: @brianlic
* Microsoft Alias: **brianlic**

### PR DESCRIPTION
**Pull request by velkovb**
Removed ProductKey from cmdlet desctiption in all editions
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1090

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306 @get-itips

Peer review needed for this PR. Thanks.

**Comment by get-itips** [comment]
Ok!

**Comment by dariomws306** [comment]
Looks good.

**Comment by e0i** [comment]
@AndreaBarr This PR can be merged. Thanks.

**Pull request merged**
