### PR TITLE
Update new-netfirewallrule.md

### PR DESCRIPTION
**Pull request by sowjanya365**
Issue #1128 : 'Profile' parameter default value has been corrected.

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306 @get-itips

Peer review needed for this PR. Thanks.

**Comment by get-itips** [comment]
ok!

**Comment by dariomws306** [comment]
Looks good.

**Comment by e0i** [comment]
@AndreaBarr The PR is ready to be merged. Thanks.

**Pull request merged**
