### PR TITLE
Update get-provisioningpackage.md

### PR DESCRIPTION
**Pull request by sowjanya365**
Issue #1036 - Missing descriptions have been added.

### CODE REVIEW

**Comment by e0i** [comment]
@JohanFreelancer9 Minor ocpy editing is needed for this PR. Thanks.

**Comment by e0i** [comment]
@get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by get-itips** [comment]
I am ok with it.

**Comment by tseward** [comment]
I'm Ok with this.

**Comment by e0i** [comment]
@AndreaBarr This PR that has passed copy and technical review can now be merged. Thanks.

**Pull request merged**
