### PR TITLE
Resolves #1228

### LINKED ISSUE #1228: 3rd example description
Example 3 says it disables all users in an OU, I believe this should be Enables?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab398405-7c47-e48a-358c-51d8190b3a57
* Version Independent ID: 35d65237-8fa9-4937-04d4-976018286c3b
* Content: [Enable-ADAccount (activedirectory)](https://docs.microsoft.com/en-us/powershell/module/activedirectory/enable-adaccount?view=winserver2012-ps#feedback)
* Content Source: [docset/winserver2012-ps/activedirectory/Enable-ADAccount.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/activedirectory/Enable-ADAccount.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

### PR DESCRIPTION
**Pull request by velkovb**
Fix example 3 description from Disable to Enable. Made changes to all 3 versions of the article so they are identical.
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1228

### CODE REVIEW

**Comment by e0i** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by tseward** [comment]
Looks good.

**Comment by dariomws306** [comment]
Looks good.

**Comment by e0i** [comment]
The PR is ready to be merged.

**Pull request merged**
