### PR TITLE
AppLocker cmdlets only work with GP

### PR DESCRIPTION
**Pull request by isbrahm**
AppLocker cmdlets do not have any knowledge of the MDM stack. Customers using the AppLocker CSP have run into issues when trying to use the cmdlets, and there isn't a clear warning for them.

### CODE REVIEW

**Comment by isbrahm** [comment]
@denisebmsft could you please merge this? Thanks!

**Comment by e0i** [comment]
@dariomws @get-itips @tseward

Peer review needed for this PR.

cc @JohanFreelancer9 for copy editing.

Thank you.

**Review by dariomws — APPROVED** [review]
Agree with @get-itips.

**Comment by tseward** [comment]
Also agreed with @get-itips

**Review by tseward — APPROVED** [review]

**Review by get-itips — APPROVED** [review]

**Review by JohanFreelancer9 — APPROVED** [review]
Copy looks good.

**Comment by isbrahm** [comment]
@e0i are you able to merge these changes? I've removed the [!Note] tag. Thanks!

**Review by denisebmsft — APPROVED** [review]
Thanks @isbrahm

**Pull request merged**
