### PR TITLE
Update Set-NetEventSession.md

### PR DESCRIPTION
**Pull request by msbemba**
added description to As Job and Input object

### CODE REVIEW

**Comment by e0i** [comment]
@nenonix Copy editing is needed for this PR. Thanks.

**Comment by e0i** [comment]
@dariomws306 @tseward

Peer review needed for this PR. Thanks.

**Comment by e0i** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by rmca14** [comment]
In review.

**Comment by rmca14** [comment]
In review.

**Pull request merged**
