### PR TITLE
Resolves #2059

### LINKED ISSUE #2059: 0 is invalid for AccountExpirationDate in New-ADServiceAccount
As documented in [AccountExpirationDate of New-ADServiceAccount](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012r2-ps/addsadministration/New-ADServiceAccount.md#-accountexpirationdate)
_When you set this parameter to 0, the account never expires. This parameter sets the AccountExpirationDate property of an account object_
However, in practise, 0 is not a valid value for AccountExpirationDate, with DateTime type.

### PR DESCRIPTION
**Pull request by velkovb**
AccountExpirationDate description
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2059

### CODE REVIEW

**Comment by e0i** [comment]
@JohanFreelancer9 

@dariomws @get-itips @tseward

cc

**Comment by velkovb** [comment]
@dariomws I was thinking about that but was not quite sure as well and this will work only for the `New-*` cmdlets. For the `Set-*` it should be to use the `Clear-ADAccountExpiration` cmdlet.

**Comment by dariomws** [comment]
@velkovb yeah, same here, not sure.

What do you think @get-itips?

**Comment by tseward** [comment]
@dariomws If you leave the parameter out, doesn't it follow the default/group policy expiration?

**Pull request merged**
