### PR TITLE
Resolves #1054

### LINKED ISSUE #1054: "Example 3: Block inheritance for an OU in a domain" is wrong
I think the title for Example 3 should be "Example 3: Unblock inheritance for an OU in a domain".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0768068-c8ac-91de-3f3c-e31e01f4a225
* Version Independent ID: ebe4263f-4a02-c9f1-8c9d-2a445590d724
* Content: [Set-GPInheritance (grouppolicy)](https://docs.microsoft.com/en-us/powershell/module/grouppolicy/set-gpinheritance?view=win10-ps)
* Content Source: [docset/windows/grouppolicy/set-gpinheritance.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/grouppolicy/set-gpinheritance.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @coreyp-at-msft
* Microsoft Alias: **coreyp**

### PR DESCRIPTION
**Pull request by velkovb**
Fixed block to unblock - example 3.
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1054

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by get-itips** [comment]
Ok

**Comment by dariomws306** [comment]
I am ok with this!

**Comment by tseward** [comment]
Also fine with this.

**Comment by e0i** [comment]
@AndreaBarr This PR can be merged. Thanks.

**Pull request merged**
