### PR TITLE
Update add-netiphttpscertbinding.md

### PR DESCRIPTION
**Pull request by sukihanabi**
#1120 
Corrected the typo, change to CertificateStoreName

### CODE REVIEW

**Comment by e0i** [comment]
@sukihanabi Please make a reference to the the issue number that this PR addresses. Thanks.

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by get-itips** [comment]
Ok!

**Comment by tseward** [comment]
Looks good.

**Comment by dariomws306** [comment]
Ok!

**Comment by e0i** [comment]
@AndreaBarr This PR can now be merged. Thanks.

**Pull request merged**
