### PR TITLE
Resolves #2239

### LINKED ISSUE #2239: Get-DfsrBacklog: Help Example 1 is not valid.
Example 1 is not valid.
The Get-DfsrBacklog CmdLet requires you to specify a value for the DestinationComputerName parameter:
```powershell
((Get-Command Get-DfsrBacklog).Parameters.Values | Where-Object -Property Name -eq DestinationComputerName ).Attributes

TypeId
------
System.Management.Automation.ValidateNotNullOrEmptyAttribute
System.Management.Automation.AliasAttribute
System.Management.Automation.ParameterAttribute
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf7df028-2f0e-fa1b-81ac-17e277cc267c
* Version Independent ID: 731117d6-b101-dd87-1868-ed0bbe93c6be
* Content: [Get-DfsrBacklog (DFSR)](https://docs.microsoft.com/en-us/powershell/module/dfsr/get-dfsrbacklog?view=win10-ps)
* Content Source: [docset/windows/dfsr/Get-DfsrBacklog.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/dfsr/Get-DfsrBacklog.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

### PR DESCRIPTION
**Pull request by velkovb**
Fix example1
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2239

### CODE REVIEW

**Comment by e0i** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by get-itips — COMMENTED** [review]
What about the current description for the parameter? currently says _If you do not specify this parameter, the cmdlet uses the local computer._ should that be updated too?

**Comment by velkovb** [comment]
@get-itips The parameters is listed as required so there shouldn't be anything about not specifying it. Let me do a few tests first.

**Review by dariomws — COMMENTED** [review]
@velkovb, please let us know once you tested it. Thanks!

**Comment by velkovb** [comment]
@dariomws @get-itips The cmdlet always prompts for the value of the parameter so there is no case where it will pickup local computer. I have updated the parameter description and removed that sentence.

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by dariomws — APPROVED** [review]

**Review by get-itips — APPROVED** [review]

**Pull request merged**
