### PR TITLE
Update Set-SmbClientConfiguration.md

### PR DESCRIPTION
**Pull request by msbemba**
Corrected exmaples

### CODE REVIEW

**Comment by e0i** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by get-itips** [comment]
It looks like you are correcting the examples to be equal as the Windows 10 version of the article is that right?
It looks ok to me. Please try to be more descriptive on the reason of the pull request. Thank you for your work!

**Comment by rjagiewich** [comment]
Hi @msbemba and @e0i - please submit these changes to the Master branch instead of to the Live branch. Closing this PR.

Thanks! -Rebecca

**Pull request closed without merging**
