### PR TITLE
Resolves #2046

### LINKED ISSUE #2046: Spelling mistake on the "Module" name (screenshot)
The module name is misspelled under the page title, see screenshot.

image

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95401782-16b2-2fa5-7146-7051c0ac5163
* Version Independent ID: 1f7fd84b-0c0c-5954-8666-18c3dec674e4
* Content: [New-WebBinding (webadminstration)](https://docs.microsoft.com/en-us/powershell/module/webadminstration/new-webbinding?view=winserver2012-ps)
* Content Source: [docset/winserver2012-ps/webadminstration/New-WebBinding.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/winserver2012-ps/webadminstration/New-WebBinding.md)
* Product: **w10**
* Technology: **powershell**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

### PR DESCRIPTION
**Pull request by velkovb**
Typo in module name
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2046

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by e0i** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by velkovb** [comment]
I did not use `git mv` but it is still detected as a rename only. I do not see history in the files. Will redo it with `git mv`. Very good point, I did not think about the history.

**Comment by dariomws** [comment]
I'm sorry to disappoint you but we'll lose history anyway.

Seems that we only see file renames as the difference in this PR, so it could be ok. Also, I think you should take care of the TOC file and redirections.

**Comment by velkovb** [comment]
@dariomws Yeah, it seems like history cannot be preserved in Github while you can still see it using git log -follow. I am not sure I understand what you mean by  TOC file and redirections. I search the whole repo for the misspelled _webadminstration_ and found only 1 match that has been corrected.

**Comment by get-itips** [comment]
I checked the history of one of the files that you are changing the folder in your fork and it seems we would lose it

image

(Comparing this to other PRs, the whole history is included in the fork)

We would need to cross check with Kateyanne or the responsible person for this repo if is it acceptable to lose the file history in this case... was the last commit made with `git mv`?

**Comment by velkovb** [comment]
@get-itips Yes, there is no history and I was not able to find a way to preserve it without re-commiting it... It was done with `git mv`. Based on my understanding `git mv` helps to recognize files as renamed instead of added and deleted but does not keep history. If it has been done before it would be nice to check and do it here as well. Could you share an example?

I remember when files where renamed from lower case to title case history was lost.

**Comment by get-itips** [comment]
> @get-itips Yes, there is no history and I was not able to find a way to preserve it without re-commiting it... It was done with `git mv`. Based on my understanding `git mv` helps to recognize files as renamed instead of added and deleted but does not keep history. If it has been done before it would be nice to check and do it here as well. Could you share an example?
> 
> I remember when files where renamed from lower case to title case history was lost.

Yes, I think we will lose history anyway. Should we move forward ? @dariomws @tseward

**Comment by dariomws** [comment]
@velkovb TOC = Table of Content

For example:
https://github.com/velkovb/windows-powershell-docs/blob/fix-2046-module-name-typo/docset/docs-conceptual/windows/toc.yml

But I think there is no content to update here.

I think we are missing redirection here. If there are some articles in another repo with links to these articles they will fail with error 404. There is more detail in the document I shared, please let me know if you can open it.

**Comment by get-itips** [comment]
@dariomws You are right, redirection must be put in place, will take a look at the doc

**Comment by velkovb** [comment]
I have searched MicrosoftDocs organization for _webadminstration_ and could not find any other reference.

**Comment by dariomws** [comment]
@velkovb I have done a "rename" job some weeks ago and I have to (in summary):

1. Rename (using `git mv`)
2. Redirection
   a. Create redirections in the .openpublishing.redirection.json file
   b. Update links all-around Microsoft Docs (despite step a)

"Step a" will handle redirection for articles outside Docs, for example, techcommunity.microsoft.com, support.microsoft.com, and even non-Microsoft articles.

**Comment by velkovb** [comment]
@dariomws Thanks for the info. I really do not understand what needs to be done in the `.openpublishing.redirection.json`

```
        {
        "source_path": "docset/virtual-directory-module/webadministration/webadministration.md",
        "redirect_url": "/powershell/module/webadministration",
        "redirect_document_id": false
        },
```

Should I duplicate this with the old incorrect name?

**Comment by dariomws** [comment]
You can check an example here:
https://github.com/MicrosoftDocs/office-docs-powershell/blob/master/.openpublishing.redirection.json

On Exchange, I removed the folders. For example:

- Removed **organization** folder:
      "source_path": "exchange/virtual-folder/exchange/organization/Set-ExchangeAssistanceConfig.md",
      "redirect_url": "https://docs.microsoft.com/powershell/module/exchange/set-exchangeassistanceconfig",
- Removed **policy-and-compliance** folder:
      "source_path": "exchange/virtual-folder/exchange/policy-and-compliance/Get-InformationBarrierPolicy.md",
      "redirect_url": "https://docs.microsoft.com/powershell/module/exchange/get-informationbarrierpolicy",

**Comment by velkovb** [comment]
@dariomws 
Thank you for the example. I added redirection based on the other information available there. Hopefully, this is the correct syntax.

**Comment by e0i** [comment]
@traya1 Can you help us verify whether the redirection configuration is the correct syntax? Please see the discussion for details. Thank you.

**Comment by traya1** [comment]
Just to help me out, what's the priority on this? I'm working on some pri 0 items right now.

**Comment by e0i** [comment]
@traya1 You may take your time in reviewing this. Thanks.

**Comment by e0i** [comment]
@traya1 Please let us know whether there is any progress on this. Thank you.

**Comment by qinezh** [comment]
Hi guys, just like share with you that, this issue can be resolved without updating the file names after the PR "**Replace legacy build pipeline with PowerShell SDP build pipeline**" is ready and merged. Because the metadata **Module Name** in module's yaml header will be respected.

Here's the preview page: https://review.docs.microsoft.com/en-us/powershell/module/webadministration/add-webconfigurationlock?view=win10-ps&branch=sdp

**Comment by e0i** [comment]
Signing off as the PR #2078 has been merged.

**Comment by velkovb** [comment]
> Hi guys, just like share with you that, this issue can be resolved without updating the file names after the PR #2078 is merged. Because the metadata **Module Name** in module's yaml header will be respected.
> 
> Here's the preview page for that PR: https://review.docs.microsoft.com/en-us/powershell/module/webadministration/add-webconfigurationlock?view=win10-ps&branch=sdp

I can see that now the module name is displayed properly but the URL is still with the wrong name. Should we continue to actually fix the URL as well?

**Comment by velkovb** [comment]
@dariomws @get-itips What do you guys think?

**Comment by dariomws** [comment]
@velkovb I understand, based on the information that @qinezh provide us, that the decision must be taken by the product team.

**Comment by velkovb** [comment]
Is there someone we should include here than? @e0i

**Comment by e0i** [comment]
Closing as the original issue has been solved. Thank you for the contributions as always.

**Pull request closed without merging**
