### PR TITLE
Resolves #2295

### LINKED ISSUE #2295: Parameter CertificateType has error in parameters
> -CertificateType
> Specifies the type and purpose of the certificate. The acceptable values for this parameter are:
> 
> Service-Communications
> **Token-Encryption**
> Token-Signing

Replace with 

> -CertificateType
> Specifies the type and purpose of the certificate. The acceptable values for this parameter are:
> 
> Service-Communications
> **Token-Decrypting**
> Token-Signing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31c38ade-0ad3-4888-b5d7-e12197885a8d
* Version Independent ID: 72baefd3-a0b3-f174-69b6-122936a31a6f
* Content: [Add-AdfsCertificate (ADFS)](https://docs.microsoft.com/en-us/powershell/module/adfs/add-adfscertificate?view=win10-ps)
* Content Source: [docset/windows/adfs/Add-AdfsCertificate.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/adfs/Add-AdfsCertificate.md)
* Product: **w10**
* Technology: ****
* GitHub Login: @Kateyanne
* Microsoft Alias: **v-kaunu**

### PR DESCRIPTION
**Pull request by velkovb**
Fix parameter description
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2295

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by dariomws — CHANGES_REQUESTED** [review]
It seems that you removed the possible values by mistake. I think you only need to change "Token-Encryption" to "Token-Decrypting".

**Comment by velkovb** [comment]
No, it was intentional. There is no point listing possible values, when they are actually in the allowed values section below. When I tested `Service-Communications` was not there so allowed values is correct.

**Review by get-itips — APPROVED** [review]
We usually list the possible values also in the description, or at least there are tons of articles that do that.

**Comment by velkovb** [comment]
@get-itips Agreed but I think the allowed values is populated automatically from the code so putting them in the description may lead to inconsistencies as it was in this case.

**Review by dariomws — APPROVED** [review]

**Review by tseward — APPROVED** [review]

**Pull request merged**
