### PR TITLE
Update Get-ClusterGroup.md

### PR DESCRIPTION
**Pull request by msbemba**
Corrected the wrong parameter to Property

### CODE REVIEW

**Comment by msbemba** [comment]
Per issue #1850 https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1810

**Comment by e0i** [comment]
@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by Park-minkyu** [comment]
merging is blocked seems that no changed will be released..
am I right?

**Comment by e0i** [comment]
@Park-minkyu The PR has been queued for merge and the changes will be available with the periodical CI updates. Thank you.

**Pull request merged**
