### PR TITLE
Update Add-NetEventPacketCaptureProvider.md

### PR DESCRIPTION
**Pull request by msbemba**
Changed wordings on example 1

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306  @tseward

Peer review needed for this PR. Thanks.

**Comment by dariomws306** [comment]
Hi @msbemba, please apply the same update for 2012 R2 version.

Thanks!

**Comment by tseward** [comment]
Change looks good.

**Comment by e0i** [comment]
> Hi @msbemba, please apply the same update for 2012 R2 version.
> 
> Thanks!

cc

**Comment by msbemba** [comment]
> > Hi @msbemba, please apply the same update for 2012 R2 version.
> > Thanks!
> 
> cc

Both versions of the doc are updated now.

**Comment by rjagiewich** [comment]
Hi @e0i @msbemba, per the same comment we made in https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1343, we have been merging with master before pushing to live. Can we get this into master first?
cc @dstrome 

thanks! -Rebecca

**Comment by dstrome** [comment]
@e0i @msbemba - We only accept PRs to the master branch so this PR is being closed without merging. Please submit a new PR against the master branch. Thanks.

**Pull request closed without merging**
