### PR TITLE
Resolves #2161

### LINKED ISSUE #2161: NetworkCategory - explain the meaning / consequence of Public, Private, DomainAuthenticated
I assume that the values for NetworkCategory are related to this explanation on [tinker.com about Network profile public private ](https://tinkertry.com/how-to-change-windows-10-network-type-from-public-to-private)

 - public: Your pc is hidden from other devices on the network and can't be used for printer and file sharing
 - private: For a network you trust, such as at home or work. Your PC is discoverable and can be used for printer and file sharing if you set it up. 

The page contains this text

> -NetworkCategory
> Specifies an array of category types of a network. You cannot set the DomainAuthenticated type by using this cmdlet. The server automatically sets the value of DomainAuthenticated when the network is authenticated to a domain controller. The acceptable values for this parameter are:
> 
> Public
> Private
> DomainAuthenticated

Please add a link or additional explanation what a setting of Public, Private, DomainAuthenticated means.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70889239-a45b-5e6a-ccbd-c233bc81059d
* Version Independent ID: f42c8e2b-b5bd-cf1e-188b-7c4f7836a5b2
* Content: [Set-NetConnectionProfile (NetConnection)](https://docs.microsoft.com/en-us/powershell/module/netconnection/set-netconnectionprofile?view=win10-ps)
* Content Source: [docset/windows/netconnection/Set-NetConnectionProfile.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/netconnection/Set-NetConnectionProfile.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @AndreaBarr
* Microsoft Alias: **v-anbarr**

### PR DESCRIPTION
**Pull request by velkovb**
Update parameter description
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2161

### CODE REVIEW

**Comment by e0i** [comment]
Closing and re-opening to refresh checks.

**Comment by e0i** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by e0i** [comment]
@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

**Review by get-itips — APPROVED** [review]
Technically I am ok, there is a typo in "ofr" that I am pretty sure @JohanFreelancer9 will notice :)

**Comment by velkovb** [comment]
Nothing can get past @JohanFreelancer9 :) I fixed that one in advance. Thanks @get-itips

**Review by dariomws — APPROVED** [review]

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by tseward — APPROVED** [review]

**Comment by e0i** [comment]
@traya1 Can we sign this PR off to be merged despite the build warnings? The warnings in question are repository-wide and we are waiting for additional information to move on with the fixes from our side. Thanks.

**Comment by traya1** [comment]
Is it possible to resolve the warnings related to the modified topics in this PR?

**Pull request merged**
