### PR TITLE
Update -Level parameter list

### PR DESCRIPTION
**Pull request by brbrahm**
Adding parameters which were added in version 1903, mirroring new-cipolicy document

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by get-itips** [comment]
ok

**Comment by dariomws306** [comment]
Looks good.

**Comment by tseward** [comment]
Looks good.

**Comment by e0i** [comment]
@AndreaBarr This PR can be merged. Thanks.

**Comment by e0i** [comment]
@AndreaBarr Following up

**Comment by e0i** [comment]
@brbrahm FYI Public contributions are on hold for a short period of time due to internal maintenance. The PR will be merged immediately following the completion of maintenance. Thank you for your contributions.

**Pull request merged**
