### PR TITLE
Update Get-NetConnectionProfile.md

### PR DESCRIPTION
**Pull request by msbemba**
Added more detail to the description about compatibility.

### CODE REVIEW

**Comment by msbemba** [comment]
Issue# https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1758

**Comment by e0i** [comment]
cc @dariomws @get-itips @tseward

**Comment by get-itips** [comment]
If this is really necessary, which i am not sure, I think that we only need to state the 64 bits compatibility, and not an explanation.

**Comment by dariomws** [comment]
Agree with @get-itips. I cannot confirm or approve it. Could we confirm this information with the product team?

**Comment by get-itips** [comment]
> Agree with @get-itips. I cannot confirm or approve it. Could we confirm this information with the product team?

Yes, if the Product Team confirms this compatibility restriction, maybe add something like in this article. https://docs.microsoft.com/es-es/powershell/module/microsoft.powershell.localaccounts/get-localgroup?view=powershell-5.1#description

**Comment by msbemba** [comment]
Thank you @get-itips  @dariomws . I have added a note instead as Dario Mentioned.

**Comment by get-itips** [comment]
@msbemba I see you added the text exactly as my example. My example talks about a different module, so that won't work here.

Were you able to get confirmation from the Product Team of this incompatibility?

Thanks

**Comment by e0i** [comment]
@dariomws @get-itips @tseward

cc

**Comment by e0i** [comment]
@sdwheeler Can we get confirmation for this PR? Thank you in advance.

**Comment by sdwheeler** [comment]
@e0i I can't confirm. I have no knowledge. You need to contact the PM owner of the module.

**Pull request closed without merging**
