### PR TITLE
Update new-eapconfiguration.md

### PR DESCRIPTION
**Pull request by sukihanabi**
#729 
I cannot verify if the "WinLogonCredential with MSCAPv2, can use NON Window credential username + password" , I cannot find any article with regard to this.

Article: https://docs.microsoft.com/en-us/windows/security/identity-protection/vpn/vpn-authentication

Although according to the above article: "EAP-Microsoft Challenge Handshake Authentication Protocol version 2 (EAP-MSCHAPv2) supports User name and password authentication", Could you please help me to verify if this mean it accept a Non-windows credentials username + password.

Additionally in this article, it said that "UWP VPN plug-in can use the authentication method "User name and password" and supports custom credential type.
Can we recommend this to the user instead?

Technet Forum: https://social.technet.microsoft.com/Forums/en-US/4d677476-0440-4276-ab07-c142f07a7bc8/really-confused-about-peap-and-mschap-v2-why-sometimes-they-are-separated-and-sometimes-one-is-the?forum=winserverNIS
It said in this forum the " Passwords from the clients are send using hashes to the authentication server. To protect these password hashes being send over the network, you can use PEAP which act as a TLS/SSL tunnel to protect the authentication traffic." - so does this mean it is just accepts a Windows login credential?

=====================================================

References:

https://github.com/MicrosoftDocs/windows-powershell-docs/blob/master/docset/windows/vpnclient/add-vpnconnection.md

https://docs.microsoft.com/en-us/windows/security/identity-protection/vpn/vpn-authentication

https://docs.microsoft.com/windows/configuration/wcd/wcd-connectivityprofiles#vpn-1

AuthenticationUserMethod When you set NativeProtocolType to IKEv2, choose between EAP and MSChapv2. 
https://docs.microsoft.com/en-us/windows/configuration/wcd/wcd-connectivityprofiles

https://docs.microsoft.com/en-us/windows/client-management/mdm/eap-configuration

https://support.microsoft.com/en-us/help/2744850/implementing-peap-ms-chap-v2-authentication-for-microsoft-pptp-vpns

https://social.technet.microsoft.com/Forums/en-US/4d677476-0440-4276-ab07-c142f07a7bc8/really-confused-about-peap-and-mschap-v2-why-sometimes-they-are-separated-and-sometimes-one-is-the?forum=winserverNIS

### CODE REVIEW

**Comment by e0i** [comment]
@nenonix Minor copy editing is needed for this PR. Thanks.

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Would you able to assist Jerry in moving forward with this PR? 

Peer review is also needed for this PR. Thanks.

**Comment by tseward** [comment]
> about VPN authentication method.

Should be method**s**.

I'm otherwise OK with the change.

**Comment by dariomws306** [comment]
Agree with Trevor.

**Comment by get-itips** [comment]
I am ok with @tseward and @dariomws306

**Comment by e0i** [comment]
@AndreaBarr This PR can be merged. Thanks.

**Pull request merged**
