### PR TITLE
remove cmdlet docs until it goes live

### PR DESCRIPTION
**Pull request by erik0686**
This PR removes the documentation of the Copy-UserInternationalSettingsToSystem. 

The reason for this is that the cmdlet is not yet live, therefore we had documentation of a feature that is not yet available and this was confusing people who wanted to use the cmdlet. 

This documentation will be added back once the feature is available for public use. 
I will add an issue to track this.

### CODE REVIEW

**Comment by jefgen** [comment]
I commented on the original PR here https://github.com/MicrosoftDocs/windows-powershell-docs/pull/2177#issuecomment-771164878 -- but also adding a comment here as well. :)

This documentation page was for a new cmdlet that will ship in a future and/or upcoming version of Windows.

Is there some way to maybe flag or denote in the documentation that this cmdlet is only present on upcoming versions of Windows? (Perhaps, something like version `xxx` or greater?).
Or alternatively, could this documentation be noted as "preliminary" (ie: for an upcoming new cmdlet) perhaps?

Thanks!

**Comment by garycentric** [comment]
Hi @erik0686

**Following are blocking issues that need to be resolved before we can merge:**

docset/windows/international/_Copy-UserInternationalSettingsToSystem.md_
- You need to add a redirect for this deleted file. 
- It appears that this file is not currently listed in a TOC file in this repo, so you don't need to remove it from a TOC file.

***

**Reference**

[Criteria used for pull request reviews](https://review.docs.microsoft.com/en-us/office-authoring-guide/pr-criteria?branch=master)

**Blocking**
 
 - Blocking: When an article is deleted, the PR includes a [redirect for the article in the .openpublishing.redirection.json](https://review.docs.microsoft.com/office-authoring-guide/retiring-redirecting-content?branch=master#the-condensed-max-version) file for the repo and an update to the TOC to remove the entry for the article.

 - Blocking: Names for new files and folders follow these guidelines: <ul><li>Use only lowercase, dashes, and numbers. Spaces and underscores are not allowed.</li><li>Use no more than 80 characters, which is a publishing system limit.</li><li>Use action verbs that are specific, such as _develop_, _buy_, _build_, and _troubleshoot_. Avoid "-ing" words.</li><li>Don't use unnecessary small words, such as _a_, _or_, _and_, _the_, and _in_.</li></ul> 


***

New files in the repo should follow the naming guidelines described in the preceding criteria about names for new files. The name isn't a blocking issue for this PR, since you're not adding the file, but note this for the future.

I also found that _Copy-UserInternationalSettingsToSystem.md_ is linked in docset/windows/international/_International.md_. Adding a redirect will prevent this link from being 404, as well as redirect any external links to the article.

When you've addressed the blocking issue, please remove _Back to submitter_ and reapply _Sign off_ to put this PR back in the queue for review.

Thanks,

Gary

**Comment by erik0686** [comment]
@garycentric
@traya1 Mentioned offline that this topic might not need a redirect. This topic will be returned at some later date when the feature is ready and live :)

**Comment by garycentric** [comment]
> @garycentric
> @traya1 Mentioned offline that this topic might not need a redirect. This topic will be returned at some later date when the feature is ready and live :)

There are search results from Google for this cmdlet, including a link to the page that you want to delete. These kinds of links are part of the rationale for requiring a redirect for a deleted file. Also, simply deleting this file will create a broken link in docset/windows/international/_International.md_, which I've already noted.

**Comment by erik0686** [comment]
@garycentric should I remove the link from _international.md_ ?? Or is adding the redirect link enough for that?
Also, I believe I don't have enough permissions to add or remove tags. I can't do as you asked and remove the "back to submitter" tag :/

**Comment by garycentric** [comment]
Erik said in e-mail that this was ready for follow-up review, but he doesn't have permission to apply the _Sign off_ label.

**Pull request merged**
