### PR TITLE
Update New-RDVirtualDesktopCollection.md

### PR DESCRIPTION
**Pull request by sowjanya365**
Issue #874 - VirtualDesktopAllocation parameter is explained.

### CODE REVIEW

**Comment by e0i** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by get-itips** [comment]
Looks ok

**Comment by dariomws306** [comment]
Ok!

**Comment by tseward** [comment]
Looks good.

**Comment by e0i** [comment]
@AndreaBarr The PR that has passed technical review can be merged. Thanks.

**Pull request merged**
