### PR TITLE
Update New-AdfsAzureMfaTenantCertificate.md

### PR DESCRIPTION
**Pull request by msbemba**
Updated the example as the output usually is not readable and is much bigger than the original file.

This way it makes it easy

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2736

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by get-itips — CHANGES_REQUESTED** [review]
I think the output is better read if you save the conversion to $cert and then pipe to a Format-List, what do you think?
`$cert | Format-List *`

**Review by dariomws — APPROVED** [review]

**Comment by msbemba** [comment]
> I think the output is better read if you save the conversion to $cert and then pipe to a Format-List, what do you think? `$cert | Format-List *`

Hello Andres,

LIke the below one?

$CertInBase64 = New-AdfsAzureMfaTenantCertificate -TenantID <your tenant ID> 
$cert = [Security.Cryptography.X509Certificates.X509Certificate2]([System.Convert]::FromBase64String($CertInBase64))
$cert | Format-List *

Thanks
Sri

**Comment by get-itips** [comment]
@msbemba Yes

**Comment by msbemba** [comment]
@get-itips Thank you. I have made those suggested changes.

**Pull request merged**
