### PR TITLE
[BrokenLinksH2]

### PR DESCRIPTION
**Pull request by mohitp930**

### CODE REVIEW

**Comment by mohitp930** [comment]
Global effort to fix broken links

@sdwheeler

[Note] Per https://docs.microsoft.com/en-us/lifecycle/products/microsoft-enterprise-desktop-virtualization-20, Microsoft Enterprise Desktop Virtualization 2.0 seems to be no longer supported. 

The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. Please review within five business days and merge, or comment in the PR with any changes you'd like to see. Thanks!

**Review by sdwheeler — CHANGES_REQUESTED** [review]
You also need to delete the following folders:
- https://github.com/MicrosoftDocs/windows-powershell-docs/tree/main/docset/mdop/Microsoft.Medv.Administration.Commands.WorkspacePackager
- https://github.com/MicrosoftDocs/windows-powershell-docs/tree/main/docset/mdop/medv

**Review by JohanFreelancer9 — APPROVED** [review]
Copy review - only @sdwheeler's suggestions.

**Review by sdwheeler — APPROVED** [review]

**Comment by sdwheeler** [comment]
#sign-off

**Pull request merged**
