### PR TITLE
Update Unregister-SmisProvider.md

### PR DESCRIPTION
**Pull request by msbemba**
added description for Force

### CODE REVIEW

**Comment by msbemba** [comment]
This PR is a copy of PR 1430 as there was a conflict to merge.

**Comment by e0i** [comment]
@dariomws306 @tseward

Peer review needed for this PR. Thanks.

**Comment by e0i** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by e0i** [comment]
@tseward Any additional review for this PR? Thanks.

**Comment by tseward** [comment]
I like @dariomws306's suggestion.

**Comment by msbemba** [comment]
> Looks good but maybe we can start using this message for this parameter:
> 
> The Force switch specifies whether to suppress warning and confirmation messages. It can be useful in scripting to suppress interactive prompts. If the Force switch isn't provided in the command, you're prompted for administrative input if required.

Updated the document with your suggestion.

**Pull request merged**
