### PR TITLE
Add Wait parameter description 2012R2/2016 version

### PR DESCRIPTION
**Pull request by velkovb**

### CODE REVIEW

**Comment by e0i** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by e0i** [comment]
@dariomws306 @tseward

Peer review needed for this PR. Thanks.

**Comment by v-raaba** [comment]
Hi @velkovb  - We understand that these [PR criteria](https://review.docs.microsoft.com/en-us/office-authoring-guide/pr-criteria?branch=master) are new, and we appreciate your patience with the process. 

**Following are blocking issues that need to be resolved before we can merge:**

Conflicting files
docset/windows/failoverclusters/reset-clustervmmonitoredstate.md 

***

**Reference**

[Criteria used for pull request reviews](https://review.docs.microsoft.com/en-us/office-authoring-guide/pr-criteria?branch=master)



***

<Use this space to insert any comments.>

Thanks

**Comment by kenwith** [comment]
@v-raaba - is it possible to make those criteria you linked above public? This is a public repo and most of the PR's people submit won't have access to the link you provided. Thanks.

**Comment by v-raaba** [comment]
I’ll work on it!

Raaj

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by e0i** [comment]
Merge conflicts have been resolved.

**Pull request merged**
