### PR TITLE
Update log level description

### PR DESCRIPTION
**Pull request by MaratMussabekov**
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2008

### CODE REVIEW

**Comment by MaratMussabekov** [comment]
Dear @JohanFreelancer9,
kindly do the copy editor review for this PR.

Dear @e0i, for your information

Thank you

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by e0i** [comment]
Closing and re-opening to refresh validation checks.

**Comment by e0i** [comment]
@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

**Review by dariomws — APPROVED** [review]

**Comment by tseward** [comment]
This cmdlet uses the [DismLogLevel Enumeration
](https://docs.microsoft.com/windows-hardware/manufacture/desktop/dism/dismloglevel-enumeration#constants) Can you please use these descriptions of the log levels, instead?

**Review by get-itips — COMMENTED** [review]
agree with @tseward

**Comment by MaratMussabekov** [comment]
Hello @tseward , @get-itips ,
**This cmdlet uses the DismLogLevel Enumeration
Can you please use these descriptions of the log levels, instead?** - could you please advise, why it needs to combine 0 with 1 or 2, to show full information? like:
 ```-LogLevel "Errors,WarningsInfo"```
it differs from the behavior described for DismLogLevel Enumeration
Thank you!

**Comment by get-itips** [comment]
> Hello @tseward , @get-itips ,
> **This cmdlet uses the DismLogLevel Enumeration Can you please use these descriptions of the log levels, instead?** - could you please advise, why it needs to combine 0 with 1 or 2, to show full information? like:
> `-LogLevel "Errors,WarningsInfo"`
> it differs from the behavior described for DismLogLevel Enumeration
> Thank you!

Ok,
The type is "Microsoft.Dism.Commands.LogLevel" and accepts Errors, Warnings, WarningsInfo, so yes, I would accept your proposal. Thanks

**Review by get-itips — APPROVED** [review]

**Review by tseward — APPROVED** [review]

**Comment by garycentric** [comment]
In review.

**Comment by garycentric** [comment]
No preview links to view. Merging now.

**Pull request merged**
