### PR TITLE
add details

### PR DESCRIPTION
**Pull request by VLG17**
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1824

### CODE REVIEW

**Comment by e0i** [comment]
@VLG17 Please change the target branch of the PR from `live` to `master` to continue with the review.

**Comment by e0i** [comment]
@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by e0i** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by get-itips** [comment]
I like @dariomws suggestion for a simpler description and I would maintain the bold format for the cmdlet names that @VLG17 used.

**Pull request merged**
