### PR TITLE
Update new-vhd.md

### PR DESCRIPTION
**Pull request by msbemba**
Corrected Example 5

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by tseward** [comment]
Looks good.

**Comment by get-itips** [comment]
ok!

**Comment by dariomws306** [comment]
I think there is no update needed here:
image

**Comment by e0i** [comment]
@tseward @get-itips Do you agree with Dario's suggestion that no changes are necessary?

**Comment by get-itips** [comment]
> @tseward @get-itips Do you agree with Dario's suggestion that no changes are necessary?

On second thoughts, yes.

**Comment by tseward** [comment]
> @tseward @get-itips Do you agree with Dario's suggestion that no changes are necessary?

Agree

**Comment by e0i** [comment]
Thank you all for input. Closing.

**Pull request closed without merging**
