### PR TITLE
Updated the description of AllowManagement OS parameter

### PR DESCRIPTION
**Pull request by ManikaDhiman**

### CODE REVIEW

**Comment by ManikaDhiman** [comment]
#sign-off

**Comment by sdwheeler** [comment]
@ManikaDhiman This PR changes more than 5000 files. Your branch is not clean. You need to fix your branch. It may be easiest to start over.

**Comment by sdwheeler** [comment]
It looks like you have local builds turned on for the Microsoft Docs Authoring Pack in VS Code. You need to turn that off and start over.

**Comment by ManikaDhiman** [comment]
I will start afresh with a clean branch--closing this PR. Thanks!

**Pull request closed without merging**
