### PR TITLE
Solved issue #246

### PR DESCRIPTION
**Pull request by j0rt3g4**
Solving issue #246 .
### Add-KdsRootKey (both)
Decorated code with the PowerShell word.
Example 2 was incorrect, corrected by the comment and two tips.

### New-ADServiceAccount
Powershell and yaml missing in some parts

### set-AdServiceAccount
Added an example on 2012r2 and added a note on 2012 saying that the object to add must be unique domain-wide

### CODE REVIEW

**Comment by SharS** [comment]
Sent mail to Ken Withee and Dan Simpson re. the metadata changes. Asked Dan Simpson to review the technical changes.

**Comment by j0rt3g4** [comment]
Thank you @shars

**Comment by kenwith** [comment]
@j0rt3g4 - there is something wrong in this PR. It is changing 326 files and remove a lot of metadata. I think you need to close this one and figure out what happened and open another one. Please make sure to check the files that are changed. There should be only 1 file per PR.

**Comment by j0rt3g4** [comment]
I agree I'll review it

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request closed without merging**
