### PR TITLE
Added Windows Server wording

### PR DESCRIPTION
**Pull request by get-itips**
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/411

### CODE REVIEW

**Comment by e0i** [comment]
cc @yogkumgit

**Comment by e0i** [comment]
@dariomws306  @tseward

Peer review needed for this PR. Thanks.

**Comment by dariomws306** [comment]
Should we apply this update to W2012 and 2012 R2 versions?

**Comment by e0i** [comment]
> Should we apply this update to W2012 and 2012 R2 versions?

@tseward Any thoughts?

**Comment by dariomws306** [comment]
@get-itips what do you think?

**Comment by get-itips** [comment]
> @get-itips what do you think?

done as requested

**Comment by tseward** [comment]
Looks good.

**Comment by e0i** [comment]
The commits have been merged.

**Pull request merged**
