### PR TITLE
Update -Level parameter list

### PR DESCRIPTION
**Pull request by brbrahm**
Was missing "FilePath" and "PFN"

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by tseward** [comment]
Looks good.

**Comment by get-itips** [comment]
Hello

I could not find "FilePath" in Windows Server 2016 and Windows Server 2019 17763.615, could you please specify which version you used?

I could find "PFN"in Windows Server 2019 17763.615

**Comment by brbrahm** [comment]
@get-itips FilePath was added in 1903. I'm on the feature team and we have a work item to add descriptions and available versions to this document as well.

**Comment by get-itips** [comment]
@brbrahm Ok, so let's move on with it, I think that the branding that now says 2016 will be eventually changed to 2019 so I am ok with it.

**Comment by dariomws306** [comment]
Looks good.

**Comment by e0i** [comment]
@AndreaBarr The PR can be merged. Thanks.

**Comment by e0i** [comment]
@AndreaBarr The PR can be merged. Thanks.

**Comment by e0i** [comment]
@brbrahm FYI Public contributions are on hold for a short period of time due to internal maintenance. The PR will be merged immediately following the completion of maintenance. Thank you for your contributions.

**Pull request merged**
