### PR TITLE
Resolves #1629, #1711

### LINKED ISSUE #1629: Set-NetConnectionProfile usage example does not work
The usage example for changing the network category of a connection profile ( [Direct Link](https://docs.microsoft.com/en-us/powershell/module/netconnection/set-netconnectionprofile?view=win10-ps&source=docs#examples) ) does not work. Tested on Windows 10 Enterprise 1903 & Windows Server 2019.

The commands referenced in the article are reproduced here:

```

PS C:\> $NetworkProfile = Get-NetConnectionProfile -InterfaceAlias Ethernet1

PS C:\> $NetworkProfile.NetworkCategory = Public

PS C:\> Set-NetConnectionProfile -InputObject $NetworkProfile
```

The usage example could be shorted to the following (functional) single-command.
```
PS C:\> Set-NetConnectionProfile -InterfaceAlias Ethernet1 -NetworkCategory "Public"
```

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 983029b7-7f55-a30a-b842-ef19a0f88e7c
* Version Independent ID: 253ace06-2925-2ca8-4cb3-30d167678bfd
* Content: [Set-NetConnectionProfile (netconnection)](https://docs.microsoft.com/en-us/powershell/module/netconnection/set-netconnectionprofile?view=win10-ps&source=docs#feedback)
* Content Source: [docset/windows/netconnection/Set-NetConnectionProfile.md](https://github.com/MicrosoftDocs/windows-powershell-docs/blob/live/docset/windows/netconnection/Set-NetConnectionProfile.md)
* Product: **w10**
* Technology: **powershell-windows**
* GitHub Login: @andreabarr
* Microsoft Alias: **v-anbarr**

### PR DESCRIPTION
**Pull request by velkovb**
Fix example 1.
Fix -NetworkCategory parameter descirption.
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1629
https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1711

### CODE REVIEW

**Comment by e0i** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by get-itips** [comment]
Hello @velkovb Borislav, how are you?
It is true that _DomainAuthenticated_ is a possible value however it is not possible to set this value manually:
image

So I would either add a note beside it (cause I already saw users reporting not being able to set values that aren't settable) or remove it altogether (it makes more sense to mention this parameter value in the Get-NetConnectionProfile

What do you guys think @dariomws306 @tseward

**Comment by velkovb** [comment]
@get-itips I think it is best to include it as note.

**Comment by get-itips** [comment]
Thank you @velkovb 🥇

**Comment by tseward** [comment]
It is certainly an "accepted value", but there should be a textual note (not a [!NOTE]) in the parameter description that "`DomainAuthenticated` is automatically set and an error will be returned if manually specified in this cmdlet". Or something like:

Valid values are:

* Private
* Public
* DomainAuthenticated (this value is automatically set and will return an error if manually specified in this cmdlet)

**Comment by velkovb** [comment]
The parameter description already has it: 
### -NetworkCategory
Specifies an array of category types of a network.
You cannot set the DomainAuthenticated type by using this cmdlet.
The server automatically sets the value of DomainAuthenticated when the network is authenticated to a domain controller.

Would we repeat ourselves?

>

**Comment by get-itips** [comment]
> The parameter description already has it:
> 
> ### -NetworkCategory
> Specifies an array of category types of a network.
> You cannot set the DomainAuthenticated type by using this cmdlet.
> The server automatically sets the value of DomainAuthenticated when the network is authenticated to a domain controller.
> 
> Would we repeat ourselves?
> 
> >

I do not think it is necessary to repeat it.. thanks

**Comment by velkovb** [comment]
Ok, then should I revert last commit?

**Comment by get-itips** [comment]
> Ok, then should I revert last commit?

Yes, I think we can include the param value as long as there is a note...
Sorry for the misunderstanding

**Pull request merged**
