### PR TITLE
Update Get-BgpStatistics.md

### PR DESCRIPTION
**Pull request by msbemba**
added description for -Allroutingdomains

### CODE REVIEW

**Comment by msbemba** [comment]
This is a copy of PR 1432 which is closed due to merging conflicts.

**Comment by e0i** [comment]
@dariomws306 @tseward

Peer review needed for this PR. Thanks.

**Comment by msbemba** [comment]
Made Changes as per Peers Suggestion.

**Comment by dariomws306** [comment]
Hi @msbemba,

I made a mistake here. We should leave "Use this command to retrieve details about all routing domains" as description for this parameter. I think this sentence sounds better.

**Pull request merged**
