### PR TITLE
Enable-AdfsDeviceRegistration: Fix URL Link

### PR DESCRIPTION
**Pull request by X-Guardian**
This PR fixes the 'Configure On-Premises Conditional Access using registered devices' URL link in the `Enable-AdfsDeviceRegistration` documentation.

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306 @tseward

Peer review needed for this PR. Thanks.

**Comment by tiburd** [comment]
Hi, Simon/@X-Guardian, 

We are closing this PR because merging to Live is restricted to the PubOps team only. To find out more about the process, see the [PubOps Publishing Process page](https://review.docs.microsoft.com/en-us/office-authoring-guide/pubops-publishing-process?branch=master). If you resubmit this to the Master branch, the PubOps team will review, merge when ready, and publish to Live. Thanks.

**Comment by X-Guardian** [comment]
If you reopen this @tiburd, I can just change the target branch to master, rather than creating a whole new PR.

**Comment by e0i** [comment]
@tiburd The branch has been retargeted to `master`. Thanks.

**Pull request merged**
