### PR TITLE
Update Set-SmbServerConfiguration.md

### PR DESCRIPTION
**Pull request by msbemba**
Clarified examples with correct information.

### CODE REVIEW

**Comment by e0i** [comment]
@nenonix @JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by e0i** [comment]
@get-itips Additional input needed.

**Comment by v-raaba** [comment]
@e0i @msbemba Closing this PR. Please PR against Master.

**Pull request closed without merging**
