### PR TITLE
Update new-netfirewallrule.md

### PR DESCRIPTION
**Pull request by msbemba**
Changed Default Value for interfacetype

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306 @tseward

Peer review needed for this PR. Thanks.

**Comment by tseward** [comment]
Looks good.

**Comment by dariomws306** [comment]
Looks good but I think we should apply the same update to W2012 and W2012R2 versions.

**Comment by e0i** [comment]
> Looks good but I think we should apply the same update to W2012 and W2012R2 versions.

cc @msbemba

**Comment by msbemba** [comment]
Madechanges 

> > Looks good but I think we should apply the same update to W2012 and W2012R2 versions.
> 
> cc @msbemba

Made changes to 2012 and 2012r2 as well.

**Comment by e0i** [comment]
@AndreaBarr The PR is ready to be merged. Thanks.

**Pull request merged**
