### PR TITLE
Update Test-AppLockerPolicy.md

### PR DESCRIPTION
**Pull request by msbemba**
Changed the switch from -XMLPATH to _XMLPOLICY on example 1

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/windows-powershell-docs/issues/1898

**Comment by e0i** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by e0i** [comment]
@dariomws @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by garycentric** [comment]
In review.

**Pull request merged**
