### PR TITLE
Fix Add-VMNetworkAdapterExtendedAcl usage example

### PR DESCRIPTION
**Pull request by dhmhd**
Add-VMNetworkAdapterExtendedAcl cmdlet have no such parameter as "Timeout", but "IdleSessionTimeout"

### CODE REVIEW

**Comment by e0i** [comment]
@nenonix Minor copy editing is needed for this PR. Thanks.

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by dariomws306** [comment]
Looks good.

**Comment by get-itips** [comment]
Looks ok

**Comment by tseward** [comment]
Looks good.

**Comment by e0i** [comment]
@AndreaBarr This PR that has passed review can be merged. Thanks.

**Pull request merged**
