### PR TITLE
adjusted format

### PR DESCRIPTION
**Pull request by RAJU2529**
i made **offline** title and **online** title visible to the public

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by dariomws — COMMENTED** [review]
@RAJU2529 I don't understand this update. What impact are you expecting adding a break line? Do you have an example (another article)? I don't think that this update will allow the readers to see the titles.

**Review by get-itips — COMMENTED** [review]
I do not think that parameter names are supposed to be rendered in public version of articles.

**Comment by dariomws** [comment]
@RAJU2529 kindly check other articles. None of them is showing the kind of titles.

**Comment by RAJU2529** [comment]
@dariomws   Yes sir  tomorrow afternoon I check most of the articles, if titles are not visible means , then tithes  made to be visible to public.
Thanking you.

**Comment by dariomws** [comment]
@RAJU2529 thanks!

**Comment by sdwheeler** [comment]
This PR does not fix the problem. The problem is a known issue in the OPS publishing pipeline for PowerShell cmdlet reference. The rendering tools do not render the parameter set names and the template does not include them even if the rendering tool provided the information.

We are working on a fix for the tools but that is still several months away.

**Pull request closed without merging**
