### PR TITLE
Fix 1655 wrongcmdletname

### PR DESCRIPTION
**Pull request by velkovb**

### CODE REVIEW

**Comment by e0i** [comment]
Introduces additional changes for all supported versions in resolution of MicrosoftDocs/feedback#1655

**Comment by e0i** [comment]
@dariomws306 @get-itips

Peer review needed for this PR. Thanks.

**Comment by get-itips** [comment]
Ok!

**Comment by dariomws306** [comment]
Looks good!

**Comment by e0i** [comment]
@AndreaBarr This PR can be merged. Thanks.

**Pull request merged**
