### PR TITLE
Update OS codename reference to OS's release name

### PR DESCRIPTION
**Pull request by rdbahm**
Small tweak to documentation to use the OS's release name instead of the codename.

### CODE REVIEW

**Comment by e0i** [comment]
@rdbahm Thank you for bringing to attention this issue that has been found to be widespread across the repository.

**Comment by e0i** [comment]
@dariomws306 @tseward

Peer review needed for this PR. Thanks.

**Comment by dariomws306** [comment]
Looks good.

I think we should apply the same update on 2012 and 2016 version, and also in Disable-NetAdapterRss.

@e0i could you assign it to someone? (I am available)

**Comment by tseward** [comment]
Can we change the wording to somethings similar to https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1293#issuecomment-532293845

**Comment by rmca14** [comment]
Acrolinx didn't run.

**Pull request merged**
