### PR TITLE
Update New-NfsClientgroup.md

### PR DESCRIPTION
**Pull request by msbemba**
Able to add one more IP like the user mentioned. Changing the value for accept wildcards to True

### CODE REVIEW

**Comment by msbemba** [comment]
Issue#https://github.com/MicrosoftDocs/windows-powershell-docs/issues/2799

**Comment by msbemba** [comment]
@JohanFreelancer9 Please copy review

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by get-itips — APPROVED** [review]
@msbemba Can you add an example? thanks

**Review by dariomws — COMMENTED** [review]
@msbemba, could you kindly share the example you have tried?

I think wildcards in cmdlet parameters don't work in this way:
https://docs.microsoft.com/powershell/scripting/developer/cmdlet/supporting-wildcard-characters-in-cmdlet-parameters

Thanks.

**Comment by msbemba** [comment]
> @msbemba, could you kindly share the example you have tried?
> 
> I think wildcards in cmdlet parameters don't work in this way: https://docs.microsoft.com/powershell/scripting/developer/cmdlet/supporting-wildcard-characters-in-cmdlet-parameters
> 
> Thanks.

@dariomws I don’t have access to the NFs server currently. Will be back on January 6th to provide you the details.

**Comment by msbemba** [comment]
> > @msbemba, could you kindly share the example you have tried?
> > I think wildcards in cmdlet parameters don't work in this way: https://docs.microsoft.com/powershell/scripting/developer/cmdlet/supporting-wildcard-characters-in-cmdlet-parameters
> > Thanks.
> 
> @dariomws I don’t have access to the NFs server currently. Will be back on January 6th to provide you the details.

@dariomws  This is what the user tested. I still don't have access but should have access in a week. Let me know if you need more information

PS C:\Users\administrator.CORP> Get-NfsClientgroup

ClientGroupName ClientGroupMembers

G1 {172.20.1.}
G2 {1.2.3.}
G3 {10.20.30.1, 10.20.30.2}

PS C:\Users\administrator.CORP> New-NfsClientgroup -name "G4" -AddMember "192.168.1.*"
PS C:\Users\administrator.CORP> Get-NfsClientgroup

ClientGroupName ClientGroupMembers

G1 {172.20.1.}
G2 {1.2.3.}
G3 {10.20.30.1, 10.20.30.2}
G4 {192.168.1.*}

**Review by tseward — APPROVED** [review]

**Pull request merged**
