### PR TITLE
Update Get-ADUser.md

### PR DESCRIPTION
**Pull request by sowjanya365**
Issue #1625 : Content has been updated.

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by get-itips** [comment]
Hello @sowjanya365 

Hope you are doing good.

First of all, I am assuming that "_Inmediate children of that path_" refers to user objects under the given OU (SearchBase). This can be maybe easily confused with "children OUs"

I am not positive on this change:

> A OneLevel query searches the immediate children of that path or object.This option only works when an OU is given as the SearchBase. If a user is given, no results are returned.

In my lab, I have 

_Moe Howard_ on _OU=docspr,DC=onpremlab,DC=net_

_Shremp Howard_ on _DC=onpremlab,DC=net_


If I run:

`Get-ADUser -Filter "Name -eq 'Moe Howard'" -SearchBase "OU=docspr,DC=onpremlab,DC=net" -SearchScope OneLevel`

User Moe Howard Found

If I run 

`Get-ADUser -Filter "Name -eq 'Shremp Howard'" -SearchScope OneLevel`

and

`Get-ADUser -Filter "Name -eq 'Shremp Howard'" -SearchBase "DC=onpremlab,DC=net" -SearchScope OneLevel`

image

With both I get results


So I think that "...If a user is given, no results are returned..." it is not true. Or maybe I misunderstood the creator of the issue.

Now, the other sentence

> A Base query searches only for the given user. If an OU is given as the SearchBase, no results will be returned.

I could reproduce this one.

I would like to know @dariomws306 and @tseward opinions on this one

Thank you!

**Comment by dariomws306** [comment]
@get-itips I have tried and I think he's right. If you try:

Get-ADUser -Filter "Name -eq 'Moe Howard'" -SearchBase "CN=Moe Howard,OU=docspr,DC=onpremlab,DC=net" -SearchScope OneLevel

Or

Get-ADUser -Filter "Name -eq 'Shremp Howard'" -SearchBase "CN=Shremp Howard,DC=onpremlab,DC=net" -SearchScope OneLevel

No results are returned. I have to say that I'm not totally happy with the wording... What do you think @tseward?

**Comment by tseward** [comment]
```powershell
PS C:\Users\trevor.seward> Get-ADUser -Filter "Name -eq 'Trevor Seward'" -SearchBase 'OU=HQ,DC=lab,DC=cobaltatom,DC=com' -SearchScope OneLevel
PS C:\Users\trevor.seward> Get-ADUser -Filter "Name -eq 'Trevor Seward'" -SearchBase 'OU=HQ,DC=lab,DC=cobaltatom,DC=com'


DistinguishedName : CN=Trevor Seward,OU=Administrators,OU=HQ,DC=lab,DC=cobaltatom,DC=com
```

**Comment by tseward** [comment]
@dariomws306 the wording confuses me, as well.

I would re-word this to:

"A SearchScope with a Base parameter searches only for the given user. If an OU is specified in the SearchBase parameter, no user will be returned by, for example, a specified Filter."

This statement is not accurate (but it *should* be if you're a good admin). You can create a user at CN=_username_,DC=domain,DC=com and using `-SearchScope OneLevel` will return the result. Unless I'm mis-reading it...

"A OneLevel query searches the immediate children of that path or object. This option only works when an OU is given as the SearchBase. If a user is given, no results are returned."

```powershell
PS C:\Users\trevor.seward> Get-ADUser -Filter "Name -eq 'test123'" -SearchScope OneLevel

DistinguishedName : CN=test123,DC=lab,DC=cobaltatom,DC=com
```

**Comment by dariomws306** [comment]
@tseward agree, looks better!

**Comment by sowjanya365** [comment]
Thank you so much @get-itips @dariomws306 @tseward 

Yes, I agree with the inputs that you all shared. Very valuable and appreciate all of your time on this. :)

@tseward I just wanted to make sure before I edit the content, so I should replace the first sentence with the following one. And the second sentence remains the same?

"A SearchScope with a Base value searches only for the given user. If an OU is specified in the SearchBase parameter, no user will be returned by, for example, a specified Filter statement."

"A Base query searches only for the given user. If an OU is given as the SearchBase, no results will be returned."

Looking forward to your response. Thanks in advance!!! :)

**Comment by dariomws306** [comment]
@sowjanya365,

"A Base query searches only for the given user. If an OU is given as the SearchBase, no results will be returned."
Should be replaced with:
"A SearchScope with a Base value searches only for the given user. If an OU is specified in the SearchBase parameter, no user will be returned by, for example, a specified Filter statement."

"A OneLevel query searches the immediate children of that path or object.	A OneLevel query searches the immediate children of that path or object. This option only works when an OU is given as the SearchBase. If a user is given, no results are returned."
Shoud be replace with:
"A OneLevel query searches the immediate children of that path or object. This option only works when an OU is given as the SearchBase. If a user is given, no results are returned."

**Comment by e0i** [comment]
@sowjanya365 Please let me know when you follow-up with every revision suggestion provided by the reviewers. Thank you.

**Comment by sowjanya365** [comment]
Hi @e0i 

I really apologize for the delay, I'm not sure why I am not receiving the email alerts from GitHub.

I'm going to make these changes in the PR now. Thank you!

**Comment by sowjanya365** [comment]
Hi @e0i 

Content has been updated now. Please take it forward.

**Pull request merged**
