### PR TITLE
Update set-vmprocessor.md

### PR DESCRIPTION
**Pull request by sowjanya365**
Issue #432 - Document has been updated with with "HwThreadCountPerCore" value limitations.

### CODE REVIEW

**Comment by e0i** [comment]
@JohanFreelancer9 Minor copy editing and style check is needed for this PR. Thanks.

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by get-itips** [comment]
Agree

**Comment by dariomws306** [comment]
Agree

**Comment by e0i** [comment]
Pending final OK via Trevor

**Comment by tseward** [comment]
Yes to the current PR but please also add this to the PR. Find the section under "Guest VMs may observe changes to CPU topology across VM mobility scenarios":

"both the VM's HwThreadCountPerCore setting and the realized value"

changed the word "realized" to "actual".

**Comment by sowjanya365** [comment]
Hi @tseward 

Thank you for your inputs. Are you suggesting this change on some other document? Kindly share with me the URL. Thank you.

**Comment by tseward** [comment]
My apologies, it was in a different document.

**Comment by e0i** [comment]
@AndreaBarr The PR that has passed peer review can now be merged. Thanks.

**Pull request merged**
