### PR TITLE
replaced  VMCollectionTpe to VMCollectionType

### PR DESCRIPTION
**Pull request by RAJU2529**
as per user report #1662 ,
i replaced the word  **VMCollectionTpe**  to   **VMCollectionType**

### CODE REVIEW

**Comment by RAJU2529** [comment]
@illfated @jvsam  , please review the changes and approve it if found correct

**Comment by illfated** [comment]
#sign-off

**Comment by illfated** [comment]
@RAJU2529 : Looks like no more actions are needed. All we need to do now is to wait for the merge.
(BTW, Jo (jvsam) will probably not attend any of the MicrosoftDocs/windows-powershell-docs tickets.)

**Comment by e0i** [comment]
@RAJU2529 Please change the PR branch target to `master`. Thank you for your contributions.

**Comment by illfated** [comment]
Good point, I did not notice or think that the wrong branch could be picked here.
@RAJU2529 : Hoping you are doing well and that it will be simple enough to switch branches.

**Comment by RAJU2529** [comment]
@illfated . Changed PR branch live to master

**Comment by illfated** [comment]
Very well. Should be good to go now.

#sign-off

**Comment by e0i** [comment]
@dariomws306 @get-itips @tseward

Peer review needed for this PR. Thanks.

**Comment by illfated** [comment]
#sign-off

**Comment by RAJU2529** [comment]
I think it's a time to merge the modified content

**Comment by illfated** [comment]
```MarkDown
---
ms.mktglfcycl: manage
ms.sitesec: library
ms.author: v-anbarr
author: andreabarr
description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
external help file: Microsoft.HyperV.PowerShell.Cmdlets.dll-Help.xml
keywords: powershell, cmdlet
manager: jasgro
ms.date: 12/20/2016
ms.prod: w10
ms.technology: powershell-windows
```

CC: @AndreaBarr , @JasonGerend

**Comment by e0i** [comment]
@illfated Although we appreciate community contributors taking the initiative to move things forward, please note that it is not advised to tag reviewers and authors because of the machinery involved in the review process. The tagged people might no longer be part of the team, or it might not actually be their responsibility, and for other variety of reasons.  Thanks.

**Pull request merged**
