### PR TITLE
Update set-mppreference.md

### PR DESCRIPTION
**Pull request by sowjanya365**
Issue #876 : "-ThreatIDDefaultAction_Actions" parameter value has been corrected.

### CODE REVIEW

**Comment by e0i** [comment]
@dariomws306 @get-itips

Peer review needed for this PR. Thanks.

**Comment by dariomws306** [comment]
I am ok with this but based on the issue author feedback the same fix should be applied to Add-MpPreference.

**Comment by get-itips** [comment]
Ok with @dariomws306

**Comment by e0i** [comment]
@sowjanya365 Please follow-up with Dario's suggestion to apply additional fixes. Thanks.

**Comment by sowjanya365** [comment]
Hi @e0i 

Apologies for the delay in response. Now I've applied the fix to Add-MpPreference as well. 

PR for your reference. https://github.com/MicrosoftDocs/windows-powershell-docs/pull/1177

Thank you.

**Comment by e0i** [comment]
@AndreaBarr This PR that has passed review can be merged. Thanks.

**Pull request merged**
